# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supplyWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(337, 157)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.Frame_2 = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Frame_2.setFont(font)
        self.Frame_2.setProperty("PeripheralCollectionInner", "")
        self.Frame_2.setObjectName("Frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Frame_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.Frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.Frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.Frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.PCS_LABEL = QtWidgets.QLabel(self.Frame_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PCS_LABEL.setFont(font)
        self.PCS_LABEL.setObjectName("PCS_LABEL")
        self.gridLayout_2.addWidget(self.PCS_LABEL, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.PV3_LABEL = QtWidgets.QLabel(self.Frame_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PV3_LABEL.setFont(font)
        self.PV3_LABEL.setObjectName("PV3_LABEL")
        self.gridLayout_2.addWidget(self.PV3_LABEL, 2, 1, 1, 1)
        self.PV2_LABEL = QtWidgets.QLabel(self.Frame_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PV2_LABEL.setFont(font)
        self.PV2_LABEL.setObjectName("PV2_LABEL")
        self.gridLayout_2.addWidget(self.PV2_LABEL, 1, 1, 1, 1)
        self.PV1_LABEL = QtWidgets.QLabel(self.Frame_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PV1_LABEL.setFont(font)
        self.PV1_LABEL.setObjectName("PV1_LABEL")
        self.gridLayout_2.addWidget(self.PV1_LABEL, 0, 1, 1, 1)
        self.PV1BOX = QtWidgets.QDoubleSpinBox(self.Frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PV1BOX.sizePolicy().hasHeightForWidth())
        self.PV1BOX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PV1BOX.setFont(font)
        self.PV1BOX.setDecimals(3)
        self.PV1BOX.setMinimum(-5.0)
        self.PV1BOX.setMaximum(5.0)
        self.PV1BOX.setSingleStep(0.1)
        self.PV1BOX.setObjectName("PV1BOX")
        self.gridLayout_2.addWidget(self.PV1BOX, 0, 2, 1, 1)
        self.PV2BOX = QtWidgets.QDoubleSpinBox(self.Frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PV2BOX.sizePolicy().hasHeightForWidth())
        self.PV2BOX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PV2BOX.setFont(font)
        self.PV2BOX.setDecimals(3)
        self.PV2BOX.setMinimum(-3.3)
        self.PV2BOX.setMaximum(3.3)
        self.PV2BOX.setSingleStep(0.1)
        self.PV2BOX.setObjectName("PV2BOX")
        self.gridLayout_2.addWidget(self.PV2BOX, 1, 2, 1, 1)
        self.PV3BOX = QtWidgets.QDoubleSpinBox(self.Frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PV3BOX.sizePolicy().hasHeightForWidth())
        self.PV3BOX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PV3BOX.setFont(font)
        self.PV3BOX.setDecimals(3)
        self.PV3BOX.setMaximum(3.3)
        self.PV3BOX.setSingleStep(0.1)
        self.PV3BOX.setObjectName("PV3BOX")
        self.gridLayout_2.addWidget(self.PV3BOX, 2, 2, 1, 1)
        self.PCSBOX = QtWidgets.QDoubleSpinBox(self.Frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PCSBOX.sizePolicy().hasHeightForWidth())
        self.PCSBOX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PCSBOX.setFont(font)
        self.PCSBOX.setDecimals(3)
        self.PCSBOX.setMaximum(3.3)
        self.PCSBOX.setSingleStep(0.1)
        self.PCSBOX.setObjectName("PCSBOX")
        self.gridLayout_2.addWidget(self.PCSBOX, 3, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.Frame_2)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Form)
        self.PV1BOX.valueChanged['double'].connect(Form.setPV1)
        self.PV2BOX.valueChanged['double'].connect(Form.setPV2)
        self.PV3BOX.valueChanged['double'].connect(Form.setPV3)
        self.PCSBOX.valueChanged['double'].connect(Form.setPCS)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.frame_3.setProperty("class", _translate("Form", "ControlWidget"))
        self.label_2.setText(_translate("Form", " IV Sources"))
        self.Frame_2.setProperty("class", _translate("Form", "ControlWidgetInner"))
        self.label_10.setText(_translate("Form", "PV3"))
        self.label_12.setText(_translate("Form", "PV2 "))
        self.label_11.setText(_translate("Form", "PV1 "))
        self.PCS_LABEL.setText(_translate("Form", "0-3.3mA"))
        self.label_9.setText(_translate("Form", "PCS"))
        self.PV3_LABEL.setText(_translate("Form", "0 - 3.3V"))
        self.PV2_LABEL.setText(_translate("Form", "-3.3 to 3.3V"))
        self.PV1_LABEL.setText(_translate("Form", "-5 to 5V"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
