# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customSweep.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(356, 63)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 2, 2, 1, 1)
        self.startBox = QtWidgets.QDoubleSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startBox.sizePolicy().hasHeightForWidth())
        self.startBox.setSizePolicy(sizePolicy)
        self.startBox.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.startBox.setFont(font)
        self.startBox.setMinimum(-100000.0)
        self.startBox.setMaximum(100000.0)
        self.startBox.setObjectName("startBox")
        self.gridLayout.addWidget(self.startBox, 4, 2, 1, 1)
        self.stopBox = QtWidgets.QDoubleSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBox.sizePolicy().hasHeightForWidth())
        self.stopBox.setSizePolicy(sizePolicy)
        self.stopBox.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.stopBox.setFont(font)
        self.stopBox.setMinimum(-100000.0)
        self.stopBox.setMaximum(100000.0)
        self.stopBox.setProperty("value", 100.0)
        self.stopBox.setObjectName("stopBox")
        self.gridLayout.addWidget(self.stopBox, 4, 3, 1, 1)
        self.toolButton = QtWidgets.QToolButton(Form)
        icon = QtGui.QIcon.fromTheme("window-close")
        self.toolButton.setIcon(icon)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 2, 5, 1, 1)
        self.numBox = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numBox.sizePolicy().hasHeightForWidth())
        self.numBox.setSizePolicy(sizePolicy)
        self.numBox.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.numBox.setFont(font)
        self.numBox.setMinimum(2)
        self.numBox.setMaximum(1000)
        self.numBox.setProperty("value", 10)
        self.numBox.setObjectName("numBox")
        self.gridLayout.addWidget(self.numBox, 4, 4, 1, 2)
        self.enable = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enable.sizePolicy().hasHeightForWidth())
        self.enable.setSizePolicy(sizePolicy)
        self.enable.setMinimumSize(QtCore.QSize(20, 0))
        self.enable.setText("")
        self.enable.setObjectName("enable")
        self.gridLayout.addWidget(self.enable, 2, 0, 1, 1)
        self.cmd = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd.sizePolicy().hasHeightForWidth())
        self.cmd.setSizePolicy(sizePolicy)
        self.cmd.setObjectName("cmd")
        self.gridLayout.addWidget(self.cmd, 2, 3, 1, 2)

        self.retranslateUi(Form)
        self.toolButton.clicked.connect(Form.remove)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.name, self.cmd)
        Form.setTabOrder(self.cmd, self.toolButton)
        Form.setTabOrder(self.toolButton, self.startBox)
        Form.setTabOrder(self.startBox, self.stopBox)
        Form.setTabOrder(self.stopBox, self.numBox)
        Form.setTabOrder(self.numBox, self.enable)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name.setPlaceholderText(_translate("Form", "title"))
        self.startBox.setSuffix(_translate("Form", " start"))
        self.stopBox.setSuffix(_translate("Form", " stop"))
        self.toolButton.setText(_translate("Form", "..."))
        self.numBox.setSuffix(_translate("Form", "points"))
        self.cmd.setPlaceholderText(_translate("Form", "function name"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
