# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sineWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(336, 153)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton.sizePolicy().hasHeightForWidth())
        self.commandLinkButton.setSizePolicy(sizePolicy)
        self.commandLinkButton.setMinimumSize(QtCore.QSize(94, 0))
        self.commandLinkButton.setMaximumSize(QtCore.QSize(30, 30))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout_2.addWidget(self.commandLinkButton)
        self.verticalLayout_4.addWidget(self.frame)
        self.Frame_3 = QtWidgets.QFrame(self.frame_4)
        self.Frame_3.setProperty("PeripheralCollectionInner", "")
        self.Frame_3.setObjectName("Frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Frame_3)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_30 = QtWidgets.QLabel(self.Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 3, 0, 1, 1)
        self.SINE1BOX = QtWidgets.QDoubleSpinBox(self.Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SINE1BOX.sizePolicy().hasHeightForWidth())
        self.SINE1BOX.setSizePolicy(sizePolicy)
        self.SINE1BOX.setMinimum(0.2)
        self.SINE1BOX.setMaximum(5000.0)
        self.SINE1BOX.setProperty("value", 500.0)
        self.SINE1BOX.setObjectName("SINE1BOX")
        self.gridLayout_3.addWidget(self.SINE1BOX, 0, 2, 1, 1)
        self.WAVE2_FREQ = QtWidgets.QLabel(self.Frame_3)
        self.WAVE2_FREQ.setObjectName("WAVE2_FREQ")
        self.gridLayout_3.addWidget(self.WAVE2_FREQ, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 1, 0, 1, 1)
        self.SINE2BOX = QtWidgets.QDoubleSpinBox(self.Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SINE2BOX.sizePolicy().hasHeightForWidth())
        self.SINE2BOX.setSizePolicy(sizePolicy)
        self.SINE2BOX.setMinimum(0.2)
        self.SINE2BOX.setMaximum(5000.0)
        self.SINE2BOX.setProperty("value", 500.0)
        self.SINE2BOX.setObjectName("SINE2BOX")
        self.gridLayout_3.addWidget(self.SINE2BOX, 1, 2, 1, 1)
        self.WAVE1_FREQ = QtWidgets.QLabel(self.Frame_3)
        self.WAVE1_FREQ.setObjectName("WAVE1_FREQ")
        self.gridLayout_3.addWidget(self.WAVE1_FREQ, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.Frame_3)
        self.comboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.Frame_3)
        self.comboBox_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 3, 1, 1)
        self.SINEPHASE = QtWidgets.QDoubleSpinBox(self.Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SINEPHASE.sizePolicy().hasHeightForWidth())
        self.SINEPHASE.setSizePolicy(sizePolicy)
        self.SINEPHASE.setDecimals(1)
        self.SINEPHASE.setMaximum(359.0)
        self.SINEPHASE.setObjectName("SINEPHASE")
        self.gridLayout_3.addWidget(self.SINEPHASE, 3, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 2, 1, 2)
        self.verticalLayout_4.addWidget(self.Frame_3)
        self.verticalLayout.addWidget(self.frame_4)

        self.retranslateUi(Form)
        self.commandLinkButton.clicked.connect(Form.loadSineTable)
        self.SINE1BOX.valueChanged['double'].connect(Form.setSINE1)
        self.SINE2BOX.valueChanged['double'].connect(Form.setSINE2)
        self.pushButton_4.clicked.connect(Form.setSinePhase)
        self.comboBox.currentIndexChanged['int'].connect(Form.setW1Type)
        self.comboBox_2.currentIndexChanged['int'].connect(Form.setW2Type)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.frame_4.setProperty("class", _translate("Form", "ControlWidget"))
        self.label_3.setText(_translate("Form", "Arbitrary Waveform Generators"))
        self.commandLinkButton.setToolTip(_translate("Form", "Edit the waveform table by setting a new function"))
        self.commandLinkButton.setText(_translate("Form", "Edit"))
        self.Frame_3.setProperty("class", _translate("Form", "ControlWidgetInner"))
        self.label_30.setText(_translate("Form", "phase"))
        self.WAVE2_FREQ.setText(_translate("Form", "10Hz to 5KHz"))
        self.label_29.setText(_translate("Form", "W2"))
        self.WAVE1_FREQ.setText(_translate("Form", "10Hz to 5KHz"))
        self.label_17.setText(_translate("Form", "W1"))
        self.comboBox.setItemText(0, _translate("Form", "sine"))
        self.comboBox.setItemText(1, _translate("Form", "tria"))
        self.comboBox_2.setItemText(0, _translate("Form", "sine"))
        self.comboBox_2.setItemText(1, _translate("Form", "tria"))
        self.pushButton_4.setText(_translate("Form", "SET PHASE"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
