metadata:
  author: FOSSASIA
  projectname: PSLab-desktop-apps
  version: development

build:
  doctheme: sphinx_fossasia_theme
  docpath: docs
  logo: docs/images/logo.png
  markdown_flavour: markdown_github

publish:
  ghpages:
    docurl: pslabdesktop.fossasia.org
