# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rodpendulum.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widgetFrameOuter = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetFrameOuter.sizePolicy().hasHeightForWidth())
        self.widgetFrameOuter.setSizePolicy(sizePolicy)
        self.widgetFrameOuter.setStyleSheet("")
        self.widgetFrameOuter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.widgetFrameOuter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.widgetFrameOuter.setObjectName("widgetFrameOuter")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetFrameOuter)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.widgetFrameOuter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setMinimumSize(QtCore.QSize(94, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(94, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setStyleSheet("QProgressBar:horizontal {\n"
"                                                        border: 1px solid gray;\n"
"                                                        border-radius: 3px;\n"
"                                                        background: white;\n"
"                                                        padding: 1px;\n"
"                                                        text-align: right;\n"
"                                                        margin-right: 5ex;\n"
"                                                        }\n"
"                                                        QProgressBar::chunk:horizontal {\n"
"                                                        background: qlineargradient(x1: 0, y1: 0.5, x2: 1, y2: 0.5,\n"
"                                                        stop: 0 #467, stop:1 white);\n"
"                                                        margin-right: 1px; /* space */\n"
"                                                        width: 5px;\n"
"                                                        }\n"
"                                                    ")
        self.progressBar.setMaximum(2500)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.timerProgress = QtWidgets.QProgressBar(self.frame_4)
        self.timerProgress.setMaximumSize(QtCore.QSize(16777215, 18))
        self.timerProgress.setStyleSheet("")
        self.timerProgress.setMaximum(60)
        self.timerProgress.setProperty("value", 0)
        self.timerProgress.setTextVisible(True)
        self.timerProgress.setObjectName("timerProgress")
        self.horizontalLayout_2.addWidget(self.timerProgress)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.widgetFrameOuter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resultsTable = QtWidgets.QTableWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsTable.sizePolicy().hasHeightForWidth())
        self.resultsTable.setSizePolicy(sizePolicy)
        self.resultsTable.setMinimumSize(QtCore.QSize(360, 0))
        self.resultsTable.setAlternatingRowColors(True)
        self.resultsTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.resultsTable.setGridStyle(QtCore.Qt.DashLine)
        self.resultsTable.setRowCount(100)
        self.resultsTable.setColumnCount(1)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.horizontalHeader().setDefaultSectionSize(150)
        self.resultsTable.horizontalHeader().setMinimumSectionSize(40)
        self.resultsTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.resultsTable)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 10, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 8, 0, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 13, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setMinimumSize(QtCore.QSize(30, 0))
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 4, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 15, 0, 1, 1)
        self.averageLabel = QtWidgets.QLabel(self.frame_3)
        self.averageLabel.setObjectName("averageLabel")
        self.gridLayout_2.addWidget(self.averageLabel, 5, 1, 1, 1)
        self.averageLabel_2 = QtWidgets.QLabel(self.frame_3)
        self.averageLabel_2.setObjectName("averageLabel_2")
        self.gridLayout_2.addWidget(self.averageLabel_2, 10, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 11, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.gLabel = QtWidgets.QLabel(self.frame_3)
        self.gLabel.setObjectName("gLabel")
        self.gridLayout_2.addWidget(self.gLabel, 13, 1, 1, 1)
        self.lenBox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.lenBox.setObjectName("lenBox")
        self.gridLayout_2.addWidget(self.lenBox, 11, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 12, 0, 1, 2)
        self.pointBox = QtWidgets.QSpinBox(self.frame_3)
        self.pointBox.setMinimum(5)
        self.pointBox.setMaximum(1000)
        self.pointBox.setObjectName("pointBox")
        self.gridLayout_2.addWidget(self.pointBox, 0, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.frame_3)
        self.line_4.setMinimumSize(QtCore.QSize(30, 0))
        self.line_4.setLineWidth(1)
        self.line_4.setMidLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 0, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.frame_3)
        self.line_5.setMinimumSize(QtCore.QSize(30, 0))
        self.line_5.setLineWidth(1)
        self.line_5.setMidLineWidth(0)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 16, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 16, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.gridLayout_3.addWidget(self.widgetFrameOuter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.run)
        self.pushButton_3.clicked.connect(MainWindow.stop)
        self.pushButton_4.clicked.connect(MainWindow.calcAvg)
        self.comboBox.currentIndexChanged['int'].connect(MainWindow.setPendulumType)
        self.pushButton_6.clicked.connect(MainWindow.calculateg)
        self.pointBox.editingFinished.connect(MainWindow.setTotalPoints)
        self.pushButton_5.clicked.connect(MainWindow.saveData)
        self.pushButton_2.clicked.connect(MainWindow.clearTable)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.widgetFrameOuter.setProperty("class", _translate("MainWindow", "PeripheralCollection"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop"))
        self.progressBar.setFormat(_translate("MainWindow", "%v"))
        self.timerProgress.setToolTip(_translate("MainWindow", "Time left before the stopwatch overflows.\n"
"                                                        Oscillations must finish within this time limit\n"
"                                                    "))
        self.timerProgress.setFormat(_translate("MainWindow", "%v Seconds to timeout"))
        self.frame_2.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.resultsTable.setToolTip(_translate("MainWindow", "List of time periods for complete oscillations.\n"
"                                                        Click and drag to select points.\n"
"                                                        Hold down CTRL key and click to select non consecutive points\n"
"                                                    "))
        self.comboBox.setItemText(0, _translate("MainWindow", "Simple Pendulum"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Rod Pendulum"))
        self.pushButton_6.setText(_translate("MainWindow", "Calculate"))
        self.averageLabel.setText(_translate("MainWindow", "result"))
        self.averageLabel_2.setText(_translate("MainWindow", "Value of g using :"))
        self.label_2.setText(_translate("MainWindow", "Length (cm)"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "Obtain average of data points selected in the\n"
"                                                                    table\n"
"                                                                "))
        self.pushButton_4.setText(_translate("MainWindow", "Average Selected points>"))
        self.label.setText(_translate("MainWindow", "Data Analysis"))
        self.label.setProperty("class", _translate("MainWindow", "headingLabel"))
        self.gLabel.setText(_translate("MainWindow", "g:"))
        self.label_3.setText(_translate("MainWindow", "Points to acquire"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear Table"))
        self.pushButton_5.setText(_translate("MainWindow", "Save Table"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
