# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'advancedCal.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(456, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMaximumSize(QtCore.QSize(650, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout.setContentsMargins(0, 5, 0, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.Frame_4 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame_4.sizePolicy().hasHeightForWidth())
        self.Frame_4.setSizePolicy(sizePolicy)
        self.Frame_4.setProperty("PeripheralCollectionInner", "")
        self.Frame_4.setObjectName("Frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Frame_4)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line = QtWidgets.QFrame(self.Frame_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 0, 1, 2)
        self.tableLayout = QtWidgets.QVBoxLayout()
        self.tableLayout.setObjectName("tableLayout")
        self.gridLayout_4.addLayout(self.tableLayout, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.Frame_4, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.Button480pF_4 = QtWidgets.QPushButton(self.frame_4)
        self.Button480pF_4.setObjectName("Button480pF_4")
        self.verticalLayout_4.addWidget(self.Button480pF_4)
        self.Button480pF_3 = QtWidgets.QPushButton(self.frame_4)
        self.Button480pF_3.setObjectName("Button480pF_3")
        self.verticalLayout_4.addWidget(self.Button480pF_3)
        self.Button1uF_3 = QtWidgets.QPushButton(self.frame_4)
        self.Button1uF_3.setObjectName("Button1uF_3")
        self.verticalLayout_4.addWidget(self.Button1uF_3)
        self.Button100uF_3 = QtWidgets.QPushButton(self.frame_4)
        self.Button100uF_3.setObjectName("Button100uF_3")
        self.verticalLayout_4.addWidget(self.Button100uF_3)
        self.ButtonCCS_3 = QtWidgets.QPushButton(self.frame_4)
        self.ButtonCCS_3.setObjectName("ButtonCCS_3")
        self.verticalLayout_4.addWidget(self.ButtonCCS_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.ButtonCCS_4 = QtWidgets.QPushButton(self.frame_4)
        self.ButtonCCS_4.setObjectName("ButtonCCS_4")
        self.verticalLayout_4.addWidget(self.ButtonCCS_4)
        self.gridLayout.addWidget(self.frame_4, 0, 0, 1, 1)
        self.widgetLayout = QtWidgets.QHBoxLayout()
        self.widgetLayout.setObjectName("widgetLayout")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_9.setObjectName("pushButton_9")
        self.widgetLayout.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_8.setObjectName("pushButton_8")
        self.widgetLayout.addWidget(self.pushButton_8)
        self.gridLayout.addLayout(self.widgetLayout, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.frame_7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_9.clicked.connect(MainWindow.recover)
        self.pushButton_8.clicked.connect(MainWindow.upload)
        self.Button480pF_3.clicked.connect(MainWindow.cal480)
        self.Button1uF_3.clicked.connect(MainWindow.cal1)
        self.Button100uF_3.clicked.connect(MainWindow.cal100)
        self.ButtonCCS_3.clicked.connect(MainWindow.calPCS)
        self.Button480pF_4.clicked.connect(MainWindow.calSock)
        self.ButtonCCS_4.clicked.connect(MainWindow.reset)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Edit Calibration"))
        self.frame_7.setProperty("class", _translate("MainWindow", "PeripheralCollection"))
        self.Frame_4.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.label.setText(_translate("MainWindow", "Click to Calibrate"))
        self.Button480pF_4.setText(_translate("MainWindow", "Socket Cap"))
        self.Button480pF_3.setText(_translate("MainWindow", "330pF"))
        self.Button1uF_3.setText(_translate("MainWindow", "680pF"))
        self.Button100uF_3.setText(_translate("MainWindow", "2220pF"))
        self.ButtonCCS_3.setText(_translate("MainWindow", "PCS(1mA)"))
        self.ButtonCCS_4.setText(_translate("MainWindow", "Reset Calibration"))
        self.pushButton_9.setText(_translate("MainWindow", "RECOVER"))
        self.pushButton_8.setText(_translate("MainWindow", "UPLOAD"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
