# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digitalScope.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 557)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/pixmaps/cubeview48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.plot_area_frame = QtWidgets.QFrame(self.splitter)
        self.plot_area_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_area_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_area_frame.setObjectName("plot_area_frame")
        self.plot_area = QtWidgets.QVBoxLayout(self.plot_area_frame)
        self.plot_area.setContentsMargins(2, 2, 2, 2)
        self.plot_area.setSpacing(2)
        self.plot_area.setObjectName("plot_area")
        self.frame_12 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_7 = QtWidgets.QFrame(self.frame_12)
        self.frame_7.setGeometry(QtCore.QRect(10, 325, 281, 191))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(3)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timeoutBox = QtWidgets.QSpinBox(self.frame_7)
        self.timeoutBox.setMinimum(10)
        self.timeoutBox.setMaximum(10000)
        self.timeoutBox.setObjectName("timeoutBox")
        self.gridLayout_4.addWidget(self.timeoutBox, 4, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 2)
        self.edge2edge = QtWidgets.QComboBox(self.frame_7)
        self.edge2edge.setObjectName("edge2edge")
        self.edge2edge.addItem("")
        self.edge2edge.addItem("")
        self.edge2edge.addItem("")
        self.gridLayout_4.addWidget(self.edge2edge, 3, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_4.addWidget(self.label_56, 0, 0, 1, 4)
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.edge1edge = QtWidgets.QComboBox(self.frame_7)
        self.edge1edge.setObjectName("edge1edge")
        self.edge1edge.addItem("")
        self.edge1edge.addItem("")
        self.edge1edge.addItem("")
        self.gridLayout_4.addWidget(self.edge1edge, 2, 2, 1, 1)
        self.edge2chan = QtWidgets.QComboBox(self.frame_7)
        self.edge2chan.setObjectName("edge2chan")
        self.gridLayout_4.addWidget(self.edge2chan, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 3, 0, 1, 1)
        self.edge1chan = QtWidgets.QComboBox(self.frame_7)
        self.edge1chan.setObjectName("edge1chan")
        self.gridLayout_4.addWidget(self.edge1chan, 2, 1, 1, 1)
        self.edge1Count = QtWidgets.QComboBox(self.frame_7)
        self.edge1Count.setObjectName("edge1Count")
        self.edge1Count.addItem("")
        self.edge1Count.addItem("")
        self.edge1Count.addItem("")
        self.edge1Count.addItem("")
        self.gridLayout_4.addWidget(self.edge1Count, 2, 3, 1, 1)
        self.edge2Count = QtWidgets.QComboBox(self.frame_7)
        self.edge2Count.setObjectName("edge2Count")
        self.edge2Count.addItem("")
        self.edge2Count.addItem("")
        self.edge2Count.addItem("")
        self.edge2Count.addItem("")
        self.gridLayout_4.addWidget(self.edge2Count, 3, 3, 1, 1)
        self.timingResults = QtWidgets.QTableWidget(self.frame_7)
        self.timingResults.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.timingResults.setShowGrid(True)
        self.timingResults.setCornerButtonEnabled(True)
        self.timingResults.setRowCount(4)
        self.timingResults.setColumnCount(2)
        self.timingResults.setObjectName("timingResults")
        self.timingResults.horizontalHeader().setVisible(False)
        self.timingResults.horizontalHeader().setDefaultSectionSize(115)
        self.timingResults.horizontalHeader().setMinimumSectionSize(60)
        self.timingResults.horizontalHeader().setStretchLastSection(True)
        self.timingResults.verticalHeader().setDefaultSectionSize(22)
        self.timingResults.verticalHeader().setMinimumSectionSize(20)
        self.timingResults.verticalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.timingResults, 10, 0, 1, 4)
        self.pushButton = QtWidgets.QPushButton(self.frame_12)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 94, 31))
        self.pushButton.setMinimumSize(QtCore.QSize(94, 0))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.frame_12)
        self.progressBar.setGeometry(QtCore.QRect(10, 45, 281, 16))
        self.progressBar.setMaximum(2500)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 94, 31))
        self.pushButton_2.setMinimumSize(QtCore.QSize(94, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_3.setGeometry(QtCore.QRect(205, 10, 94, 31))
        self.pushButton_3.setMinimumSize(QtCore.QSize(94, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.channelSelection = QtWidgets.QToolBox(self.frame_12)
        self.channelSelection.setGeometry(QtCore.QRect(10, 65, 281, 246))
        self.channelSelection.setObjectName("channelSelection")
        self.C1 = QtWidgets.QWidget()
        self.C1.setGeometry(QtCore.QRect(0, 0, 281, 122))
        self.C1.setObjectName("C1")
        self.label_28 = QtWidgets.QLabel(self.C1)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_28.setObjectName("label_28")
        self.C1_chan = QtWidgets.QComboBox(self.C1)
        self.C1_chan.setGeometry(QtCore.QRect(135, 5, 141, 26))
        self.C1_chan.setObjectName("C1_chan")
        self.C1_chanmode = QtWidgets.QComboBox(self.C1)
        self.C1_chanmode.setGeometry(QtCore.QRect(135, 40, 141, 26))
        self.C1_chanmode.setObjectName("C1_chanmode")
        self.C1_chanmode.addItem("")
        self.C1_chanmode.addItem("")
        self.C1_chanmode.addItem("")
        self.C1_chanmode.addItem("")
        self.C1_chanmode.addItem("")
        self.label_29 = QtWidgets.QLabel(self.C1)
        self.label_29.setGeometry(QtCore.QRect(10, 45, 131, 20))
        self.label_29.setObjectName("label_29")
        self.label_31 = QtWidgets.QLabel(self.C1)
        self.label_31.setEnabled(True)
        self.label_31.setGeometry(QtCore.QRect(10, 85, 81, 18))
        self.label_31.setObjectName("label_31")
        self.C1_trig = QtWidgets.QComboBox(self.C1)
        self.C1_trig.setEnabled(True)
        self.C1_trig.setGeometry(QtCore.QRect(83, 80, 78, 26))
        self.C1_trig.setFrame(True)
        self.C1_trig.setObjectName("C1_trig")
        self.C1_trigmode = QtWidgets.QComboBox(self.C1)
        self.C1_trigmode.setEnabled(True)
        self.C1_trigmode.setGeometry(QtCore.QRect(163, 80, 113, 26))
        self.C1_trigmode.setFrame(True)
        self.C1_trigmode.setObjectName("C1_trigmode")
        self.C1_trigmode.addItem("")
        self.C1_trigmode.addItem("")
        self.C1_trigmode.addItem("")
        self.C1_trigmode.addItem("")
        self.channelSelection.addItem(self.C1, "")
        self.C2 = QtWidgets.QWidget()
        self.C2.setObjectName("C2")
        self.C2_ID1 = QtWidgets.QComboBox(self.C2)
        self.C2_ID1.setGeometry(QtCore.QRect(83, 4, 78, 26))
        self.C2_ID1.setObjectName("C2_ID1")
        self.label_33 = QtWidgets.QLabel(self.C2)
        self.label_33.setGeometry(QtCore.QRect(10, 10, 81, 18))
        self.label_33.setObjectName("label_33")
        self.C2_M1 = QtWidgets.QComboBox(self.C2)
        self.C2_M1.setGeometry(QtCore.QRect(165, 5, 113, 26))
        self.C2_M1.setObjectName("C2_M1")
        self.C2_M1.addItem("")
        self.C2_M1.addItem("")
        self.C2_M1.addItem("")
        self.C2_M1.addItem("")
        self.C2_M1.addItem("")
        self.label_34 = QtWidgets.QLabel(self.C2)
        self.label_34.setGeometry(QtCore.QRect(10, 45, 81, 18))
        self.label_34.setObjectName("label_34")
        self.C2_ID2 = QtWidgets.QComboBox(self.C2)
        self.C2_ID2.setGeometry(QtCore.QRect(83, 40, 78, 26))
        self.C2_ID2.setObjectName("C2_ID2")
        self.C2_M2 = QtWidgets.QComboBox(self.C2)
        self.C2_M2.setGeometry(QtCore.QRect(165, 40, 113, 26))
        self.C2_M2.setObjectName("C2_M2")
        self.C2_M2.addItem("")
        self.C2_M2.addItem("")
        self.C2_M2.addItem("")
        self.C2_M2.addItem("")
        self.C2_M2.addItem("")
        self.C2_trigmode = QtWidgets.QComboBox(self.C2)
        self.C2_trigmode.setGeometry(QtCore.QRect(172, 85, 106, 26))
        self.C2_trigmode.setObjectName("C2_trigmode")
        self.C2_trigmode.addItem("")
        self.C2_trigmode.addItem("")
        self.C2_trigmode.addItem("")
        self.label_35 = QtWidgets.QLabel(self.C2)
        self.label_35.setGeometry(QtCore.QRect(10, 90, 81, 18))
        self.label_35.setObjectName("label_35")
        self.C2_trig = QtWidgets.QComboBox(self.C2)
        self.C2_trig.setGeometry(QtCore.QRect(85, 85, 78, 26))
        self.C2_trig.setObjectName("C2_trig")
        self.channelSelection.addItem(self.C2, "")
        self.C3 = QtWidgets.QWidget()
        self.C3.setObjectName("C3")
        self.C3_M2 = QtWidgets.QComboBox(self.C3)
        self.C3_M2.setGeometry(QtCore.QRect(50, 35, 225, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C3_M2.setFont(font)
        self.C3_M2.setObjectName("C3_M2")
        self.C3_M2.addItem("")
        self.C3_M2.addItem("")
        self.C3_M2.addItem("")
        self.C3_M2.addItem("")
        self.label_10 = QtWidgets.QLabel(self.C3)
        self.label_10.setGeometry(QtCore.QRect(9, 35, 30, 17))
        self.label_10.setObjectName("label_10")
        self.C3_M3 = QtWidgets.QComboBox(self.C3)
        self.C3_M3.setGeometry(QtCore.QRect(50, 58, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C3_M3.setFont(font)
        self.C3_M3.setObjectName("C3_M3")
        self.C3_M3.addItem("")
        self.C3_M3.addItem("")
        self.C3_M3.addItem("")
        self.C3_M3.addItem("")
        self.label_5 = QtWidgets.QLabel(self.C3)
        self.label_5.setGeometry(QtCore.QRect(9, 11, 30, 18))
        self.label_5.setObjectName("label_5")
        self.C3_M1 = QtWidgets.QComboBox(self.C3)
        self.C3_M1.setGeometry(QtCore.QRect(50, 11, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C3_M1.setFont(font)
        self.C3_M1.setObjectName("C3_M1")
        self.C3_M1.addItem("")
        self.C3_M1.addItem("")
        self.C3_M1.addItem("")
        self.C3_M1.addItem("")
        self.label_13 = QtWidgets.QLabel(self.C3)
        self.label_13.setGeometry(QtCore.QRect(9, 58, 30, 18))
        self.label_13.setObjectName("label_13")
        self.label_32 = QtWidgets.QLabel(self.C3)
        self.label_32.setGeometry(QtCore.QRect(7, 95, 81, 18))
        self.label_32.setObjectName("label_32")
        self.C3_trig = QtWidgets.QComboBox(self.C3)
        self.C3_trig.setGeometry(QtCore.QRect(80, 90, 78, 26))
        self.C3_trig.setObjectName("C3_trig")
        self.C3_trigmode = QtWidgets.QComboBox(self.C3)
        self.C3_trigmode.setGeometry(QtCore.QRect(162, 90, 113, 26))
        self.C3_trigmode.setObjectName("C3_trigmode")
        self.C3_trigmode.addItem("")
        self.C3_trigmode.addItem("")
        self.C3_trigmode.addItem("")
        self.C3_trigmode.addItem("")
        self.channelSelection.addItem(self.C3, "")
        self.C4 = QtWidgets.QWidget()
        self.C4.setGeometry(QtCore.QRect(0, 0, 281, 122))
        self.C4.setObjectName("C4")
        self.C4_M4 = QtWidgets.QComboBox(self.C4)
        self.C4_M4.setGeometry(QtCore.QRect(50, 71, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C4_M4.setFont(font)
        self.C4_M4.setObjectName("C4_M4")
        self.C4_M4.addItem("")
        self.C4_M4.addItem("")
        self.C4_M4.addItem("")
        self.C4_M4.addItem("")
        self.label_11 = QtWidgets.QLabel(self.C4)
        self.label_11.setGeometry(QtCore.QRect(9, 47, 30, 18))
        self.label_11.setObjectName("label_11")
        self.C4_M1 = QtWidgets.QComboBox(self.C4)
        self.C4_M1.setGeometry(QtCore.QRect(50, 0, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C4_M1.setFont(font)
        self.C4_M1.setObjectName("C4_M1")
        self.C4_M1.addItem("")
        self.C4_M1.addItem("")
        self.C4_M1.addItem("")
        self.C4_M1.addItem("")
        self.label_12 = QtWidgets.QLabel(self.C4)
        self.label_12.setGeometry(QtCore.QRect(9, 71, 30, 18))
        self.label_12.setObjectName("label_12")
        self.C4_M3 = QtWidgets.QComboBox(self.C4)
        self.C4_M3.setGeometry(QtCore.QRect(50, 47, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C4_M3.setFont(font)
        self.C4_M3.setObjectName("C4_M3")
        self.C4_M3.addItem("")
        self.C4_M3.addItem("")
        self.C4_M3.addItem("")
        self.C4_M3.addItem("")
        self.C4_M2 = QtWidgets.QComboBox(self.C4)
        self.C4_M2.setGeometry(QtCore.QRect(50, 24, 225, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C4_M2.setFont(font)
        self.C4_M2.setObjectName("C4_M2")
        self.C4_M2.addItem("")
        self.C4_M2.addItem("")
        self.C4_M2.addItem("")
        self.C4_M2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.C4)
        self.label_4.setGeometry(QtCore.QRect(9, 0, 30, 18))
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.C4)
        self.label_9.setGeometry(QtCore.QRect(9, 24, 30, 17))
        self.label_9.setObjectName("label_9")
        self.FourChanTrig = QtWidgets.QCheckBox(self.C4)
        self.FourChanTrig.setGeometry(QtCore.QRect(10, 95, 256, 26))
        self.FourChanTrig.setChecked(True)
        self.FourChanTrig.setObjectName("FourChanTrig")
        self.channelSelection.addItem(self.C4, "")
        self.line = QtWidgets.QFrame(self.frame_12)
        self.line.setGeometry(QtCore.QRect(12, 310, 276, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.splitter)
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 17))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 34))
        self.frame_9.setBaseSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.message_label = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_label.sizePolicy().hasHeightForWidth())
        self.message_label.setSizePolicy(sizePolicy)
        self.message_label.setMinimumSize(QtCore.QSize(0, 30))
        self.message_label.setBaseSize(QtCore.QSize(0, 17))
        self.message_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.message_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.message_label.setWordWrap(True)
        self.message_label.setObjectName("message_label")
        self.horizontalLayout.addWidget(self.message_label)
        self.coord_label = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coord_label.sizePolicy().hasHeightForWidth())
        self.coord_label.setSizePolicy(sizePolicy)
        self.coord_label.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.coord_label.setFont(font)
        self.coord_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coord_label.setObjectName("coord_label")
        self.horizontalLayout.addWidget(self.coord_label)
        self.freezeButton = QtWidgets.QCheckBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freezeButton.sizePolicy().hasHeightForWidth())
        self.freezeButton.setSizePolicy(sizePolicy)
        self.freezeButton.setMaximumSize(QtCore.QSize(100, 10))
        self.freezeButton.setObjectName("freezeButton")
        self.horizontalLayout.addWidget(self.freezeButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frame_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")

        self.retranslateUi(MainWindow)
        self.edge2edge.setCurrentIndex(1)
        self.edge1Count.setCurrentIndex(0)
        self.channelSelection.setCurrentIndex(0)
        self.C1_chanmode.setCurrentIndex(1)
        self.C1_trigmode.setCurrentIndex(0)
        self.C2_M1.setCurrentIndex(1)
        self.C2_M2.setCurrentIndex(1)
        self.C2_trigmode.setCurrentIndex(0)
        self.C3_M2.setCurrentIndex(1)
        self.C3_M3.setCurrentIndex(1)
        self.C3_M1.setCurrentIndex(1)
        self.C3_trigmode.setCurrentIndex(0)
        self.C4_M4.setCurrentIndex(1)
        self.C4_M1.setCurrentIndex(1)
        self.C4_M3.setCurrentIndex(1)
        self.C4_M2.setCurrentIndex(1)
        self.pushButton_6.clicked.connect(MainWindow.measure_interval)
        self.pushButton.clicked.connect(MainWindow.capture)
        self.pushButton_3.clicked.connect(MainWindow.showData)
        self.pushButton_2.clicked.connect(MainWindow.plotData)
        self.pushButton_4.clicked.connect(MainWindow.saveData)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test and Measurement Suite"))
        self.frame_12.setProperty("class", _translate("MainWindow", "PeripheralCollection"))
        self.frame_7.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.timeoutBox.setSuffix(_translate("MainWindow", "mS"))
        self.pushButton_6.setText(_translate("MainWindow", "Measure >"))
        self.label.setText(_translate("MainWindow", "Timeout:"))
        self.edge2edge.setItemText(0, _translate("MainWindow", "rising"))
        self.edge2edge.setItemText(1, _translate("MainWindow", "falling"))
        self.edge2edge.setItemText(2, _translate("MainWindow", "four rising edges"))
        self.label_56.setText(_translate("MainWindow", "TIME INTERVAL MEASUREMENT"))
        self.label_16.setText(_translate("MainWindow", "1"))
        self.edge1edge.setItemText(0, _translate("MainWindow", "rising"))
        self.edge1edge.setItemText(1, _translate("MainWindow", "falling"))
        self.edge1edge.setItemText(2, _translate("MainWindow", "four rising edges"))
        self.label_17.setText(_translate("MainWindow", "2"))
        self.edge1Count.setItemText(0, _translate("MainWindow", "1"))
        self.edge1Count.setItemText(1, _translate("MainWindow", "2"))
        self.edge1Count.setItemText(2, _translate("MainWindow", "3"))
        self.edge1Count.setItemText(3, _translate("MainWindow", "4"))
        self.edge2Count.setItemText(0, _translate("MainWindow", "1"))
        self.edge2Count.setItemText(1, _translate("MainWindow", "2"))
        self.edge2Count.setItemText(2, _translate("MainWindow", "3"))
        self.edge2Count.setItemText(3, _translate("MainWindow", "4"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.progressBar.setFormat(_translate("MainWindow", "%v"))
        self.pushButton_2.setText(_translate("MainWindow", "Plot Data"))
        self.pushButton_3.setText(_translate("MainWindow", "Raw Data"))
        self.label_28.setText(_translate("MainWindow", "Input Channel"))
        self.C1_chanmode.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C1_chanmode.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C1_chanmode.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C1_chanmode.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.C1_chanmode.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.label_29.setText(_translate("MainWindow", "Edges to Record :"))
        self.label_31.setText(_translate("MainWindow", "trigger"))
        self.C1_trigmode.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C1_trigmode.setItemText(1, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C1_trigmode.setItemText(2, _translate("MainWindow", "RISING EDGES ONLY"))
        self.C1_trigmode.setItemText(3, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.channelSelection.setItemText(self.channelSelection.indexOf(self.C1), _translate("MainWindow", "Single Channel Mode"))
        self.label_33.setText(_translate("MainWindow", "Channel 1"))
        self.C2_M1.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C2_M1.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C2_M1.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C2_M1.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.C2_M1.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.label_34.setText(_translate("MainWindow", "Channel 2"))
        self.C2_M2.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C2_M2.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C2_M2.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C2_M2.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.C2_M2.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.C2_trigmode.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C2_trigmode.setItemText(1, _translate("MainWindow", "FALLING EDGE"))
        self.C2_trigmode.setItemText(2, _translate("MainWindow", "RISING EDGE"))
        self.label_35.setText(_translate("MainWindow", "trigger"))
        self.channelSelection.setItemText(self.channelSelection.indexOf(self.C2), _translate("MainWindow", "Two Channel Mode"))
        self.C3_M2.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C3_M2.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C3_M2.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C3_M2.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.label_10.setText(_translate("MainWindow", "ID2 :"))
        self.C3_M3.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C3_M3.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C3_M3.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C3_M3.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.label_5.setText(_translate("MainWindow", "ID1 :"))
        self.C3_M1.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C3_M1.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C3_M1.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C3_M1.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.label_13.setText(_translate("MainWindow", "ID3 :"))
        self.label_32.setText(_translate("MainWindow", "trigger"))
        self.C3_trigmode.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C3_trigmode.setItemText(1, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C3_trigmode.setItemText(2, _translate("MainWindow", "RISING EDGES ONLY"))
        self.C3_trigmode.setItemText(3, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.channelSelection.setItemText(self.channelSelection.indexOf(self.C3), _translate("MainWindow", "Three Channel Mode"))
        self.C4_M4.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C4_M4.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C4_M4.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C4_M4.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.label_11.setText(_translate("MainWindow", "ID3 :"))
        self.C4_M1.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C4_M1.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C4_M1.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C4_M1.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.label_12.setText(_translate("MainWindow", "ID4 :"))
        self.C4_M3.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C4_M3.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C4_M3.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C4_M3.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.C4_M2.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.C4_M2.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.C4_M2.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.C4_M2.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.label_4.setText(_translate("MainWindow", "ID1 :"))
        self.label_9.setText(_translate("MainWindow", "ID2 :"))
        self.FourChanTrig.setText(_translate("MainWindow", "Trigger on ID1"))
        self.channelSelection.setItemText(self.channelSelection.indexOf(self.C4), _translate("MainWindow", "Four Channel Mode"))
        self.message_label.setText(_translate("MainWindow", "Msg:"))
        self.coord_label.setText(_translate("MainWindow", "TextLabel"))
        self.freezeButton.setText(_translate("MainWindow", "FREEZE"))
        self.pushButton_4.setText(_translate("MainWindow", "Save Data"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
