# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 451)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.eTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.eTabs.setAutoFillBackground(True)
        self.eTabs.setObjectName("eTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.confTable = QtWidgets.QTableWidget(self.tab)
        self.confTable.setRowCount(100)
        self.confTable.setColumnCount(2)
        self.confTable.setObjectName("confTable")
        self.confTable.horizontalHeader().setDefaultSectionSize(150)
        self.confTable.horizontalHeader().setMinimumSectionSize(150)
        self.confTable.horizontalHeader().setStretchLastSection(True)
        self.confTable.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.confTable)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.eTabs.addTab(self.tab, "")
        self.selectTab = QtWidgets.QWidget()
        self.selectTab.setObjectName("selectTab")
        self.gridLayout = QtWidgets.QGridLayout(self.selectTab)
        self.gridLayout.setContentsMargins(0, 2, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_7 = QtWidgets.QFrame(self.selectTab)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_3.setContentsMargins(0, 2, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(3)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_2.setContentsMargins(2, -1, 2, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.sweepLayout = QtWidgets.QVBoxLayout(self.frame_12)
        self.sweepLayout.setContentsMargins(2, 2, 2, 2)
        self.sweepLayout.setSpacing(3)
        self.sweepLayout.setObjectName("sweepLayout")
        self.verticalLayout_2.addWidget(self.frame_12, 0, QtCore.Qt.AlignTop)
        self.gridLayout_3.addWidget(self.frame_10, 0, 1, 6, 1)
        self.frame_14 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton.sizePolicy().hasHeightForWidth())
        self.commandLinkButton.setSizePolicy(sizePolicy)
        self.commandLinkButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.commandLinkButton.setIconSize(QtCore.QSize(20, 15))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout_3.addWidget(self.commandLinkButton)
        self.gridLayout_3.addWidget(self.frame_14, 5, 2, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_3.setContentsMargins(2, -1, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.frame_3 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.sampleReadbacks = QtWidgets.QGridLayout(self.frame_3)
        self.sampleReadbacks.setContentsMargins(2, 2, 2, 2)
        self.sampleReadbacks.setSpacing(2)
        self.sampleReadbacks.setObjectName("sampleReadbacks")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.monitorLayout = QtWidgets.QVBoxLayout(self.frame_13)
        self.monitorLayout.setContentsMargins(2, 2, 2, 2)
        self.monitorLayout.setSpacing(2)
        self.monitorLayout.setObjectName("monitorLayout")
        self.verticalLayout_3.addWidget(self.frame_13, 0, QtCore.Qt.AlignTop)
        self.gridLayout_3.addWidget(self.frame_11, 0, 2, 5, 1)
        self.frame = QtWidgets.QFrame(self.frame_7)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(2, -1, 2, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setProperty("class", "")
        self.frame_2.setObjectName("frame_2")
        self.staticLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.staticLayout.setContentsMargins(0, 0, 0, 5)
        self.staticLayout.setObjectName("staticLayout")
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 6, 1)
        self.gridLayout.addWidget(self.frame_7, 0, 6, 1, 2)
        self.eTabs.addTab(self.selectTab, "")
        self.runTab = QtWidgets.QWidget()
        self.runTab.setObjectName("runTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.runTab)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.runTab)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_8)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.delayBox = QtWidgets.QSpinBox(self.frame_6)
        self.delayBox.setMinimum(0)
        self.delayBox.setMaximum(1000)
        self.delayBox.setObjectName("delayBox")
        self.horizontalLayout_2.addWidget(self.delayBox)
        self.gridLayout_4.addWidget(self.frame_6, 0, 1, 1, 1)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.frame_8)
        self.commandLinkButton_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.commandLinkButton_2.setFont(font)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.gridLayout_4.addWidget(self.commandLinkButton_2, 2, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.controlsLayout = QtWidgets.QGridLayout(self.frame_4)
        self.controlsLayout.setContentsMargins(2, 2, 2, 2)
        self.controlsLayout.setSpacing(3)
        self.controlsLayout.setObjectName("controlsLayout")
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.tbl = QtWidgets.QTableWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl.sizePolicy().hasHeightForWidth())
        self.tbl.setSizePolicy(sizePolicy)
        self.tbl.setObjectName("tbl")
        self.tbl.setColumnCount(0)
        self.tbl.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.tbl)
        self.gridLayout_4.addWidget(self.frame_5, 1, 0, 1, 3)
        self.frame_6.raise_()
        self.frame_5.raise_()
        self.commandLinkButton_2.raise_()
        self.gridLayout_2.addWidget(self.frame_8, 0, 1, 1, 1)
        self.eTabs.addTab(self.runTab, "")
        self.plotTab = QtWidgets.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.plotTab)
        self.gridLayout_5.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.plotTab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 1, 1, 1)
        self.plotList = QtWidgets.QComboBox(self.plotTab)
        self.plotList.setMinimumSize(QtCore.QSize(200, 0))
        self.plotList.setObjectName("plotList")
        self.gridLayout_5.addWidget(self.plotList, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.plotTab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.plotTab)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.plot_area = QtWidgets.QVBoxLayout(self.frame_9)
        self.plot_area.setContentsMargins(0, 0, 0, 0)
        self.plot_area.setSpacing(0)
        self.plot_area.setObjectName("plot_area")
        self.gridLayout_5.addWidget(self.frame_9, 1, 0, 1, 4)
        self.eTabs.addTab(self.plotTab, "")
        self.horizontalLayout.addWidget(self.eTabs)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.eTabs.setCurrentIndex(1)
        self.commandLinkButton.clicked.connect(MainWindow.prepare)
        self.pushButton_5.clicked.connect(MainWindow.runAll)
        self.commandLinkButton_2.clicked.connect(MainWindow.plotColumns)
        self.pushButton_2.clicked.connect(MainWindow.saveData)
        self.pushButton.clicked.connect(MainWindow.deleteCurve)
        self.pushButton_6.clicked.connect(MainWindow.saveProfile)
        self.pushButton_3.clicked.connect(MainWindow.loadProfile)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Load Profile From File"))
        self.eTabs.setTabText(self.eTabs.indexOf(self.tab), _translate("MainWindow", "Load Profile"))
        self.frame_7.setProperty("class", _translate("MainWindow", "PeripheralCollection"))
        self.frame_10.setToolTip(_translate("MainWindow", "select the parameters you need to vary in\n"
"order to generate a dataset"))
        self.frame_10.setProperty("class", _translate("MainWindow", "ControlWidget"))
        self.label.setText(_translate("MainWindow", "SWEEP CHANNELS"))
        self.pushButton_6.setText(_translate("MainWindow", "Save Profile"))
        self.pushButton_6.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.commandLinkButton.setText(_translate("MainWindow", "Prepare Experiment!"))
        self.commandLinkButton.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.frame_11.setToolTip(_translate("MainWindow", "Select the channels you need to monitor\n"
"in order to obtain the dataset"))
        self.frame_11.setProperty("class", _translate("MainWindow", "ControlWidget"))
        self.label_3.setText(_translate("MainWindow", "READBACK CHANNELS"))
        self.frame.setToolTip(_translate("MainWindow", "Select the parameters that need to have a certain fixed value per dataset"))
        self.frame.setProperty("class", _translate("MainWindow", "ControlWidget"))
        self.label_2.setText(_translate("MainWindow", "MANUAL CHANNELS"))
        self.eTabs.setTabText(self.eTabs.indexOf(self.selectTab), _translate("MainWindow", "Configure Experiment"))
        self.frame_8.setProperty("class", _translate("MainWindow", "PeripheralCollection"))
        self.frame_6.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.pushButton_5.setText(_translate("MainWindow", "Evaluate All Rows"))
        self.delayBox.setSuffix(_translate("MainWindow", " mS settling time"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "                Plot Selected Columns"))
        self.eTabs.setTabText(self.eTabs.indexOf(self.runTab), _translate("MainWindow", "Make Measurements"))
        self.pushButton.setText(_translate("MainWindow", "Delete"))
        self.pushButton_2.setText(_translate("MainWindow", "savePlots"))
        self.eTabs.setTabText(self.eTabs.indexOf(self.plotTab), _translate("MainWindow", "View plots"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
