# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scope.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 558)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/pixmaps/cubeview48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.plot_area_frame = QtWidgets.QFrame(self.splitter)
        self.plot_area_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_area_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_area_frame.setObjectName("plot_area_frame")
        self.plot_area = QtWidgets.QVBoxLayout(self.plot_area_frame)
        self.plot_area.setContentsMargins(0, 0, 0, 0)
        self.plot_area.setSpacing(2)
        self.plot_area.setObjectName("plot_area")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(291, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("border-color: rgb(115, 0, 255);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Analog = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Analog.sizePolicy().hasHeightForWidth())
        self.Analog.setSizePolicy(sizePolicy)
        self.Analog.setObjectName("Analog")
        self.frame = QtWidgets.QFrame(self.Analog)
        self.frame.setGeometry(QtCore.QRect(10, 140, 281, 71))
        self.frame.setStyleSheet("background-color: rgba(255, 0, 0, 20);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dial_11 = QtWidgets.QDial(self.frame)
        self.dial_11.setGeometry(QtCore.QRect(160, 0, 111, 71))
        self.dial_11.setMinimum(0)
        self.dial_11.setMaximum(1000)
        self.dial_11.setProperty("value", 500)
        self.dial_11.setNotchTarget(10.0)
        self.dial_11.setNotchesVisible(True)
        self.dial_11.setObjectName("dial_11")
        self.trigger_level_box = QtWidgets.QDoubleSpinBox(self.frame)
        self.trigger_level_box.setGeometry(QtCore.QRect(10, 50, 141, 21))
        self.trigger_level_box.setReadOnly(True)
        self.trigger_level_box.setMinimum(-20.0)
        self.trigger_level_box.setMaximum(20.0)
        self.trigger_level_box.setObjectName("trigger_level_box")
        self.trigger_select_box = QtWidgets.QComboBox(self.frame)
        self.trigger_select_box.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.trigger_select_box.setStyleSheet("")
        self.trigger_select_box.setFrame(False)
        self.trigger_select_box.setObjectName("trigger_select_box")
        self.trigger_select_box.addItem("")
        self.trigger_select_box.addItem("")
        self.trigger_select_box.addItem("")
        self.trigger_select_box.addItem("")
        self.label_48 = QtWidgets.QLabel(self.frame)
        self.label_48.setGeometry(QtCore.QRect(10, 0, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.frame_2 = QtWidgets.QFrame(self.Analog)
        self.frame_2.setGeometry(QtCore.QRect(10, 220, 281, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.timebase_dial = QtWidgets.QDial(self.frame_2)
        self.timebase_dial.setGeometry(QtCore.QRect(160, 0, 111, 71))
        self.timebase_dial.setMinimum(0)
        self.timebase_dial.setMaximum(10)
        self.timebase_dial.setPageStep(1)
        self.timebase_dial.setProperty("value", 1)
        self.timebase_dial.setObjectName("timebase_dial")
        self.timebase_label = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.timebase_label.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.timebase_label.setReadOnly(True)
        self.timebase_label.setDecimals(3)
        self.timebase_label.setMaximum(1000.0)
        self.timebase_label.setSingleStep(0.125)
        self.timebase_label.setProperty("value", 1.175)
        self.timebase_label.setObjectName("timebase_label")
        self.label_49 = QtWidgets.QLabel(self.frame_2)
        self.label_49.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.frame_3 = QtWidgets.QFrame(self.Analog)
        self.frame_3.setGeometry(QtCore.QRect(10, 370, 281, 71))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(180, 10, 98, 21))
        self.pushButton.setObjectName("pushButton")
        self.Liss_show = QtWidgets.QCheckBox(self.frame_3)
        self.Liss_show.setGeometry(QtCore.QRect(90, 10, 71, 22))
        self.Liss_show.setObjectName("Liss_show")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_2.setGeometry(QtCore.QRect(180, 40, 91, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.Liss_x = QtWidgets.QComboBox(self.frame_3)
        self.Liss_x.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.Liss_x.setObjectName("Liss_x")
        self.Liss_x.addItem("")
        self.Liss_x.addItem("")
        self.Liss_y = QtWidgets.QComboBox(self.frame_3)
        self.Liss_y.setGeometry(QtCore.QRect(90, 40, 71, 21))
        self.Liss_y.setObjectName("Liss_y")
        self.Liss_y.addItem("")
        self.Liss_y.addItem("")
        self.frame_6 = QtWidgets.QFrame(self.Analog)
        self.frame_6.setGeometry(QtCore.QRect(10, 300, 281, 61))
        self.frame_6.setStyleSheet("QCheckBox{background-color: rgba(255, 33, 0,0);}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.fit_select_box = QtWidgets.QComboBox(self.frame_6)
        self.fit_select_box.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.fit_select_box.setObjectName("fit_select_box")
        self.fit_select_box.addItem("")
        self.fit_select_box.addItem("")
        self.fit_select_box.addItem("")
        self.fit_select_box.addItem("")
        self.fit_select_box.addItem("")
        self.overlay_fit_button = QtWidgets.QCheckBox(self.frame_6)
        self.overlay_fit_button.setGeometry(QtCore.QRect(190, 0, 91, 21))
        self.overlay_fit_button.setObjectName("overlay_fit_button")
        self.fit_select_box_2 = QtWidgets.QComboBox(self.frame_6)
        self.fit_select_box_2.setGeometry(QtCore.QRect(90, 30, 71, 21))
        self.fit_select_box_2.setObjectName("fit_select_box_2")
        self.fit_select_box_2.addItem("")
        self.fit_select_box_2.addItem("")
        self.fit_select_box_2.addItem("")
        self.fit_select_box_2.addItem("")
        self.fit_select_box_2.addItem("")
        self.fit_type_box = QtWidgets.QComboBox(self.frame_6)
        self.fit_type_box.setGeometry(QtCore.QRect(10, 3, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.fit_type_box.setFont(font)
        self.fit_type_box.setFrame(False)
        self.fit_type_box.setObjectName("fit_type_box")
        self.fit_type_box.addItem("")
        self.collapseButton = QtWidgets.QCheckBox(self.frame_6)
        self.collapseButton.setGeometry(QtCore.QRect(250, 40, 21, 21))
        self.collapseButton.setObjectName("collapseButton")
        self.frame_11 = QtWidgets.QFrame(self.Analog)
        self.frame_11.setGeometry(QtCore.QRect(10, 10, 281, 121))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.CH1_REMAPS = QtWidgets.QComboBox(self.frame_11)
        self.CH1_REMAPS.setGeometry(QtCore.QRect(220, 10, 61, 21))
        self.CH1_REMAPS.setObjectName("CH1_REMAPS")
        self.CH1_LABEL = QtWidgets.QLabel(self.frame_11)
        self.CH1_LABEL.setGeometry(QtCore.QRect(20, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.CH1_LABEL.setFont(font)
        self.CH1_LABEL.setObjectName("CH1_LABEL")
        self.CH2_LABEL = QtWidgets.QLabel(self.frame_11)
        self.CH2_LABEL.setGeometry(QtCore.QRect(20, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.CH2_LABEL.setFont(font)
        self.CH2_LABEL.setObjectName("CH2_LABEL")
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_6.setGeometry(QtCore.QRect(130, 10, 78, 21))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_7.setGeometry(QtCore.QRect(130, 50, 78, 20))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_30 = QtWidgets.QLabel(self.frame_11)
        self.label_30.setGeometry(QtCore.QRect(90, 10, 31, 17))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_11)
        self.label_31.setGeometry(QtCore.QRect(90, 50, 31, 17))
        self.label_31.setObjectName("label_31")
        self.CH1_ENABLE = QtWidgets.QCheckBox(self.frame_11)
        self.CH1_ENABLE.setGeometry(QtCore.QRect(0, 10, 21, 20))
        self.CH1_ENABLE.setText("")
        self.CH1_ENABLE.setChecked(True)
        self.CH1_ENABLE.setObjectName("CH1_ENABLE")
        self.CH2_ENABLE = QtWidgets.QCheckBox(self.frame_11)
        self.CH2_ENABLE.setGeometry(QtCore.QRect(0, 50, 21, 20))
        self.CH2_ENABLE.setText("")
        self.CH2_ENABLE.setObjectName("CH2_ENABLE")
        self.offsetLabel = QtWidgets.QLabel(self.frame_11)
        self.offsetLabel.setGeometry(QtCore.QRect(240, 30, 41, 31))
        self.offsetLabel.setObjectName("offsetLabel")
        self.FOURCHAN_ENABLE = QtWidgets.QCheckBox(self.frame_11)
        self.FOURCHAN_ENABLE.setGeometry(QtCore.QRect(0, 90, 21, 20))
        self.FOURCHAN_ENABLE.setText("")
        self.FOURCHAN_ENABLE.setChecked(False)
        self.FOURCHAN_ENABLE.setObjectName("FOURCHAN_ENABLE")
        self.CH2_LABEL_2 = QtWidgets.QLabel(self.frame_11)
        self.CH2_LABEL_2.setGeometry(QtCore.QRect(20, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.CH2_LABEL_2.setFont(font)
        self.CH2_LABEL_2.setObjectName("CH2_LABEL_2")
        self.tabWidget.addTab(self.Analog, "")
        self.Digital = QtWidgets.QWidget()
        self.Digital.setObjectName("Digital")
        self.active_channel_box = QtWidgets.QComboBox(self.Digital)
        self.active_channel_box.setGeometry(QtCore.QRect(150, 6, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.active_channel_box.sizePolicy().hasHeightForWidth())
        self.active_channel_box.setSizePolicy(sizePolicy)
        self.active_channel_box.setObjectName("active_channel_box")
        self.active_channel_box.addItem("")
        self.active_channel_box.addItem("")
        self.active_channel_box.addItem("")
        self.active_channel_box.addItem("")
        self.label_13 = QtWidgets.QLabel(self.Digital)
        self.label_13.setGeometry(QtCore.QRect(30, 10, 106, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.frame_4 = QtWidgets.QFrame(self.Digital)
        self.frame_4.setGeometry(QtCore.QRect(10, 30, 281, 61))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.dial_16 = QtWidgets.QDial(self.frame_4)
        self.dial_16.setGeometry(QtCore.QRect(180, 0, 111, 61))
        self.dial_16.setMinimum(0)
        self.dial_16.setMaximum(9)
        self.dial_16.setPageStep(1)
        self.dial_16.setProperty("value", 0)
        self.dial_16.setObjectName("dial_16")
        self.digital_timescale = QtWidgets.QSpinBox(self.frame_4)
        self.digital_timescale.setGeometry(QtCore.QRect(10, 30, 141, 27))
        self.digital_timescale.setReadOnly(True)
        self.digital_timescale.setMaximum(10000)
        self.digital_timescale.setProperty("value", 1)
        self.digital_timescale.setObjectName("digital_timescale")
        self.label_53 = QtWidgets.QLabel(self.frame_4)
        self.label_53.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.frame_5 = QtWidgets.QFrame(self.Digital)
        self.frame_5.setGeometry(QtCore.QRect(10, 200, 281, 141))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayout = QtWidgets.QFormLayout(self.frame_5)
        self.formLayout.setObjectName("formLayout")
        self.label_54 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_54)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.frame_7 = QtWidgets.QFrame(self.Digital)
        self.frame_7.setGeometry(QtCore.QRect(10, 350, 281, 121))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.edge2chan = QtWidgets.QComboBox(self.frame_7)
        self.edge2chan.setObjectName("edge2chan")
        self.edge2chan.addItem("")
        self.edge2chan.addItem("")
        self.edge2chan.addItem("")
        self.edge2chan.addItem("")
        self.edge2chan.addItem("")
        self.edge2chan.addItem("")
        self.edge2chan.addItem("")
        self.gridLayout_4.addWidget(self.edge2chan, 2, 1, 1, 1)
        self.edge1edge = QtWidgets.QComboBox(self.frame_7)
        self.edge1edge.setObjectName("edge1edge")
        self.edge1edge.addItem("")
        self.edge1edge.addItem("")
        self.edge1edge.addItem("")
        self.gridLayout_4.addWidget(self.edge1edge, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.edge2edge = QtWidgets.QComboBox(self.frame_7)
        self.edge2edge.setObjectName("edge2edge")
        self.edge2edge.addItem("")
        self.edge2edge.addItem("")
        self.edge2edge.addItem("")
        self.gridLayout_4.addWidget(self.edge2edge, 2, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.edge1chan = QtWidgets.QComboBox(self.frame_7)
        self.edge1chan.setObjectName("edge1chan")
        self.edge1chan.addItem("")
        self.edge1chan.addItem("")
        self.edge1chan.addItem("")
        self.edge1chan.addItem("")
        self.edge1chan.addItem("")
        self.edge1chan.addItem("")
        self.edge1chan.addItem("")
        self.gridLayout_4.addWidget(self.edge1chan, 1, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_4.addWidget(self.label_56, 0, 0, 1, 3)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 3, 0, 1, 3)
        self.time_interval_label = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.time_interval_label.setFont(font)
        self.time_interval_label.setObjectName("time_interval_label")
        self.gridLayout_4.addWidget(self.time_interval_label, 6, 0, 1, 3)
        self.frame_8 = QtWidgets.QFrame(self.Digital)
        self.frame_8.setGeometry(QtCore.QRect(10, 100, 281, 51))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_58 = QtWidgets.QLabel(self.frame_8)
        self.label_58.setGeometry(QtCore.QRect(10, 0, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.LA1_chanmode = QtWidgets.QComboBox(self.frame_8)
        self.LA1_chanmode.setGeometry(QtCore.QRect(150, 20, 121, 21))
        self.LA1_chanmode.setObjectName("LA1_chanmode")
        self.LA1_chanmode.addItem("")
        self.LA1_chanmode.addItem("")
        self.LA1_chanmode.addItem("")
        self.LA1_chanmode.addItem("")
        self.LA1_chanmode.addItem("")
        self.label_28 = QtWidgets.QLabel(self.frame_8)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label_28.setObjectName("label_28")
        self.LA1_chan = QtWidgets.QComboBox(self.frame_8)
        self.LA1_chan.setGeometry(QtCore.QRect(70, 20, 71, 21))
        self.LA1_chan.setObjectName("LA1_chan")
        self.LA1_chan.addItem("")
        self.LA1_chan.addItem("")
        self.LA1_chan.addItem("")
        self.LA1_chan.addItem("")
        self.LA1_chan.addItem("")
        self.LA1_chan.addItem("")
        self.LA1_chan.addItem("")
        self.frame_10 = QtWidgets.QFrame(self.Digital)
        self.frame_10.setGeometry(QtCore.QRect(10, 160, 281, 31))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_29 = QtWidgets.QLabel(self.frame_10)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_2.addWidget(self.label_29)
        self.LA1_trig = QtWidgets.QComboBox(self.frame_10)
        self.LA1_trig.setObjectName("LA1_trig")
        self.LA1_trig.addItem("")
        self.LA1_trig.addItem("")
        self.LA1_trig.addItem("")
        self.LA1_trig.addItem("")
        self.LA1_trig.addItem("")
        self.LA1_trig.addItem("")
        self.LA1_trig.addItem("")
        self.horizontalLayout_2.addWidget(self.LA1_trig)
        self.LA1_trigmode = QtWidgets.QComboBox(self.frame_10)
        self.LA1_trigmode.setObjectName("LA1_trigmode")
        self.LA1_trigmode.addItem("")
        self.LA1_trigmode.addItem("")
        self.LA1_trigmode.addItem("")
        self.LA1_trigmode.addItem("")
        self.horizontalLayout_2.addWidget(self.LA1_trigmode)
        self.tabWidget.addTab(self.Digital, "")
        self.Peripheral = QtWidgets.QWidget()
        self.Peripheral.setObjectName("Peripheral")
        self.layoutWidget = QtWidgets.QWidget(self.Peripheral)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 297, 260))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.PV2_LABEL = QtWidgets.QLabel(self.layoutWidget)
        self.PV2_LABEL.setObjectName("PV2_LABEL")
        self.gridLayout.addWidget(self.PV2_LABEL, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.PV3_LABEL = QtWidgets.QLabel(self.layoutWidget)
        self.PV3_LABEL.setObjectName("PV3_LABEL")
        self.gridLayout.addWidget(self.PV3_LABEL, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.PCS_LABEL = QtWidgets.QLabel(self.layoutWidget)
        self.PCS_LABEL.setObjectName("PCS_LABEL")
        self.gridLayout.addWidget(self.PCS_LABEL, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 0, 1, 1)
        self.WAVE1_FREQ = QtWidgets.QLabel(self.layoutWidget)
        self.WAVE1_FREQ.setObjectName("WAVE1_FREQ")
        self.gridLayout.addWidget(self.WAVE1_FREQ, 4, 1, 1, 1)
        self.sinebox2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinebox2.sizePolicy().hasHeightForWidth())
        self.sinebox2.setSizePolicy(sizePolicy)
        self.sinebox2.setMaximum(1000000.0)
        self.sinebox2.setObjectName("sinebox2")
        self.gridLayout.addWidget(self.sinebox2, 4, 2, 1, 1)
        self.PV1_LABEL = QtWidgets.QLabel(self.layoutWidget)
        self.PV1_LABEL.setObjectName("PV1_LABEL")
        self.gridLayout.addWidget(self.PV1_LABEL, 0, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider.setMaximum(4095)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 0, 2, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_2.setMaximum(4095)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout.addWidget(self.horizontalSlider_2, 1, 2, 1, 1)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_3.setMaximum(4095)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout.addWidget(self.horizontalSlider_3, 2, 2, 1, 1)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_4.setMaximum(4095)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.gridLayout.addWidget(self.horizontalSlider_4, 3, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 5, 0, 1, 1)
        self.WAVE2_FREQ = QtWidgets.QLabel(self.layoutWidget)
        self.WAVE2_FREQ.setObjectName("WAVE2_FREQ")
        self.gridLayout.addWidget(self.WAVE2_FREQ, 5, 1, 1, 1)
        self.sinebox1 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinebox1.sizePolicy().hasHeightForWidth())
        self.sinebox1.setSizePolicy(sizePolicy)
        self.sinebox1.setMaximum(1000000.0)
        self.sinebox1.setObjectName("sinebox1")
        self.gridLayout.addWidget(self.sinebox1, 5, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 6, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 6, 2, 1, 1)
        self.sinePhase_freq = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinePhase_freq.sizePolicy().hasHeightForWidth())
        self.sinePhase_freq.setSizePolicy(sizePolicy)
        self.sinePhase_freq.setMinimum(5.0)
        self.sinePhase_freq.setMaximum(5000.0)
        self.sinePhase_freq.setObjectName("sinePhase_freq")
        self.gridLayout.addWidget(self.sinePhase_freq, 7, 0, 1, 1)
        self.sinePhase_phase = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinePhase_phase.sizePolicy().hasHeightForWidth())
        self.sinePhase_phase.setSizePolicy(sizePolicy)
        self.sinePhase_phase.setDecimals(1)
        self.sinePhase_phase.setMaximum(359.0)
        self.sinePhase_phase.setObjectName("sinePhase_phase")
        self.gridLayout.addWidget(self.sinePhase_phase, 7, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 7, 2, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.Peripheral)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 250, 271, 159))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 1, 0, 1, 1)
        self.SQR_NM = QtWidgets.QComboBox(self.layoutWidget_2)
        self.SQR_NM.setObjectName("SQR_NM")
        self.SQR_NM.addItem("")
        self.SQR_NM.addItem("")
        self.SQR_NM.addItem("")
        self.SQR_NM.addItem("")
        self.gridLayout_5.addWidget(self.SQR_NM, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 3)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 4, 0, 1, 3)
        self.SQR_FREQ = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.SQR_FREQ.setMinimum(1)
        self.SQR_FREQ.setMaximum(1000000)
        self.SQR_FREQ.setProperty("value", 500)
        self.SQR_FREQ.setObjectName("SQR_FREQ")
        self.gridLayout_5.addWidget(self.SQR_FREQ, 1, 1, 1, 2)
        self.SQR_PH = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.SQR_PH.setMaximum(360)
        self.SQR_PH.setObjectName("SQR_PH")
        self.gridLayout_5.addWidget(self.SQR_PH, 3, 1, 1, 1)
        self.SQR_DC = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.SQR_DC.setMaximum(100)
        self.SQR_DC.setProperty("value", 50)
        self.SQR_DC.setObjectName("SQR_DC")
        self.gridLayout_5.addWidget(self.SQR_DC, 3, 2, 1, 1)
        self.tabWidget.addTab(self.Peripheral, "")
        self.verticalLayout.addWidget(self.splitter)
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 17))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 34))
        self.frame_9.setBaseSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.message_label = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_label.sizePolicy().hasHeightForWidth())
        self.message_label.setSizePolicy(sizePolicy)
        self.message_label.setBaseSize(QtCore.QSize(0, 17))
        self.message_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.message_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.message_label.setWordWrap(True)
        self.message_label.setObjectName("message_label")
        self.horizontalLayout.addWidget(self.message_label)
        self.coord_label = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coord_label.sizePolicy().hasHeightForWidth())
        self.coord_label.setSizePolicy(sizePolicy)
        self.coord_label.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.coord_label.setFont(font)
        self.coord_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coord_label.setObjectName("coord_label")
        self.horizontalLayout.addWidget(self.coord_label)
        self.freezeButton = QtWidgets.QCheckBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freezeButton.sizePolicy().hasHeightForWidth())
        self.freezeButton.setSizePolicy(sizePolicy)
        self.freezeButton.setMaximumSize(QtCore.QSize(100, 10))
        self.freezeButton.setObjectName("freezeButton")
        self.horizontalLayout.addWidget(self.freezeButton)
        self.verticalLayout.addWidget(self.frame_9)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Liss_y.setCurrentIndex(1)
        self.fit_select_box.setCurrentIndex(4)
        self.fit_select_box_2.setCurrentIndex(4)
        self.fit_type_box.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(1)
        self.comboBox_2.setCurrentIndex(1)
        self.comboBox_3.setCurrentIndex(1)
        self.comboBox_4.setCurrentIndex(1)
        self.edge2edge.setCurrentIndex(0)
        self.LA1_chanmode.setCurrentIndex(1)
        self.LA1_trigmode.setCurrentIndex(0)
        self.active_channel_box.currentIndexChanged['QString'].connect(MainWindow.setActiveDigitalChannels)
        self.comboBox_3.currentIndexChanged['int'].connect(MainWindow.set_dchan_mode_ch3)
        self.comboBox_2.currentIndexChanged['int'].connect(MainWindow.set_dchan_mode_ch2)
        self.dial_16.valueChanged['int'].connect(MainWindow.set_digital_scope_time)
        self.comboBox.currentIndexChanged['int'].connect(MainWindow.set_dchan_mode_ch1)
        self.comboBox_4.currentIndexChanged['int'].connect(MainWindow.set_dchan_mode_ch4)
        self.pushButton_6.clicked.connect(MainWindow.measure_interval)
        self.pushButton_7.clicked.connect(MainWindow.sqr_update)
        self.SQR_PH.valueChanged['int'].connect(MainWindow.sqr_phase)
        self.SQR_DC.valueChanged['int'].connect(MainWindow.sqr_dc)
        self.sinebox2.valueChanged['double'].connect(MainWindow.setSINE1)
        self.horizontalSlider.valueChanged['int'].connect(MainWindow.setPV1)
        self.horizontalSlider_2.valueChanged['int'].connect(MainWindow.setPV2)
        self.horizontalSlider_3.valueChanged['int'].connect(MainWindow.setPV3)
        self.horizontalSlider_4.valueChanged['int'].connect(MainWindow.setPCS)
        self.sinebox1.valueChanged['double'].connect(MainWindow.setSINE2)
        self.pushButton_2.clicked.connect(MainWindow.setSinePhase)
        self.pushButton.clicked.connect(MainWindow.plot_liss)
        self.tabWidget.currentChanged['int'].connect(MainWindow.change_scope_type)
        self.checkBox_2.toggled['bool'].connect(MainWindow.liss_animate)
        self.trigger_select_box.currentIndexChanged['int'].connect(MainWindow.setTriggerChannel)
        self.dial_11.valueChanged['int'].connect(MainWindow.setTriggerLevel)
        self.timebase_dial.valueChanged['int'].connect(MainWindow.setTimeBase)
        self.comboBox_6.currentIndexChanged['int'].connect(MainWindow.setGainCH1)
        self.comboBox_7.currentIndexChanged['int'].connect(MainWindow.setGainCH2)
        self.CH1_REMAPS.currentIndexChanged['QString'].connect(MainWindow.remap_CH0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test and Measurement Suite"))
        self.trigger_level_box.setSuffix(_translate("MainWindow", " V"))
        self.trigger_select_box.setItemText(0, _translate("MainWindow", "CH1"))
        self.trigger_select_box.setItemText(1, _translate("MainWindow", "CH2"))
        self.trigger_select_box.setItemText(2, _translate("MainWindow", "CH3"))
        self.trigger_select_box.setItemText(3, _translate("MainWindow", "MIC"))
        self.label_48.setText(_translate("MainWindow", "TRIGGER"))
        self.timebase_label.setSuffix(_translate("MainWindow", "uS"))
        self.label_49.setText(_translate("MainWindow", "TIME GAP"))
        self.label.setText(_translate("MainWindow", "Lissajous "))
        self.pushButton.setText(_translate("MainWindow", "PLOT"))
        self.Liss_show.setText(_translate("MainWindow", "Show"))
        self.checkBox_2.setText(_translate("MainWindow", "animate"))
        self.Liss_x.setItemText(0, _translate("MainWindow", "CH1"))
        self.Liss_x.setItemText(1, _translate("MainWindow", "CH2"))
        self.Liss_y.setItemText(0, _translate("MainWindow", "CH1"))
        self.Liss_y.setItemText(1, _translate("MainWindow", "CH2"))
        self.fit_select_box.setItemText(0, _translate("MainWindow", "CH1"))
        self.fit_select_box.setItemText(1, _translate("MainWindow", "CH2"))
        self.fit_select_box.setItemText(2, _translate("MainWindow", "CH3"))
        self.fit_select_box.setItemText(3, _translate("MainWindow", "MIC"))
        self.fit_select_box.setItemText(4, _translate("MainWindow", "None"))
        self.overlay_fit_button.setText(_translate("MainWindow", "Overlay"))
        self.fit_select_box_2.setItemText(0, _translate("MainWindow", "CH1"))
        self.fit_select_box_2.setItemText(1, _translate("MainWindow", "CH2"))
        self.fit_select_box_2.setItemText(2, _translate("MainWindow", "CH3"))
        self.fit_select_box_2.setItemText(3, _translate("MainWindow", "MIC"))
        self.fit_select_box_2.setItemText(4, _translate("MainWindow", "None"))
        self.fit_type_box.setItemText(0, _translate("MainWindow", "SINE FIT"))
        self.collapseButton.setText(_translate("MainWindow", "."))
        self.CH1_LABEL.setText(_translate("MainWindow", "CH1"))
        self.CH2_LABEL.setText(_translate("MainWindow", "CH2"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "1x"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "2x"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "4x"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "5x"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "8x"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "10x"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "16x"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "32x"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "1x"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "2x"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "4x"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "5x"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "8x"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "10x"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "16x"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "32x"))
        self.label_30.setText(_translate("MainWindow", "gain"))
        self.label_31.setText(_translate("MainWindow", "gain"))
        self.offsetLabel.setText(_translate("MainWindow", "."))
        self.CH2_LABEL_2.setText(_translate("MainWindow", "CH3 , MIC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analog), _translate("MainWindow", "Analog signals"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Analog), _translate("MainWindow", "Four channel, 1MSPS Oscilloscope"))
        self.active_channel_box.setItemText(0, _translate("MainWindow", "1"))
        self.active_channel_box.setItemText(1, _translate("MainWindow", "2"))
        self.active_channel_box.setItemText(2, _translate("MainWindow", "3"))
        self.active_channel_box.setItemText(3, _translate("MainWindow", "4"))
        self.label_13.setText(_translate("MainWindow", "Active Channels"))
        self.digital_timescale.setSuffix(_translate("MainWindow", "mS"))
        self.label_53.setText(_translate("MainWindow", "ACQUISITION TIME"))
        self.label_54.setText(_translate("MainWindow", "3/4 CHANNEL MODES"))
        self.label_4.setText(_translate("MainWindow", "CH1 :"))
        self.comboBox.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.comboBox.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.comboBox.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.comboBox.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.comboBox.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.label_9.setText(_translate("MainWindow", "CH2 :"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.label_11.setText(_translate("MainWindow", "CH3 :"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.label_12.setText(_translate("MainWindow", "CH4 :"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.edge2chan.setItemText(0, _translate("MainWindow", "ID1"))
        self.edge2chan.setItemText(1, _translate("MainWindow", "ID2"))
        self.edge2chan.setItemText(2, _translate("MainWindow", "ID3"))
        self.edge2chan.setItemText(3, _translate("MainWindow", "ID4"))
        self.edge2chan.setItemText(4, _translate("MainWindow", "-"))
        self.edge2chan.setItemText(5, _translate("MainWindow", "CH1"))
        self.edge2chan.setItemText(6, _translate("MainWindow", "Fin"))
        self.edge1edge.setItemText(0, _translate("MainWindow", "rising"))
        self.edge1edge.setItemText(1, _translate("MainWindow", "falling"))
        self.edge1edge.setItemText(2, _translate("MainWindow", "four rising edges"))
        self.label_16.setText(_translate("MainWindow", "EDGE 1"))
        self.edge2edge.setItemText(0, _translate("MainWindow", "rising"))
        self.edge2edge.setItemText(1, _translate("MainWindow", "falling"))
        self.edge2edge.setItemText(2, _translate("MainWindow", "four rising edges"))
        self.label_17.setText(_translate("MainWindow", "EDGE 2"))
        self.edge1chan.setItemText(0, _translate("MainWindow", "ID1"))
        self.edge1chan.setItemText(1, _translate("MainWindow", "ID2"))
        self.edge1chan.setItemText(2, _translate("MainWindow", "ID3"))
        self.edge1chan.setItemText(3, _translate("MainWindow", "ID4"))
        self.edge1chan.setItemText(4, _translate("MainWindow", "-"))
        self.edge1chan.setItemText(5, _translate("MainWindow", "CH1"))
        self.edge1chan.setItemText(6, _translate("MainWindow", "Fin"))
        self.label_56.setText(_translate("MainWindow", "MEASURE TIME INTERVALS"))
        self.pushButton_6.setText(_translate("MainWindow", "Go"))
        self.time_interval_label.setText(_translate("MainWindow", "result:"))
        self.label_58.setText(_translate("MainWindow", "SINGLE CHANNEL OPTIONS"))
        self.LA1_chanmode.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.LA1_chanmode.setItemText(1, _translate("MainWindow", "EVERY EDGE"))
        self.LA1_chanmode.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.LA1_chanmode.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY"))
        self.LA1_chanmode.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.label_28.setText(_translate("MainWindow", "Channel"))
        self.LA1_chan.setItemText(0, _translate("MainWindow", "ID1"))
        self.LA1_chan.setItemText(1, _translate("MainWindow", "ID2"))
        self.LA1_chan.setItemText(2, _translate("MainWindow", "ID3"))
        self.LA1_chan.setItemText(3, _translate("MainWindow", "ID4"))
        self.LA1_chan.setItemText(4, _translate("MainWindow", "-"))
        self.LA1_chan.setItemText(5, _translate("MainWindow", "CH1"))
        self.LA1_chan.setItemText(6, _translate("MainWindow", "Fin"))
        self.label_29.setText(_translate("MainWindow", "trigger"))
        self.LA1_trig.setItemText(0, _translate("MainWindow", "ID1"))
        self.LA1_trig.setItemText(1, _translate("MainWindow", "ID2"))
        self.LA1_trig.setItemText(2, _translate("MainWindow", "ID3"))
        self.LA1_trig.setItemText(3, _translate("MainWindow", "ID4"))
        self.LA1_trig.setItemText(4, _translate("MainWindow", "-"))
        self.LA1_trig.setItemText(5, _translate("MainWindow", "CH1"))
        self.LA1_trig.setItemText(6, _translate("MainWindow", "Fin"))
        self.LA1_trigmode.setItemText(0, _translate("MainWindow", "DISABLED"))
        self.LA1_trigmode.setItemText(1, _translate("MainWindow", "FALLING EDGES ONLY"))
        self.LA1_trigmode.setItemText(2, _translate("MainWindow", "RISING EDGES ONLY"))
        self.LA1_trigmode.setItemText(3, _translate("MainWindow", "EVERY FOUR RISING EDGES"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Digital), _translate("MainWindow", "Digital signals"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Digital), _translate("MainWindow", "Four channel Logic Analyzer"))
        self.label_6.setText(_translate("MainWindow", "PV1 "))
        self.label_7.setText(_translate("MainWindow", "PV2 "))
        self.PV2_LABEL.setText(_translate("MainWindow", "-3.3 to 3.3V"))
        self.label_5.setText(_translate("MainWindow", "PV3"))
        self.PV3_LABEL.setText(_translate("MainWindow", "0 - 3.3V"))
        self.label_8.setText(_translate("MainWindow", "PCS"))
        self.PCS_LABEL.setText(_translate("MainWindow", "0-3.3mA"))
        self.label_15.setText(_translate("MainWindow", "Wave 1"))
        self.WAVE1_FREQ.setText(_translate("MainWindow", "10Hz to 5KHz"))
        self.PV1_LABEL.setText(_translate("MainWindow", "-5 to 5V"))
        self.label_22.setText(_translate("MainWindow", "Wave 2"))
        self.WAVE2_FREQ.setText(_translate("MainWindow", "10Hz to 5KHz"))
        self.label_24.setText(_translate("MainWindow", "Frequency"))
        self.label_25.setText(_translate("MainWindow", "phase"))
        self.label_26.setText(_translate("MainWindow", "Correlate"))
        self.pushButton_2.setText(_translate("MainWindow", "SET PHASE"))
        self.label_3.setText(_translate("MainWindow", "Frequency"))
        self.SQR_NM.setItemText(0, _translate("MainWindow", "SQ1"))
        self.SQR_NM.setItemText(1, _translate("MainWindow", "SQ2"))
        self.SQR_NM.setItemText(2, _translate("MainWindow", "OD1"))
        self.SQR_NM.setItemText(3, _translate("MainWindow", "OD2"))
        self.label_21.setText(_translate("MainWindow", "Duty Cycle"))
        self.label_20.setText(_translate("MainWindow", "Phase"))
        self.label_2.setText(_translate("MainWindow", "Phase Correlated Square Waves"))
        self.label_18.setText(_translate("MainWindow", "Output"))
        self.pushButton_7.setText(_translate("MainWindow", "UPDATE"))
        self.SQR_DC.setSuffix(_translate("MainWindow", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Peripheral), _translate("MainWindow", "Peripherals"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Peripheral), _translate("MainWindow", "Set values for function generators, voltage sources etc."))
        self.message_label.setText(_translate("MainWindow", "Msg:"))
        self.coord_label.setText(_translate("MainWindow", "TextLabel"))
        self.freezeButton.setText(_translate("MainWindow", "FREEZE"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
