# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single_col_exp.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 667)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.subSections = QtWidgets.QComboBox(self.frame)
        self.subSections.setDuplicatesEnabled(True)
        self.subSections.setFrame(False)
        self.subSections.setObjectName("subSections")
        self.verticalLayout_4.addWidget(self.subSections)
        self.ExperimentScrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExperimentScrollArea.sizePolicy().hasHeightForWidth())
        self.ExperimentScrollArea.setSizePolicy(sizePolicy)
        self.ExperimentScrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ExperimentScrollArea.setStyleSheet("")
        self.ExperimentScrollArea.setWidgetResizable(True)
        self.ExperimentScrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ExperimentScrollArea.setObjectName("ExperimentScrollArea")
        self.SCF1 = QtWidgets.QWidget()
        self.SCF1.setGeometry(QtCore.QRect(0, 0, 400, 417))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SCF1.sizePolicy().hasHeightForWidth())
        self.SCF1.setSizePolicy(sizePolicy)
        self.SCF1.setStyleSheet("")
        self.SCF1.setObjectName("SCF1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.SCF1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.SCF1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ExperimentLayout = QtWidgets.QGridLayout()
        self.ExperimentLayout.setContentsMargins(5, 5, 5, 5)
        self.ExperimentLayout.setSpacing(7)
        self.ExperimentLayout.setObjectName("ExperimentLayout")
        self.gridLayout_7.addLayout(self.ExperimentLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_5, 0, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.ExperimentScrollArea.setWidget(self.SCF1)
        self.verticalLayout_4.addWidget(self.ExperimentScrollArea)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.hintText = QtWidgets.QTextBrowser(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hintText.sizePolicy().hasHeightForWidth())
        self.hintText.setSizePolicy(sizePolicy)
        self.hintText.setMinimumSize(QtCore.QSize(0, 30))
        self.hintText.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.hintText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hintText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hintText.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.hintText.setObjectName("hintText")
        self.verticalLayout_5.addWidget(self.hintText)
        self.verticalLayout.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab, "")
        self.HELPTAB = QtWidgets.QWidget()
        self.HELPTAB.setObjectName("HELPTAB")
        self.helpLayout = QtWidgets.QVBoxLayout(self.HELPTAB)
        self.helpLayout.setContentsMargins(0, 0, 0, 0)
        self.helpLayout.setSpacing(0)
        self.helpLayout.setObjectName("helpLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.HELPTAB)
        self.pushButton_2.setObjectName("pushButton_2")
        self.helpLayout.addWidget(self.pushButton_2)
        self.tabWidget.addTab(self.HELPTAB, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_5.sizePolicy().hasHeightForWidth())
        self.scrollArea_5.setSizePolicy(sizePolicy)
        self.scrollArea_5.setMinimumSize(QtCore.QSize(400, 0))
        self.scrollArea_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_5.setStyleSheet("")
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.SCF2 = QtWidgets.QWidget()
        self.SCF2.setGeometry(QtCore.QRect(0, 0, 382, 17))
        self.SCF2.setStyleSheet("")
        self.SCF2.setObjectName("SCF2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.SCF2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.SCF2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_8.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_8.setSpacing(5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.WidgetLayout = QtWidgets.QGridLayout()
        self.WidgetLayout.setContentsMargins(5, 5, 5, 5)
        self.WidgetLayout.setSpacing(7)
        self.WidgetLayout.setObjectName("WidgetLayout")
        self.gridLayout_8.addLayout(self.WidgetLayout, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_6, 0, 0, 1, 1)
        self.scrollArea_5.setWidget(self.SCF2)
        self.verticalLayout_3.addWidget(self.scrollArea_5)
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(86, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.deviceCombo = QtWidgets.QComboBox(self.frame_2)
        self.deviceCombo.setObjectName("deviceCombo")
        self.horizontalLayout.addWidget(self.deviceCombo)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layout = QtWidgets.QVBoxLayout(self.tab_4)
        self.layout.setContentsMargins(3, 3, 3, 3)
        self.layout.setObjectName("layout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.SCF3 = QtWidgets.QWidget()
        self.SCF3.setGeometry(QtCore.QRect(0, 0, 92, 22))
        self.SCF3.setObjectName("SCF3")
        self.advancedControlsLayout = QtWidgets.QGridLayout(self.SCF3)
        self.advancedControlsLayout.setContentsMargins(0, 0, 0, 0)
        self.advancedControlsLayout.setHorizontalSpacing(3)
        self.advancedControlsLayout.setObjectName("advancedControlsLayout")
        self.scrollArea.setWidget(self.SCF3)
        self.layout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 25))
        self.menubar.setObjectName("menubar")
        self.menuUtilities = QtWidgets.QMenu(self.menubar)
        self.menuUtilities.setObjectName("menuUtilities")
        self.menuColor_scheme = QtWidgets.QMenu(self.menuUtilities)
        self.menuColor_scheme.setObjectName("menuColor_scheme")
        self.menuRemote_server = QtWidgets.QMenu(self.menuUtilities)
        self.menuRemote_server.setObjectName("menuRemote_server")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionIPython_Console = QtWidgets.QAction(MainWindow)
        self.actionIPython_Console.setObjectName("actionIPython_Console")
        self.actionIPython = QtWidgets.QAction(MainWindow)
        self.actionIPython.setObjectName("actionIPython")
        self.actionReset_Device = QtWidgets.QAction(MainWindow)
        self.actionReset_Device.setObjectName("actionReset_Device")
        self.actionAbout_device = QtWidgets.QAction(MainWindow)
        self.actionAbout_device.setObjectName("actionAbout_device")
        self.actionWhite = QtWidgets.QAction(MainWindow)
        self.actionWhite.setObjectName("actionWhite")
        self.actionBlack = QtWidgets.QAction(MainWindow)
        self.actionBlack.setObjectName("actionBlack")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionExperiments = QtWidgets.QAction(MainWindow)
        self.actionExperiments.setObjectName("actionExperiments")
        self.menuColor_scheme.addAction(self.actionWhite)
        self.menuColor_scheme.addAction(self.actionBlack)
        self.menuRemote_server.addAction(self.actionStart)
        self.menuRemote_server.addAction(self.actionStop)
        self.menuUtilities.addAction(self.actionReset_Device)
        self.menuUtilities.addAction(self.actionAbout_device)
        self.menuUtilities.addAction(self.menuColor_scheme.menuAction())
        self.menuUtilities.addAction(self.menuRemote_server.menuAction())
        self.menuHelp.addAction(self.actionExperiments)
        self.menubar.addAction(self.menuUtilities.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionReset_Device.triggered.connect(MainWindow.resetDevice)
        self.pushButton.clicked.connect(MainWindow.selectDevice)
        self.actionAbout_device.triggered.connect(MainWindow.launchAboutDevice)
        self.actionWhite.triggered.connect(MainWindow.setColorSchemeWhite)
        self.actionBlack.triggered.connect(MainWindow.setColorSchemeBlack)
        self.actionStart.triggered.connect(MainWindow.startRemoteServer)
        self.pushButton_2.clicked.connect(MainWindow.returnToApps)
        self.actionExperiments.triggered.connect(MainWindow.importExperimentFolder)
        self.subSections.currentIndexChanged['int'].connect(MainWindow.changeSubSection)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FOSSASIA PSLab: Control Panel"))
        self.SCF1.setProperty("class", _translate("MainWindow", "PeripheralCollection"))
        self.hintText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Experiments "))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Icons for launching experiments"))
        self.pushButton_2.setText(_translate("MainWindow", "<<< Return To Application List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HELPTAB), _translate("MainWindow", "Help"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.HELPTAB), _translate("MainWindow", "Help window: This tab will automatically load the helpfile relevant to the last experiment you launched"))
        self.SCF2.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.pushButton.setText(_translate("MainWindow", "SET"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", " Controls  "))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Various knobs for setting the outputs such as power supplies and waveform generators. Also contains meters for voltage, frequency, and capacitance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "  Adv. controls  "))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Advanced control inputs for configuring the waveform generators and power supplies"))
        self.menuUtilities.setTitle(_translate("MainWindow", "Utilities"))
        self.menuColor_scheme.setTitle(_translate("MainWindow", "color scheme"))
        self.menuRemote_server.setTitle(_translate("MainWindow", "remote server"))
        self.menuHelp.setTitle(_translate("MainWindow", "import"))
        self.actionIPython_Console.setText(_translate("MainWindow", "iPython Console"))
        self.actionIPython.setText(_translate("MainWindow", "iPython Console"))
        self.actionReset_Device.setText(_translate("MainWindow", "Reset Device"))
        self.actionAbout_device.setText(_translate("MainWindow", "about device"))
        self.actionWhite.setText(_translate("MainWindow", "white"))
        self.actionBlack.setText(_translate("MainWindow", "black"))
        self.actionStart.setText(_translate("MainWindow", "start"))
        self.actionStop.setText(_translate("MainWindow", "stop"))
        self.actionExperiments.setText(_translate("MainWindow", "Experiment Package"))
        self.actionExperiments.setShortcut(_translate("MainWindow", "Ctrl+I"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
