# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transistor.ui'


from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(242, 416)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowOpacity(1.0)
        Form.setStyleSheet(_fromUtf8("QTextEdit {color: rgb(0, 0, 0);}\n"
"QLineEdit {color: rgb(0, 0, 0);}\n"
"QLineEdit:selected {color: rgb(0, 0, 0);}\n"
"QSpinBox{color: rgb(0, 0, 0);}"))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBox = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setStyleSheet(_fromUtf8(""))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBox)
        self.splitter = QtGui.QSplitter(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtGui.QFrame.Panel)
        self.splitter.setFrameShadow(QtGui.QFrame.Raised)
        self.splitter.setMidLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(8)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.NPN_Frame = QtGui.QFrame(self.splitter)
        self.NPN_Frame.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NPN_Frame.sizePolicy().hasHeightForWidth())
        self.NPN_Frame.setSizePolicy(sizePolicy)
        self.NPN_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.NPN_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.NPN_Frame.setObjectName(_fromUtf8("NPN_Frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.NPN_Frame)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.NPN_Frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.NPN_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        self.base_current_slider = QtGui.QSlider(self.NPN_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_current_slider.sizePolicy().hasHeightForWidth())
        self.base_current_slider.setSizePolicy(sizePolicy)
        self.base_current_slider.setBaseSize(QtCore.QSize(10, 0))
        self.base_current_slider.setMinimum(0)
        self.base_current_slider.setMaximum(4095)
        self.base_current_slider.setPageStep(1)
        self.base_current_slider.setProperty("value", 0)
        self.base_current_slider.setOrientation(QtCore.Qt.Horizontal)
        self.base_current_slider.setObjectName(_fromUtf8("base_current_slider"))
        self.gridLayout_4.addWidget(self.base_current_slider, 1, 0, 1, 1)
        self.IbeLabel = QtGui.QLabel(self.NPN_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IbeLabel.sizePolicy().hasHeightForWidth())
        self.IbeLabel.setSizePolicy(sizePolicy)
        self.IbeLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.IbeLabel.setObjectName(_fromUtf8("IbeLabel"))
        self.gridLayout_4.addWidget(self.IbeLabel, 1, 1, 1, 1)
        self.PNP_Frame = QtGui.QFrame(self.splitter)
        self.PNP_Frame.setEnabled(True)
        self.PNP_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.PNP_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.PNP_Frame.setObjectName(_fromUtf8("PNP_Frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.PNP_Frame)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.PNP_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 1)
        self.IbeLabel2 = QtGui.QLabel(self.PNP_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IbeLabel2.sizePolicy().hasHeightForWidth())
        self.IbeLabel2.setSizePolicy(sizePolicy)
        self.IbeLabel2.setObjectName(_fromUtf8("IbeLabel2"))
        self.gridLayout_2.addWidget(self.IbeLabel2, 1, 1, 1, 1)
        self.resistance_value = QtGui.QSpinBox(self.PNP_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistance_value.sizePolicy().hasHeightForWidth())
        self.resistance_value.setSizePolicy(sizePolicy)
        self.resistance_value.setMinimumSize(QtCore.QSize(0, 0))
        self.resistance_value.setMinimum(100)
        self.resistance_value.setMaximum(50000)
        self.resistance_value.setProperty("value", 1000)
        self.resistance_value.setObjectName(_fromUtf8("resistance_value"))
        self.gridLayout_2.addWidget(self.resistance_value, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.PNP_Frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.PNP_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.base_voltage_label = QtGui.QSlider(self.PNP_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_voltage_label.sizePolicy().hasHeightForWidth())
        self.base_voltage_label.setSizePolicy(sizePolicy)
        self.base_voltage_label.setBaseSize(QtCore.QSize(20, 0))
        self.base_voltage_label.setMaximum(4095)
        self.base_voltage_label.setPageStep(1)
        self.base_voltage_label.setProperty("value", 15)
        self.base_voltage_label.setOrientation(QtCore.Qt.Horizontal)
        self.base_voltage_label.setObjectName(_fromUtf8("base_voltage_label"))
        self.gridLayout_2.addWidget(self.base_voltage_label, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        self.frame_5 = QtGui.QFrame(self.frame)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.IceLabel = QtGui.QLabel(self.frame_5)
        self.IceLabel.setObjectName(_fromUtf8("IceLabel"))
        self.gridLayout_5.addWidget(self.IceLabel, 0, 0, 1, 1)
        self.VceLabel = QtGui.QLabel(self.frame_5)
        self.VceLabel.setObjectName(_fromUtf8("VceLabel"))
        self.gridLayout_5.addWidget(self.VceLabel, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.progress = QtGui.QProgressBar(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress.sizePolicy().hasHeightForWidth())
        self.progress.setSizePolicy(sizePolicy)
        self.progress.setStyleSheet(_fromUtf8(""))
        self.progress.setProperty("value", 0)
        self.progress.setObjectName(_fromUtf8("progress"))
        self.verticalLayout.addWidget(self.progress)
        self.frame_3 = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setStyleSheet(_fromUtf8(""))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_3 = QtGui.QPushButton(self.frame_3)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.saved_traces = QtGui.QComboBox(self.frame_3)
        self.saved_traces.setMinimumSize(QtCore.QSize(40, 0))
        self.saved_traces.setStyleSheet(_fromUtf8("QComboBox{background-color: rgba(255, 255, 255, 50);}\n"
""))
        self.saved_traces.setObjectName(_fromUtf8("saved_traces"))
        self.gridLayout_3.addWidget(self.saved_traces, 1, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.filename_text = QtGui.QLineEdit(self.frame_3)
        self.filename_text.setStyleSheet(_fromUtf8(""))
        self.filename_text.setObjectName(_fromUtf8("filename_text"))
        self.gridLayout_3.addWidget(self.filename_text, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.base_current_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.setBaseCurrent)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.start)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.delete_curve)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.saveData)
        QtCore.QObject.connect(self.base_voltage_label, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.setBaseVoltage)
        QtCore.QObject.connect(self.resistance_value, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.setSeriesR)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Form.changeTransistorType)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.showData)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.comboBox.setItemText(0, _translate("Form", "NPN - Common Emitter", None))
        self.comboBox.setItemText(1, _translate("Form", "PNP", None))
        self.label_2.setText(_translate("Form", "Current Source", None))
        self.label_3.setText(_translate("Form", "0->3.3mA", None))
        self.base_current_slider.setToolTip(_translate("Form", "Set the programmable current source output. Feed this into the base of the transistor", None))
        self.IbeLabel.setText(_translate("Form", "I_be = 0 mA  ", None))
        self.label_6.setText(_translate("Form", "Series Resistor", None))
        self.IbeLabel2.setText(_translate("Form", "I_be = 0mA ", None))
        self.resistance_value.setToolTip(_translate("Form", "In order to create negative base currents for NPN transistors,\n"
" A bipolar voltage source is used with a series resistor. \n"
"Specify the accurate value of the series resistance \n"
"to estimate the current flow", None))
        self.resistance_value.setSuffix(_translate("Form", " Ohms", None))
        self.label_4.setText(_translate("Form", "Voltage Source", None))
        self.label_5.setText(_translate("Form", "-3.3->3.3V", None))
        self.base_voltage_label.setToolTip(_translate("Form", "Set the value of PV3 (-3.3 Volts to 3.3 Volts)", None))
        self.IceLabel.setToolTip(_translate("Form", "Current flowing through the emitter.", None))
        self.IceLabel.setText(_translate("Form", "I_ce=", None))
        self.VceLabel.setToolTip(_translate("Form", "Voltage across the collector and emitter", None))
        self.VceLabel.setText(_translate("Form", "V_ce=", None))
        self.pushButton.setText(_translate("Form", "Start", None))
        self.pushButton_3.setText(_translate("Form", "Save Data", None))
        self.pushButton_2.setText(_translate("Form", "Delete", None))
        self.filename_text.setText(_translate("Form", "Filename.txt", None))
        self.label.setText(_translate("Form", "Data", None))
        self.pushButton_4.setText(_translate("Form", "Display", None))

