# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scope.ui'


from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(889, 558)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/pixmaps/cubeview48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8(" QPushButton{ background-image: url(:/images/bt_01_off.png);\n"
"color: rgb(255, 255, 255);}\n"
" QPushButton:pressed {background-image:url(:/images/bt_01_on.png);}\n"
"QFrame{background-color: rgb(21, 107, 113);}\n"
"\n"
"QLabel,QRadioButton,QCheckBox {color: rgb(255, 255, 255);}\n"
"QLabel,QRadioButton,QCheckBox{background-color: rgba(0,0,0, 0);color: rgb(0,0,0);}\n"
"QComboBox{background-color: rgba(255,255,255, 100);color: rgb(0,0,0);}\n"
"\n"
"border-color: rgb(29, 122, 162);\n"
""))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.plot_area_frame = QtGui.QFrame(self.splitter)
        self.plot_area_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_area_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_area_frame.setObjectName(_fromUtf8("plot_area_frame"))
        self.plot_area = QtGui.QVBoxLayout(self.plot_area_frame)
        self.plot_area.setSpacing(2)
        self.plot_area.setMargin(0)
        self.plot_area.setObjectName(_fromUtf8("plot_area"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(291, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(_fromUtf8("border-color: rgb(115, 0, 255);"))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Analog = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Analog.sizePolicy().hasHeightForWidth())
        self.Analog.setSizePolicy(sizePolicy)
        self.Analog.setObjectName(_fromUtf8("Analog"))
        self.frame = QtGui.QFrame(self.Analog)
        self.frame.setGeometry(QtCore.QRect(10, 140, 281, 71))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgba(255, 0, 0, 20);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.dial_11 = QtGui.QDial(self.frame)
        self.dial_11.setGeometry(QtCore.QRect(160, 0, 111, 71))
        self.dial_11.setMinimum(0)
        self.dial_11.setMaximum(1000)
        self.dial_11.setProperty("value", 500)
        self.dial_11.setNotchTarget(10.0)
        self.dial_11.setNotchesVisible(True)
        self.dial_11.setObjectName(_fromUtf8("dial_11"))
        self.trigger_level_box = QtGui.QDoubleSpinBox(self.frame)
        self.trigger_level_box.setGeometry(QtCore.QRect(10, 50, 141, 21))
        self.trigger_level_box.setReadOnly(True)
        self.trigger_level_box.setMinimum(-20.0)
        self.trigger_level_box.setMaximum(20.0)
        self.trigger_level_box.setObjectName(_fromUtf8("trigger_level_box"))
        self.trigger_select_box = QtGui.QComboBox(self.frame)
        self.trigger_select_box.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.trigger_select_box.setStyleSheet(_fromUtf8(""))
        self.trigger_select_box.setFrame(False)
        self.trigger_select_box.setObjectName(_fromUtf8("trigger_select_box"))
        self.trigger_select_box.addItem(_fromUtf8(""))
        self.trigger_select_box.addItem(_fromUtf8(""))
        self.trigger_select_box.addItem(_fromUtf8(""))
        self.trigger_select_box.addItem(_fromUtf8(""))
        self.label_48 = QtGui.QLabel(self.frame)
        self.label_48.setGeometry(QtCore.QRect(10, 0, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.frame_2 = QtGui.QFrame(self.Analog)
        self.frame_2.setGeometry(QtCore.QRect(10, 220, 281, 71))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.timebase_dial = QtGui.QDial(self.frame_2)
        self.timebase_dial.setGeometry(QtCore.QRect(160, 0, 111, 71))
        self.timebase_dial.setMinimum(0)
        self.timebase_dial.setMaximum(10)
        self.timebase_dial.setPageStep(1)
        self.timebase_dial.setProperty("value", 1)
        self.timebase_dial.setObjectName(_fromUtf8("timebase_dial"))
        self.timebase_label = QtGui.QDoubleSpinBox(self.frame_2)
        self.timebase_label.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.timebase_label.setReadOnly(True)
        self.timebase_label.setDecimals(3)
        self.timebase_label.setMaximum(1000.0)
        self.timebase_label.setSingleStep(0.125)
        self.timebase_label.setProperty("value", 1.175)
        self.timebase_label.setObjectName(_fromUtf8("timebase_label"))
        self.label_49 = QtGui.QLabel(self.frame_2)
        self.label_49.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.frame_3 = QtGui.QFrame(self.Analog)
        self.frame_3.setGeometry(QtCore.QRect(10, 370, 281, 71))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(180, 10, 98, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.Liss_show = QtGui.QCheckBox(self.frame_3)
        self.Liss_show.setGeometry(QtCore.QRect(90, 10, 71, 22))
        self.Liss_show.setObjectName(_fromUtf8("Liss_show"))
        self.checkBox_2 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_2.setGeometry(QtCore.QRect(180, 40, 91, 21))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.Liss_x = QtGui.QComboBox(self.frame_3)
        self.Liss_x.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.Liss_x.setObjectName(_fromUtf8("Liss_x"))
        self.Liss_x.addItem(_fromUtf8(""))
        self.Liss_x.addItem(_fromUtf8(""))
        self.Liss_y = QtGui.QComboBox(self.frame_3)
        self.Liss_y.setGeometry(QtCore.QRect(90, 40, 71, 21))
        self.Liss_y.setObjectName(_fromUtf8("Liss_y"))
        self.Liss_y.addItem(_fromUtf8(""))
        self.Liss_y.addItem(_fromUtf8(""))
        self.frame_6 = QtGui.QFrame(self.Analog)
        self.frame_6.setGeometry(QtCore.QRect(10, 300, 281, 61))
        self.frame_6.setStyleSheet(_fromUtf8("QCheckBox{background-color: rgba(255, 33, 0,0);}"))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.fit_select_box = QtGui.QComboBox(self.frame_6)
        self.fit_select_box.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.fit_select_box.setObjectName(_fromUtf8("fit_select_box"))
        self.fit_select_box.addItem(_fromUtf8(""))
        self.fit_select_box.addItem(_fromUtf8(""))
        self.fit_select_box.addItem(_fromUtf8(""))
        self.fit_select_box.addItem(_fromUtf8(""))
        self.fit_select_box.addItem(_fromUtf8(""))
        self.overlay_fit_button = QtGui.QCheckBox(self.frame_6)
        self.overlay_fit_button.setGeometry(QtCore.QRect(190, 0, 91, 21))
        self.overlay_fit_button.setObjectName(_fromUtf8("overlay_fit_button"))
        self.fit_select_box_2 = QtGui.QComboBox(self.frame_6)
        self.fit_select_box_2.setGeometry(QtCore.QRect(90, 30, 71, 21))
        self.fit_select_box_2.setObjectName(_fromUtf8("fit_select_box_2"))
        self.fit_select_box_2.addItem(_fromUtf8(""))
        self.fit_select_box_2.addItem(_fromUtf8(""))
        self.fit_select_box_2.addItem(_fromUtf8(""))
        self.fit_select_box_2.addItem(_fromUtf8(""))
        self.fit_select_box_2.addItem(_fromUtf8(""))
        self.fit_type_box = QtGui.QComboBox(self.frame_6)
        self.fit_type_box.setGeometry(QtCore.QRect(10, 3, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.fit_type_box.setFont(font)
        self.fit_type_box.setFrame(False)
        self.fit_type_box.setObjectName(_fromUtf8("fit_type_box"))
        self.fit_type_box.addItem(_fromUtf8(""))
        self.collapseButton = QtGui.QCheckBox(self.frame_6)
        self.collapseButton.setGeometry(QtCore.QRect(250, 40, 21, 21))
        self.collapseButton.setObjectName(_fromUtf8("collapseButton"))
        self.frame_11 = QtGui.QFrame(self.Analog)
        self.frame_11.setGeometry(QtCore.QRect(10, 10, 281, 121))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.CH1_REMAPS = QtGui.QComboBox(self.frame_11)
        self.CH1_REMAPS.setGeometry(QtCore.QRect(220, 10, 61, 21))
        self.CH1_REMAPS.setObjectName(_fromUtf8("CH1_REMAPS"))
        self.CH1_LABEL = QtGui.QLabel(self.frame_11)
        self.CH1_LABEL.setGeometry(QtCore.QRect(20, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.CH1_LABEL.setFont(font)
        self.CH1_LABEL.setObjectName(_fromUtf8("CH1_LABEL"))
        self.CH2_LABEL = QtGui.QLabel(self.frame_11)
        self.CH2_LABEL.setGeometry(QtCore.QRect(20, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.CH2_LABEL.setFont(font)
        self.CH2_LABEL.setObjectName(_fromUtf8("CH2_LABEL"))
        self.comboBox_6 = QtGui.QComboBox(self.frame_11)
        self.comboBox_6.setGeometry(QtCore.QRect(130, 10, 78, 21))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_7 = QtGui.QComboBox(self.frame_11)
        self.comboBox_7.setGeometry(QtCore.QRect(130, 50, 78, 20))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.label_30 = QtGui.QLabel(self.frame_11)
        self.label_30.setGeometry(QtCore.QRect(90, 10, 31, 17))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.frame_11)
        self.label_31.setGeometry(QtCore.QRect(90, 50, 31, 17))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.CH1_ENABLE = QtGui.QCheckBox(self.frame_11)
        self.CH1_ENABLE.setGeometry(QtCore.QRect(0, 10, 21, 20))
        self.CH1_ENABLE.setText(_fromUtf8(""))
        self.CH1_ENABLE.setChecked(True)
        self.CH1_ENABLE.setObjectName(_fromUtf8("CH1_ENABLE"))
        self.CH2_ENABLE = QtGui.QCheckBox(self.frame_11)
        self.CH2_ENABLE.setGeometry(QtCore.QRect(0, 50, 21, 20))
        self.CH2_ENABLE.setText(_fromUtf8(""))
        self.CH2_ENABLE.setObjectName(_fromUtf8("CH2_ENABLE"))
        self.offsetLabel = QtGui.QLabel(self.frame_11)
        self.offsetLabel.setGeometry(QtCore.QRect(240, 30, 41, 31))
        self.offsetLabel.setObjectName(_fromUtf8("offsetLabel"))
        self.FOURCHAN_ENABLE = QtGui.QCheckBox(self.frame_11)
        self.FOURCHAN_ENABLE.setGeometry(QtCore.QRect(0, 90, 21, 20))
        self.FOURCHAN_ENABLE.setText(_fromUtf8(""))
        self.FOURCHAN_ENABLE.setChecked(False)
        self.FOURCHAN_ENABLE.setObjectName(_fromUtf8("FOURCHAN_ENABLE"))
        self.CH2_LABEL_2 = QtGui.QLabel(self.frame_11)
        self.CH2_LABEL_2.setGeometry(QtCore.QRect(20, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.CH2_LABEL_2.setFont(font)
        self.CH2_LABEL_2.setObjectName(_fromUtf8("CH2_LABEL_2"))
        self.tabWidget.addTab(self.Analog, _fromUtf8(""))
        self.Digital = QtGui.QWidget()
        self.Digital.setObjectName(_fromUtf8("Digital"))
        self.active_channel_box = QtGui.QComboBox(self.Digital)
        self.active_channel_box.setGeometry(QtCore.QRect(150, 6, 121, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.active_channel_box.sizePolicy().hasHeightForWidth())
        self.active_channel_box.setSizePolicy(sizePolicy)
        self.active_channel_box.setObjectName(_fromUtf8("active_channel_box"))
        self.active_channel_box.addItem(_fromUtf8(""))
        self.active_channel_box.addItem(_fromUtf8(""))
        self.active_channel_box.addItem(_fromUtf8(""))
        self.active_channel_box.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.Digital)
        self.label_13.setGeometry(QtCore.QRect(30, 10, 106, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.frame_4 = QtGui.QFrame(self.Digital)
        self.frame_4.setGeometry(QtCore.QRect(10, 30, 281, 61))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.dial_16 = QtGui.QDial(self.frame_4)
        self.dial_16.setGeometry(QtCore.QRect(180, 0, 111, 61))
        self.dial_16.setMinimum(0)
        self.dial_16.setMaximum(9)
        self.dial_16.setPageStep(1)
        self.dial_16.setProperty("value", 0)
        self.dial_16.setObjectName(_fromUtf8("dial_16"))
        self.digital_timescale = QtGui.QSpinBox(self.frame_4)
        self.digital_timescale.setGeometry(QtCore.QRect(10, 30, 141, 27))
        self.digital_timescale.setReadOnly(True)
        self.digital_timescale.setMaximum(10000)
        self.digital_timescale.setProperty("value", 1)
        self.digital_timescale.setObjectName(_fromUtf8("digital_timescale"))
        self.label_53 = QtGui.QLabel(self.frame_4)
        self.label_53.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.frame_5 = QtGui.QFrame(self.Digital)
        self.frame_5.setGeometry(QtCore.QRect(10, 200, 281, 141))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.formLayout = QtGui.QFormLayout(self.frame_5)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_54 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_54)
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBox = QtGui.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.comboBox_2 = QtGui.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_2)
        self.label_11 = QtGui.QLabel(self.frame_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.comboBox_3 = QtGui.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_3)
        self.label_12 = QtGui.QLabel(self.frame_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_12)
        self.comboBox_4 = QtGui.QComboBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBox_4)
        self.frame_7 = QtGui.QFrame(self.Digital)
        self.frame_7.setGeometry(QtCore.QRect(10, 350, 281, 121))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.edge2chan = QtGui.QComboBox(self.frame_7)
        self.edge2chan.setObjectName(_fromUtf8("edge2chan"))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.edge2chan.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge2chan, 2, 1, 1, 1)
        self.edge1edge = QtGui.QComboBox(self.frame_7)
        self.edge1edge.setObjectName(_fromUtf8("edge1edge"))
        self.edge1edge.addItem(_fromUtf8(""))
        self.edge1edge.addItem(_fromUtf8(""))
        self.edge1edge.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge1edge, 1, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.edge2edge = QtGui.QComboBox(self.frame_7)
        self.edge2edge.setObjectName(_fromUtf8("edge2edge"))
        self.edge2edge.addItem(_fromUtf8(""))
        self.edge2edge.addItem(_fromUtf8(""))
        self.edge2edge.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge2edge, 2, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.edge1chan = QtGui.QComboBox(self.frame_7)
        self.edge1chan.setObjectName(_fromUtf8("edge1chan"))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.edge1chan.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge1chan, 1, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_4.addWidget(self.label_56, 0, 0, 1, 3)
        self.pushButton_6 = QtGui.QPushButton(self.frame_7)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_4.addWidget(self.pushButton_6, 3, 0, 1, 3)
        self.time_interval_label = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.time_interval_label.setFont(font)
        self.time_interval_label.setObjectName(_fromUtf8("time_interval_label"))
        self.gridLayout_4.addWidget(self.time_interval_label, 6, 0, 1, 3)
        self.frame_8 = QtGui.QFrame(self.Digital)
        self.frame_8.setGeometry(QtCore.QRect(10, 100, 281, 51))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.label_58 = QtGui.QLabel(self.frame_8)
        self.label_58.setGeometry(QtCore.QRect(10, 0, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.LA1_chanmode = QtGui.QComboBox(self.frame_8)
        self.LA1_chanmode.setGeometry(QtCore.QRect(150, 20, 121, 21))
        self.LA1_chanmode.setObjectName(_fromUtf8("LA1_chanmode"))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.LA1_chanmode.addItem(_fromUtf8(""))
        self.label_28 = QtGui.QLabel(self.frame_8)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.LA1_chan = QtGui.QComboBox(self.frame_8)
        self.LA1_chan.setGeometry(QtCore.QRect(70, 20, 71, 21))
        self.LA1_chan.setObjectName(_fromUtf8("LA1_chan"))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.LA1_chan.addItem(_fromUtf8(""))
        self.frame_10 = QtGui.QFrame(self.Digital)
        self.frame_10.setGeometry(QtCore.QRect(10, 160, 281, 31))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_10)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_29 = QtGui.QLabel(self.frame_10)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_2.addWidget(self.label_29)
        self.LA1_trig = QtGui.QComboBox(self.frame_10)
        self.LA1_trig.setObjectName(_fromUtf8("LA1_trig"))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.LA1_trig.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.LA1_trig)
        self.LA1_trigmode = QtGui.QComboBox(self.frame_10)
        self.LA1_trigmode.setObjectName(_fromUtf8("LA1_trigmode"))
        self.LA1_trigmode.addItem(_fromUtf8(""))
        self.LA1_trigmode.addItem(_fromUtf8(""))
        self.LA1_trigmode.addItem(_fromUtf8(""))
        self.LA1_trigmode.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.LA1_trigmode)
        self.tabWidget.addTab(self.Digital, _fromUtf8(""))
        self.Peripheral = QtGui.QWidget()
        self.Peripheral.setObjectName(_fromUtf8("Peripheral"))
        self.layoutWidget = QtGui.QWidget(self.Peripheral)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 297, 241))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.PV2_LABEL = QtGui.QLabel(self.layoutWidget)
        self.PV2_LABEL.setObjectName(_fromUtf8("PV2_LABEL"))
        self.gridLayout.addWidget(self.PV2_LABEL, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.PV3_LABEL = QtGui.QLabel(self.layoutWidget)
        self.PV3_LABEL.setObjectName(_fromUtf8("PV3_LABEL"))
        self.gridLayout.addWidget(self.PV3_LABEL, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.PCS_LABEL = QtGui.QLabel(self.layoutWidget)
        self.PCS_LABEL.setObjectName(_fromUtf8("PCS_LABEL"))
        self.gridLayout.addWidget(self.PCS_LABEL, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 4, 0, 1, 1)
        self.WAVE1_FREQ = QtGui.QLabel(self.layoutWidget)
        self.WAVE1_FREQ.setObjectName(_fromUtf8("WAVE1_FREQ"))
        self.gridLayout.addWidget(self.WAVE1_FREQ, 4, 1, 1, 1)
        self.sinebox2 = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinebox2.sizePolicy().hasHeightForWidth())
        self.sinebox2.setSizePolicy(sizePolicy)
        self.sinebox2.setMaximum(1000000.0)
        self.sinebox2.setObjectName(_fromUtf8("sinebox2"))
        self.gridLayout.addWidget(self.sinebox2, 4, 2, 1, 1)
        self.PV1_LABEL = QtGui.QLabel(self.layoutWidget)
        self.PV1_LABEL.setObjectName(_fromUtf8("PV1_LABEL"))
        self.gridLayout.addWidget(self.PV1_LABEL, 0, 1, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider.setMaximum(4095)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout.addWidget(self.horizontalSlider, 0, 2, 1, 1)
        self.horizontalSlider_2 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_2.setMaximum(4095)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.gridLayout.addWidget(self.horizontalSlider_2, 1, 2, 1, 1)
        self.horizontalSlider_3 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_3.setMaximum(4095)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.gridLayout.addWidget(self.horizontalSlider_3, 2, 2, 1, 1)
        self.horizontalSlider_4 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_4.setMaximum(4095)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.gridLayout.addWidget(self.horizontalSlider_4, 3, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 5, 0, 1, 1)
        self.WAVE2_FREQ = QtGui.QLabel(self.layoutWidget)
        self.WAVE2_FREQ.setObjectName(_fromUtf8("WAVE2_FREQ"))
        self.gridLayout.addWidget(self.WAVE2_FREQ, 5, 1, 1, 1)
        self.sinebox1 = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinebox1.sizePolicy().hasHeightForWidth())
        self.sinebox1.setSizePolicy(sizePolicy)
        self.sinebox1.setMaximum(1000000.0)
        self.sinebox1.setObjectName(_fromUtf8("sinebox1"))
        self.gridLayout.addWidget(self.sinebox1, 5, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 6, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 6, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 6, 2, 1, 1)
        self.sinePhase_freq = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinePhase_freq.sizePolicy().hasHeightForWidth())
        self.sinePhase_freq.setSizePolicy(sizePolicy)
        self.sinePhase_freq.setMinimum(5.0)
        self.sinePhase_freq.setMaximum(5000.0)
        self.sinePhase_freq.setObjectName(_fromUtf8("sinePhase_freq"))
        self.gridLayout.addWidget(self.sinePhase_freq, 7, 0, 1, 1)
        self.sinePhase_phase = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinePhase_phase.sizePolicy().hasHeightForWidth())
        self.sinePhase_phase.setSizePolicy(sizePolicy)
        self.sinePhase_phase.setDecimals(1)
        self.sinePhase_phase.setMaximum(359.0)
        self.sinePhase_phase.setObjectName(_fromUtf8("sinePhase_phase"))
        self.gridLayout.addWidget(self.sinePhase_phase, 7, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 7, 2, 1, 1)
        self.layoutWidget_2 = QtGui.QWidget(self.Peripheral)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 250, 271, 159))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 1, 0, 1, 1)
        self.SQR_NM = QtGui.QComboBox(self.layoutWidget_2)
        self.SQR_NM.setObjectName(_fromUtf8("SQR_NM"))
        self.SQR_NM.addItem(_fromUtf8(""))
        self.SQR_NM.addItem(_fromUtf8(""))
        self.SQR_NM.addItem(_fromUtf8(""))
        self.SQR_NM.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.SQR_NM, 3, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_5.addWidget(self.label_21, 2, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 3)
        self.label_18 = QtGui.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_5.addWidget(self.pushButton_7, 4, 0, 1, 3)
        self.SQR_FREQ = QtGui.QSpinBox(self.layoutWidget_2)
        self.SQR_FREQ.setMinimum(1)
        self.SQR_FREQ.setMaximum(1000000)
        self.SQR_FREQ.setProperty("value", 500)
        self.SQR_FREQ.setObjectName(_fromUtf8("SQR_FREQ"))
        self.gridLayout_5.addWidget(self.SQR_FREQ, 1, 1, 1, 2)
        self.SQR_PH = QtGui.QSpinBox(self.layoutWidget_2)
        self.SQR_PH.setMaximum(360)
        self.SQR_PH.setObjectName(_fromUtf8("SQR_PH"))
        self.gridLayout_5.addWidget(self.SQR_PH, 3, 1, 1, 1)
        self.SQR_DC = QtGui.QSpinBox(self.layoutWidget_2)
        self.SQR_DC.setMaximum(100)
        self.SQR_DC.setProperty("value", 50)
        self.SQR_DC.setObjectName(_fromUtf8("SQR_DC"))
        self.gridLayout_5.addWidget(self.SQR_DC, 3, 2, 1, 1)
        self.tabWidget.addTab(self.Peripheral, _fromUtf8(""))
        self.verticalLayout.addWidget(self.splitter)
        self.frame_9 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 17))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 34))
        self.frame_9.setBaseSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.message_label = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_label.sizePolicy().hasHeightForWidth())
        self.message_label.setSizePolicy(sizePolicy)
        self.message_label.setBaseSize(QtCore.QSize(0, 17))
        self.message_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.message_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.message_label.setWordWrap(True)
        self.message_label.setObjectName(_fromUtf8("message_label"))
        self.horizontalLayout.addWidget(self.message_label)
        self.coord_label = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coord_label.sizePolicy().hasHeightForWidth())
        self.coord_label.setSizePolicy(sizePolicy)
        self.coord_label.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.coord_label.setFont(font)
        self.coord_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coord_label.setObjectName(_fromUtf8("coord_label"))
        self.horizontalLayout.addWidget(self.coord_label)
        self.freezeButton = QtGui.QCheckBox(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freezeButton.sizePolicy().hasHeightForWidth())
        self.freezeButton.setSizePolicy(sizePolicy)
        self.freezeButton.setMaximumSize(QtCore.QSize(100, 10))
        self.freezeButton.setObjectName(_fromUtf8("freezeButton"))
        self.horizontalLayout.addWidget(self.freezeButton)
        self.verticalLayout.addWidget(self.frame_9)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Liss_y.setCurrentIndex(1)
        self.fit_select_box.setCurrentIndex(4)
        self.fit_select_box_2.setCurrentIndex(4)
        self.fit_type_box.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(1)
        self.comboBox_2.setCurrentIndex(1)
        self.comboBox_3.setCurrentIndex(1)
        self.comboBox_4.setCurrentIndex(1)
        self.edge2edge.setCurrentIndex(0)
        self.LA1_chanmode.setCurrentIndex(1)
        self.LA1_trigmode.setCurrentIndex(0)
        QtCore.QObject.connect(self.active_channel_box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.setActiveDigitalChannels)
        QtCore.QObject.connect(self.comboBox_3, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.set_dchan_mode_ch3)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.plot_liss)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.change_scope_type)
        QtCore.QObject.connect(self.comboBox_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.set_dchan_mode_ch2)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.liss_animate)
        QtCore.QObject.connect(self.trigger_select_box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setTriggerChannel)
        QtCore.QObject.connect(self.dial_16, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.set_digital_scope_time)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.set_dchan_mode_ch1)
        QtCore.QObject.connect(self.dial_11, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setTriggerLevel)
        QtCore.QObject.connect(self.comboBox_4, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.set_dchan_mode_ch4)
        QtCore.QObject.connect(self.timebase_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setTimeBase)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.measure_interval)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sqr_update)
        QtCore.QObject.connect(self.SQR_PH, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.sqr_phase)
        QtCore.QObject.connect(self.SQR_DC, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.sqr_dc)
        QtCore.QObject.connect(self.sinebox2, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.setSINE1)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setPV1)
        QtCore.QObject.connect(self.horizontalSlider_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setPV2)
        QtCore.QObject.connect(self.horizontalSlider_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setPV3)
        QtCore.QObject.connect(self.horizontalSlider_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setPCS)
        QtCore.QObject.connect(self.comboBox_6, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setGainCH1)
        QtCore.QObject.connect(self.comboBox_7, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setGainCH2)
        QtCore.QObject.connect(self.CH1_REMAPS, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.remap_CH0)
        QtCore.QObject.connect(self.sinebox1, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.setSINE2)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.setSinePhase)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Test and Measurement Suite", None))
        self.trigger_level_box.setSuffix(_translate("MainWindow", " V", None))
        self.trigger_select_box.setItemText(0, _translate("MainWindow", "CH1", None))
        self.trigger_select_box.setItemText(1, _translate("MainWindow", "CH2", None))
        self.trigger_select_box.setItemText(2, _translate("MainWindow", "CH3", None))
        self.trigger_select_box.setItemText(3, _translate("MainWindow", "MIC", None))
        self.label_48.setText(_translate("MainWindow", "TRIGGER", None))
        self.timebase_label.setSuffix(_translate("MainWindow", "uS", None))
        self.label_49.setText(_translate("MainWindow", "TIME GAP", None))
        self.label.setText(_translate("MainWindow", "Lissajous ", None))
        self.pushButton.setText(_translate("MainWindow", "PLOT", None))
        self.Liss_show.setText(_translate("MainWindow", "Show", None))
        self.checkBox_2.setText(_translate("MainWindow", "animate", None))
        self.Liss_x.setItemText(0, _translate("MainWindow", "CH1", None))
        self.Liss_x.setItemText(1, _translate("MainWindow", "CH2", None))
        self.Liss_y.setItemText(0, _translate("MainWindow", "CH1", None))
        self.Liss_y.setItemText(1, _translate("MainWindow", "CH2", None))
        self.fit_select_box.setItemText(0, _translate("MainWindow", "CH1", None))
        self.fit_select_box.setItemText(1, _translate("MainWindow", "CH2", None))
        self.fit_select_box.setItemText(2, _translate("MainWindow", "CH3", None))
        self.fit_select_box.setItemText(3, _translate("MainWindow", "MIC", None))
        self.fit_select_box.setItemText(4, _translate("MainWindow", "None", None))
        self.overlay_fit_button.setText(_translate("MainWindow", "Overlay", None))
        self.fit_select_box_2.setItemText(0, _translate("MainWindow", "CH1", None))
        self.fit_select_box_2.setItemText(1, _translate("MainWindow", "CH2", None))
        self.fit_select_box_2.setItemText(2, _translate("MainWindow", "CH3", None))
        self.fit_select_box_2.setItemText(3, _translate("MainWindow", "MIC", None))
        self.fit_select_box_2.setItemText(4, _translate("MainWindow", "None", None))
        self.fit_type_box.setItemText(0, _translate("MainWindow", "SINE FIT", None))
        self.collapseButton.setText(_translate("MainWindow", ".", None))
        self.CH1_LABEL.setText(_translate("MainWindow", "CH1", None))
        self.CH2_LABEL.setText(_translate("MainWindow", "CH2", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "1x", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "2x", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "4x", None))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "5x", None))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "8x", None))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "10x", None))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "16x", None))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "32x", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "1x", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "2x", None))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "4x", None))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "5x", None))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "8x", None))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "10x", None))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "16x", None))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "32x", None))
        self.label_30.setText(_translate("MainWindow", "gain", None))
        self.label_31.setText(_translate("MainWindow", "gain", None))
        self.offsetLabel.setText(_translate("MainWindow", ".", None))
        self.CH2_LABEL_2.setText(_translate("MainWindow", "CH3 , MIC", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analog), _translate("MainWindow", "Analog signals", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Analog), _translate("MainWindow", "Four channel, 1MSPS Oscilloscope", None))
        self.active_channel_box.setItemText(0, _translate("MainWindow", "1", None))
        self.active_channel_box.setItemText(1, _translate("MainWindow", "2", None))
        self.active_channel_box.setItemText(2, _translate("MainWindow", "3", None))
        self.active_channel_box.setItemText(3, _translate("MainWindow", "4", None))
        self.label_13.setText(_translate("MainWindow", "Active Channels", None))
        self.digital_timescale.setSuffix(_translate("MainWindow", "mS", None))
        self.label_53.setText(_translate("MainWindow", "ACQUISITION TIME", None))
        self.label_54.setText(_translate("MainWindow", "3/4 CHANNEL MODES", None))
        self.label_4.setText(_translate("MainWindow", "CH1 :", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_9.setText(_translate("MainWindow", "CH2 :", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_11.setText(_translate("MainWindow", "CH3 :", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_12.setText(_translate("MainWindow", "CH4 :", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.edge2chan.setItemText(0, _translate("MainWindow", "ID1", None))
        self.edge2chan.setItemText(1, _translate("MainWindow", "ID2", None))
        self.edge2chan.setItemText(2, _translate("MainWindow", "ID3", None))
        self.edge2chan.setItemText(3, _translate("MainWindow", "ID4", None))
        self.edge2chan.setItemText(4, _translate("MainWindow", "-", None))
        self.edge2chan.setItemText(5, _translate("MainWindow", "CH1", None))
        self.edge2chan.setItemText(6, _translate("MainWindow", "Fin", None))
        self.edge1edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.edge1edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.edge1edge.setItemText(2, _translate("MainWindow", "four rising edges", None))
        self.label_16.setText(_translate("MainWindow", "EDGE 1", None))
        self.edge2edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.edge2edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.edge2edge.setItemText(2, _translate("MainWindow", "four rising edges", None))
        self.label_17.setText(_translate("MainWindow", "EDGE 2", None))
        self.edge1chan.setItemText(0, _translate("MainWindow", "ID1", None))
        self.edge1chan.setItemText(1, _translate("MainWindow", "ID2", None))
        self.edge1chan.setItemText(2, _translate("MainWindow", "ID3", None))
        self.edge1chan.setItemText(3, _translate("MainWindow", "ID4", None))
        self.edge1chan.setItemText(4, _translate("MainWindow", "-", None))
        self.edge1chan.setItemText(5, _translate("MainWindow", "CH1", None))
        self.edge1chan.setItemText(6, _translate("MainWindow", "Fin", None))
        self.label_56.setText(_translate("MainWindow", "MEASURE TIME INTERVALS", None))
        self.pushButton_6.setText(_translate("MainWindow", "Go", None))
        self.time_interval_label.setText(_translate("MainWindow", "result:", None))
        self.label_58.setText(_translate("MainWindow", "SINGLE CHANNEL OPTIONS", None))
        self.LA1_chanmode.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.LA1_chanmode.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.LA1_chanmode.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.LA1_chanmode.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.LA1_chanmode.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_28.setText(_translate("MainWindow", "Channel", None))
        self.LA1_chan.setItemText(0, _translate("MainWindow", "ID1", None))
        self.LA1_chan.setItemText(1, _translate("MainWindow", "ID2", None))
        self.LA1_chan.setItemText(2, _translate("MainWindow", "ID3", None))
        self.LA1_chan.setItemText(3, _translate("MainWindow", "ID4", None))
        self.LA1_chan.setItemText(4, _translate("MainWindow", "-", None))
        self.LA1_chan.setItemText(5, _translate("MainWindow", "CH1", None))
        self.LA1_chan.setItemText(6, _translate("MainWindow", "Fin", None))
        self.label_29.setText(_translate("MainWindow", "trigger", None))
        self.LA1_trig.setItemText(0, _translate("MainWindow", "ID1", None))
        self.LA1_trig.setItemText(1, _translate("MainWindow", "ID2", None))
        self.LA1_trig.setItemText(2, _translate("MainWindow", "ID3", None))
        self.LA1_trig.setItemText(3, _translate("MainWindow", "ID4", None))
        self.LA1_trig.setItemText(4, _translate("MainWindow", "-", None))
        self.LA1_trig.setItemText(5, _translate("MainWindow", "CH1", None))
        self.LA1_trig.setItemText(6, _translate("MainWindow", "Fin", None))
        self.LA1_trigmode.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.LA1_trigmode.setItemText(1, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.LA1_trigmode.setItemText(2, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.LA1_trigmode.setItemText(3, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Digital), _translate("MainWindow", "Digital signals", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Digital), _translate("MainWindow", "Four channel Logic Analyzer", None))
        self.label_6.setText(_translate("MainWindow", "PV1 ", None))
        self.label_7.setText(_translate("MainWindow", "PV2 ", None))
        self.PV2_LABEL.setText(_translate("MainWindow", "-3.3 to 3.3V", None))
        self.label_5.setText(_translate("MainWindow", "PV3", None))
        self.PV3_LABEL.setText(_translate("MainWindow", "0 - 3.3V", None))
        self.label_8.setText(_translate("MainWindow", "PCS", None))
        self.PCS_LABEL.setText(_translate("MainWindow", "0-3.3mA", None))
        self.label_15.setText(_translate("MainWindow", "Wave 1", None))
        self.WAVE1_FREQ.setText(_translate("MainWindow", "10Hz to 5KHz", None))
        self.PV1_LABEL.setText(_translate("MainWindow", "-5 to 5V", None))
        self.label_22.setText(_translate("MainWindow", "Wave 2", None))
        self.WAVE2_FREQ.setText(_translate("MainWindow", "10Hz to 5KHz", None))
        self.label_24.setText(_translate("MainWindow", "Frequency", None))
        self.label_25.setText(_translate("MainWindow", "phase", None))
        self.label_26.setText(_translate("MainWindow", "Correlate", None))
        self.pushButton_2.setText(_translate("MainWindow", "SET PHASE", None))
        self.label_3.setText(_translate("MainWindow", "Frequency", None))
        self.SQR_NM.setItemText(0, _translate("MainWindow", "SQ1", None))
        self.SQR_NM.setItemText(1, _translate("MainWindow", "SQ2", None))
        self.SQR_NM.setItemText(2, _translate("MainWindow", "OD1", None))
        self.SQR_NM.setItemText(3, _translate("MainWindow", "OD2", None))
        self.label_21.setText(_translate("MainWindow", "Duty Cycle", None))
        self.label_20.setText(_translate("MainWindow", "Phase", None))
        self.label_2.setText(_translate("MainWindow", "Phase Correlated Square Waves", None))
        self.label_18.setText(_translate("MainWindow", "Output", None))
        self.pushButton_7.setText(_translate("MainWindow", "UPDATE", None))
        self.SQR_DC.setSuffix(_translate("MainWindow", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Peripheral), _translate("MainWindow", "Peripherals", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Peripheral), _translate("MainWindow", "Set values for function generators, voltage sources etc.", None))
        self.message_label.setText(_translate("MainWindow", "Msg:", None))
        self.coord_label.setText(_translate("MainWindow", "TextLabel", None))
        self.freezeButton.setText(_translate("MainWindow", "FREEZE", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as", None))

