# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PSL_Apps/templates/designer.ui'
#
# Created: Mon Jul 18 22:55:10 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(799, 451)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.eTabs = QtGui.QTabWidget(self.centralwidget)
        self.eTabs.setAutoFillBackground(True)
        self.eTabs.setObjectName(_fromUtf8("eTabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.confTable = QtGui.QTableWidget(self.tab)
        self.confTable.setRowCount(100)
        self.confTable.setColumnCount(2)
        self.confTable.setObjectName(_fromUtf8("confTable"))
        self.confTable.horizontalHeader().setDefaultSectionSize(150)
        self.confTable.horizontalHeader().setMinimumSectionSize(150)
        self.confTable.horizontalHeader().setStretchLastSection(True)
        self.confTable.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.confTable)
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.eTabs.addTab(self.tab, _fromUtf8(""))
        self.selectTab = QtGui.QWidget()
        self.selectTab.setObjectName(_fromUtf8("selectTab"))
        self.gridLayout = QtGui.QGridLayout(self.selectTab)
        self.gridLayout.setContentsMargins(0, 2, 0, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_7 = QtGui.QFrame(self.selectTab)
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_3.setContentsMargins(0, 2, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(3)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_10 = QtGui.QFrame(self.frame_7)
        self.frame_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(2, -1, 2, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.frame_12 = QtGui.QFrame(self.frame_10)
        self.frame_12.setFrameShape(QtGui.QFrame.Panel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.sweepLayout = QtGui.QVBoxLayout(self.frame_12)
        self.sweepLayout.setSpacing(3)
        self.sweepLayout.setMargin(2)
        self.sweepLayout.setObjectName(_fromUtf8("sweepLayout"))
        self.verticalLayout_2.addWidget(self.frame_12)
        self.gridLayout_3.addWidget(self.frame_10, 0, 1, 6, 1)
        self.frame_14 = QtGui.QFrame(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_14)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_6 = QtGui.QPushButton(self.frame_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.frame_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton.sizePolicy().hasHeightForWidth())
        self.commandLinkButton.setSizePolicy(sizePolicy)
        self.commandLinkButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.commandLinkButton.setIconSize(QtCore.QSize(20, 15))
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.horizontalLayout_3.addWidget(self.commandLinkButton)
        self.gridLayout_3.addWidget(self.frame_14, 5, 2, 1, 1)
        self.frame_11 = QtGui.QFrame(self.frame_7)
        self.frame_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_11)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(2, -1, 2, 2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.frame_3 = QtGui.QFrame(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.sampleReadbacks = QtGui.QGridLayout(self.frame_3)
        self.sampleReadbacks.setMargin(2)
        self.sampleReadbacks.setSpacing(2)
        self.sampleReadbacks.setObjectName(_fromUtf8("sampleReadbacks"))
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_13 = QtGui.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtGui.QFrame.Panel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.monitorLayout = QtGui.QVBoxLayout(self.frame_13)
        self.monitorLayout.setSpacing(2)
        self.monitorLayout.setMargin(2)
        self.monitorLayout.setObjectName(_fromUtf8("monitorLayout"))
        self.verticalLayout_3.addWidget(self.frame_13)
        self.gridLayout_3.addWidget(self.frame_11, 0, 2, 5, 1)
        self.frame = QtGui.QFrame(self.frame_7)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(2, -1, 2, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.frame_2 = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setProperty("class", _fromUtf8(""))
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.staticLayout = QtGui.QVBoxLayout(self.frame_2)
        self.staticLayout.setContentsMargins(0, 0, 0, 5)
        self.staticLayout.setObjectName(_fromUtf8("staticLayout"))
        self.verticalLayout.addWidget(self.frame_2)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 6, 1)
        self.gridLayout.addWidget(self.frame_7, 0, 6, 1, 2)
        self.eTabs.addTab(self.selectTab, _fromUtf8(""))
        self.runTab = QtGui.QWidget()
        self.runTab.setObjectName(_fromUtf8("runTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.runTab)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_8 = QtGui.QFrame(self.runTab)
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_4.setMargin(2)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_6 = QtGui.QFrame(self.frame_8)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_5 = QtGui.QPushButton(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.delayBox = QtGui.QSpinBox(self.frame_6)
        self.delayBox.setMinimum(0)
        self.delayBox.setMaximum(1000)
        self.delayBox.setObjectName(_fromUtf8("delayBox"))
        self.horizontalLayout_2.addWidget(self.delayBox)
        self.gridLayout_4.addWidget(self.frame_6, 0, 1, 1, 1)
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(self.frame_8)
        self.commandLinkButton_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.commandLinkButton_2.setFont(font)
        self.commandLinkButton_2.setObjectName(_fromUtf8("commandLinkButton_2"))
        self.gridLayout_4.addWidget(self.commandLinkButton_2, 2, 2, 1, 1)
        self.frame_5 = QtGui.QFrame(self.frame_8)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frame_4 = QtGui.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.controlsLayout = QtGui.QGridLayout(self.frame_4)
        self.controlsLayout.setMargin(2)
        self.controlsLayout.setSpacing(3)
        self.controlsLayout.setObjectName(_fromUtf8("controlsLayout"))
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.tbl = QtGui.QTableWidget(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl.sizePolicy().hasHeightForWidth())
        self.tbl.setSizePolicy(sizePolicy)
        self.tbl.setObjectName(_fromUtf8("tbl"))
        self.tbl.setColumnCount(0)
        self.tbl.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.tbl)
        self.gridLayout_4.addWidget(self.frame_5, 1, 0, 1, 3)
        self.gridLayout_2.addWidget(self.frame_8, 0, 1, 1, 1)
        self.eTabs.addTab(self.runTab, _fromUtf8(""))
        self.plotTab = QtGui.QWidget()
        self.plotTab.setObjectName(_fromUtf8("plotTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.plotTab)
        self.gridLayout_5.setMargin(3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.plotTab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_5.addWidget(self.pushButton, 0, 1, 1, 1)
        self.plotList = QtGui.QComboBox(self.plotTab)
        self.plotList.setMinimumSize(QtCore.QSize(200, 0))
        self.plotList.setObjectName(_fromUtf8("plotList"))
        self.gridLayout_5.addWidget(self.plotList, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.plotTab)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.frame_9 = QtGui.QFrame(self.plotTab)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.plot_area = QtGui.QVBoxLayout(self.frame_9)
        self.plot_area.setSpacing(0)
        self.plot_area.setMargin(0)
        self.plot_area.setObjectName(_fromUtf8("plot_area"))
        self.gridLayout_5.addWidget(self.frame_9, 1, 0, 1, 4)
        self.eTabs.addTab(self.plotTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.eTabs)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.eTabs.setCurrentIndex(1)
        QtCore.QObject.connect(self.commandLinkButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.prepare)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.runAll)
        QtCore.QObject.connect(self.commandLinkButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.plotColumns)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.saveData)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.deleteCurve)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.saveProfile)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.loadProfile)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_3.setText(_translate("MainWindow", "Load Profile From File", None))
        self.eTabs.setTabText(self.eTabs.indexOf(self.tab), _translate("MainWindow", "Load Profile", None))
        self.frame_7.setProperty("class", _translate("MainWindow", "PeripheralCollection", None))
        self.frame_10.setToolTip(_translate("MainWindow", "select the parameters you need to vary in\n"
"order to generate a dataset", None))
        self.frame_10.setProperty("class", _translate("MainWindow", "ControlWidget", None))
        self.label.setText(_translate("MainWindow", "SWEEP CHANNELS", None))
        self.pushButton_6.setText(_translate("MainWindow", "Save Profile", None))
        self.pushButton_6.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.commandLinkButton.setText(_translate("MainWindow", "Prepare Experiment!", None))
        self.commandLinkButton.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.frame_11.setToolTip(_translate("MainWindow", "Select the channels you need to monitor\n"
"in order to obtain the dataset", None))
        self.frame_11.setProperty("class", _translate("MainWindow", "ControlWidget", None))
        self.label_3.setText(_translate("MainWindow", "READBACK CHANNELS", None))
        self.frame.setToolTip(_translate("MainWindow", "Select the parameters that need to have a certain fixed value per dataset", None))
        self.frame.setProperty("class", _translate("MainWindow", "ControlWidget", None))
        self.label_2.setText(_translate("MainWindow", "MANUAL CHANNELS", None))
        self.eTabs.setTabText(self.eTabs.indexOf(self.selectTab), _translate("MainWindow", "Configure Experiment", None))
        self.frame_8.setProperty("class", _translate("MainWindow", "PeripheralCollection", None))
        self.frame_6.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.pushButton_5.setText(_translate("MainWindow", "Evaluate All Rows", None))
        self.delayBox.setSuffix(_translate("MainWindow", " mS settling time", None))
        self.commandLinkButton_2.setText(_translate("MainWindow", "                Plot Selected Columns", None))
        self.eTabs.setTabText(self.eTabs.indexOf(self.runTab), _translate("MainWindow", "Make Measurements", None))
        self.pushButton.setText(_translate("MainWindow", "Delete", None))
        self.pushButton_2.setText(_translate("MainWindow", "savePlots", None))
        self.eTabs.setTabText(self.eTabs.indexOf(self.plotTab), _translate("MainWindow", "View plots", None))

