# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'psl_res/GUI/A_TEST_AND_MEASUREMENT/A_TandM/templates/digitalScope.ui'
#
# Created: Sun Aug 21 23:13:15 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(944, 557)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/pixmaps/cubeview48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.plot_area_frame = QtGui.QFrame(self.splitter)
        self.plot_area_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_area_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_area_frame.setObjectName(_fromUtf8("plot_area_frame"))
        self.plot_area = QtGui.QVBoxLayout(self.plot_area_frame)
        self.plot_area.setSpacing(2)
        self.plot_area.setMargin(2)
        self.plot_area.setObjectName(_fromUtf8("plot_area"))
        self.frame_12 = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_12.setStyleSheet(_fromUtf8(""))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.frame_7 = QtGui.QFrame(self.frame_12)
        self.frame_7.setGeometry(QtCore.QRect(10, 325, 281, 191))
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setHorizontalSpacing(3)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.timeoutBox = QtGui.QSpinBox(self.frame_7)
        self.timeoutBox.setMinimum(10)
        self.timeoutBox.setMaximum(10000)
        self.timeoutBox.setObjectName(_fromUtf8("timeoutBox"))
        self.gridLayout_4.addWidget(self.timeoutBox, 4, 2, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_4.addWidget(self.pushButton_6, 4, 3, 1, 1)
        self.label = QtGui.QLabel(self.frame_7)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 2)
        self.edge2edge = QtGui.QComboBox(self.frame_7)
        self.edge2edge.setObjectName(_fromUtf8("edge2edge"))
        self.edge2edge.addItem(_fromUtf8(""))
        self.edge2edge.addItem(_fromUtf8(""))
        self.edge2edge.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge2edge, 3, 2, 1, 1)
        self.label_56 = QtGui.QLabel(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_4.addWidget(self.label_56, 0, 0, 1, 4)
        self.label_16 = QtGui.QLabel(self.frame_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.edge1edge = QtGui.QComboBox(self.frame_7)
        self.edge1edge.setObjectName(_fromUtf8("edge1edge"))
        self.edge1edge.addItem(_fromUtf8(""))
        self.edge1edge.addItem(_fromUtf8(""))
        self.edge1edge.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge1edge, 2, 2, 1, 1)
        self.edge2chan = QtGui.QComboBox(self.frame_7)
        self.edge2chan.setObjectName(_fromUtf8("edge2chan"))
        self.gridLayout_4.addWidget(self.edge2chan, 3, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 3, 0, 1, 1)
        self.edge1chan = QtGui.QComboBox(self.frame_7)
        self.edge1chan.setObjectName(_fromUtf8("edge1chan"))
        self.gridLayout_4.addWidget(self.edge1chan, 2, 1, 1, 1)
        self.edge1Count = QtGui.QComboBox(self.frame_7)
        self.edge1Count.setObjectName(_fromUtf8("edge1Count"))
        self.edge1Count.addItem(_fromUtf8(""))
        self.edge1Count.addItem(_fromUtf8(""))
        self.edge1Count.addItem(_fromUtf8(""))
        self.edge1Count.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge1Count, 2, 3, 1, 1)
        self.edge2Count = QtGui.QComboBox(self.frame_7)
        self.edge2Count.setObjectName(_fromUtf8("edge2Count"))
        self.edge2Count.addItem(_fromUtf8(""))
        self.edge2Count.addItem(_fromUtf8(""))
        self.edge2Count.addItem(_fromUtf8(""))
        self.edge2Count.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge2Count, 3, 3, 1, 1)
        self.timingResults = QtGui.QTableWidget(self.frame_7)
        self.timingResults.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.timingResults.setShowGrid(True)
        self.timingResults.setCornerButtonEnabled(True)
        self.timingResults.setRowCount(4)
        self.timingResults.setColumnCount(2)
        self.timingResults.setObjectName(_fromUtf8("timingResults"))
        self.timingResults.horizontalHeader().setVisible(False)
        self.timingResults.horizontalHeader().setDefaultSectionSize(115)
        self.timingResults.horizontalHeader().setMinimumSectionSize(60)
        self.timingResults.horizontalHeader().setStretchLastSection(True)
        self.timingResults.verticalHeader().setDefaultSectionSize(22)
        self.timingResults.verticalHeader().setMinimumSectionSize(20)
        self.timingResults.verticalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.timingResults, 10, 0, 1, 4)
        self.pushButton = QtGui.QPushButton(self.frame_12)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 94, 31))
        self.pushButton.setMinimumSize(QtCore.QSize(94, 0))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.progressBar = QtGui.QProgressBar(self.frame_12)
        self.progressBar.setGeometry(QtCore.QRect(10, 45, 281, 16))
        self.progressBar.setMaximum(2500)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.pushButton_2 = QtGui.QPushButton(self.frame_12)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 94, 31))
        self.pushButton_2.setMinimumSize(QtCore.QSize(94, 0))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.frame_12)
        self.pushButton_3.setGeometry(QtCore.QRect(205, 10, 94, 31))
        self.pushButton_3.setMinimumSize(QtCore.QSize(94, 0))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.channelSelection = QtGui.QToolBox(self.frame_12)
        self.channelSelection.setGeometry(QtCore.QRect(10, 65, 281, 246))
        self.channelSelection.setObjectName(_fromUtf8("channelSelection"))
        self.C1 = QtGui.QWidget()
        self.C1.setGeometry(QtCore.QRect(0, 0, 281, 122))
        self.C1.setObjectName(_fromUtf8("C1"))
        self.label_28 = QtGui.QLabel(self.C1)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.C1_chan = QtGui.QComboBox(self.C1)
        self.C1_chan.setGeometry(QtCore.QRect(135, 5, 141, 26))
        self.C1_chan.setObjectName(_fromUtf8("C1_chan"))
        self.C1_chanmode = QtGui.QComboBox(self.C1)
        self.C1_chanmode.setGeometry(QtCore.QRect(135, 40, 141, 26))
        self.C1_chanmode.setObjectName(_fromUtf8("C1_chanmode"))
        self.C1_chanmode.addItem(_fromUtf8(""))
        self.C1_chanmode.addItem(_fromUtf8(""))
        self.C1_chanmode.addItem(_fromUtf8(""))
        self.C1_chanmode.addItem(_fromUtf8(""))
        self.C1_chanmode.addItem(_fromUtf8(""))
        self.label_29 = QtGui.QLabel(self.C1)
        self.label_29.setGeometry(QtCore.QRect(10, 45, 131, 20))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_31 = QtGui.QLabel(self.C1)
        self.label_31.setEnabled(True)
        self.label_31.setGeometry(QtCore.QRect(10, 85, 81, 18))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.C1_trig = QtGui.QComboBox(self.C1)
        self.C1_trig.setEnabled(True)
        self.C1_trig.setGeometry(QtCore.QRect(83, 80, 78, 26))
        self.C1_trig.setFrame(True)
        self.C1_trig.setObjectName(_fromUtf8("C1_trig"))
        self.C1_trigmode = QtGui.QComboBox(self.C1)
        self.C1_trigmode.setEnabled(True)
        self.C1_trigmode.setGeometry(QtCore.QRect(163, 80, 113, 26))
        self.C1_trigmode.setFrame(True)
        self.C1_trigmode.setObjectName(_fromUtf8("C1_trigmode"))
        self.C1_trigmode.addItem(_fromUtf8(""))
        self.C1_trigmode.addItem(_fromUtf8(""))
        self.C1_trigmode.addItem(_fromUtf8(""))
        self.C1_trigmode.addItem(_fromUtf8(""))
        self.channelSelection.addItem(self.C1, _fromUtf8(""))
        self.C2 = QtGui.QWidget()
        self.C2.setObjectName(_fromUtf8("C2"))
        self.C2_ID1 = QtGui.QComboBox(self.C2)
        self.C2_ID1.setGeometry(QtCore.QRect(83, 4, 78, 26))
        self.C2_ID1.setObjectName(_fromUtf8("C2_ID1"))
        self.label_33 = QtGui.QLabel(self.C2)
        self.label_33.setGeometry(QtCore.QRect(10, 10, 81, 18))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.C2_M1 = QtGui.QComboBox(self.C2)
        self.C2_M1.setGeometry(QtCore.QRect(165, 5, 113, 26))
        self.C2_M1.setObjectName(_fromUtf8("C2_M1"))
        self.C2_M1.addItem(_fromUtf8(""))
        self.C2_M1.addItem(_fromUtf8(""))
        self.C2_M1.addItem(_fromUtf8(""))
        self.C2_M1.addItem(_fromUtf8(""))
        self.C2_M1.addItem(_fromUtf8(""))
        self.label_34 = QtGui.QLabel(self.C2)
        self.label_34.setGeometry(QtCore.QRect(10, 45, 81, 18))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.C2_ID2 = QtGui.QComboBox(self.C2)
        self.C2_ID2.setGeometry(QtCore.QRect(83, 40, 78, 26))
        self.C2_ID2.setObjectName(_fromUtf8("C2_ID2"))
        self.C2_M2 = QtGui.QComboBox(self.C2)
        self.C2_M2.setGeometry(QtCore.QRect(165, 40, 113, 26))
        self.C2_M2.setObjectName(_fromUtf8("C2_M2"))
        self.C2_M2.addItem(_fromUtf8(""))
        self.C2_M2.addItem(_fromUtf8(""))
        self.C2_M2.addItem(_fromUtf8(""))
        self.C2_M2.addItem(_fromUtf8(""))
        self.C2_M2.addItem(_fromUtf8(""))
        self.C2_trigmode = QtGui.QComboBox(self.C2)
        self.C2_trigmode.setGeometry(QtCore.QRect(172, 85, 106, 26))
        self.C2_trigmode.setObjectName(_fromUtf8("C2_trigmode"))
        self.C2_trigmode.addItem(_fromUtf8(""))
        self.C2_trigmode.addItem(_fromUtf8(""))
        self.C2_trigmode.addItem(_fromUtf8(""))
        self.label_35 = QtGui.QLabel(self.C2)
        self.label_35.setGeometry(QtCore.QRect(10, 90, 81, 18))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.C2_trig = QtGui.QComboBox(self.C2)
        self.C2_trig.setGeometry(QtCore.QRect(85, 85, 78, 26))
        self.C2_trig.setObjectName(_fromUtf8("C2_trig"))
        self.channelSelection.addItem(self.C2, _fromUtf8(""))
        self.C3 = QtGui.QWidget()
        self.C3.setObjectName(_fromUtf8("C3"))
        self.C3_M2 = QtGui.QComboBox(self.C3)
        self.C3_M2.setGeometry(QtCore.QRect(50, 35, 225, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C3_M2.setFont(font)
        self.C3_M2.setObjectName(_fromUtf8("C3_M2"))
        self.C3_M2.addItem(_fromUtf8(""))
        self.C3_M2.addItem(_fromUtf8(""))
        self.C3_M2.addItem(_fromUtf8(""))
        self.C3_M2.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.C3)
        self.label_10.setGeometry(QtCore.QRect(9, 35, 30, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.C3_M3 = QtGui.QComboBox(self.C3)
        self.C3_M3.setGeometry(QtCore.QRect(50, 58, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C3_M3.setFont(font)
        self.C3_M3.setObjectName(_fromUtf8("C3_M3"))
        self.C3_M3.addItem(_fromUtf8(""))
        self.C3_M3.addItem(_fromUtf8(""))
        self.C3_M3.addItem(_fromUtf8(""))
        self.C3_M3.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.C3)
        self.label_5.setGeometry(QtCore.QRect(9, 11, 30, 18))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.C3_M1 = QtGui.QComboBox(self.C3)
        self.C3_M1.setGeometry(QtCore.QRect(50, 11, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C3_M1.setFont(font)
        self.C3_M1.setObjectName(_fromUtf8("C3_M1"))
        self.C3_M1.addItem(_fromUtf8(""))
        self.C3_M1.addItem(_fromUtf8(""))
        self.C3_M1.addItem(_fromUtf8(""))
        self.C3_M1.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.C3)
        self.label_13.setGeometry(QtCore.QRect(9, 58, 30, 18))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_32 = QtGui.QLabel(self.C3)
        self.label_32.setGeometry(QtCore.QRect(7, 95, 81, 18))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.C3_trig = QtGui.QComboBox(self.C3)
        self.C3_trig.setGeometry(QtCore.QRect(80, 90, 78, 26))
        self.C3_trig.setObjectName(_fromUtf8("C3_trig"))
        self.C3_trigmode = QtGui.QComboBox(self.C3)
        self.C3_trigmode.setGeometry(QtCore.QRect(162, 90, 113, 26))
        self.C3_trigmode.setObjectName(_fromUtf8("C3_trigmode"))
        self.C3_trigmode.addItem(_fromUtf8(""))
        self.C3_trigmode.addItem(_fromUtf8(""))
        self.C3_trigmode.addItem(_fromUtf8(""))
        self.C3_trigmode.addItem(_fromUtf8(""))
        self.channelSelection.addItem(self.C3, _fromUtf8(""))
        self.C4 = QtGui.QWidget()
        self.C4.setGeometry(QtCore.QRect(0, 0, 281, 122))
        self.C4.setObjectName(_fromUtf8("C4"))
        self.C4_M4 = QtGui.QComboBox(self.C4)
        self.C4_M4.setGeometry(QtCore.QRect(50, 71, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C4_M4.setFont(font)
        self.C4_M4.setObjectName(_fromUtf8("C4_M4"))
        self.C4_M4.addItem(_fromUtf8(""))
        self.C4_M4.addItem(_fromUtf8(""))
        self.C4_M4.addItem(_fromUtf8(""))
        self.C4_M4.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.C4)
        self.label_11.setGeometry(QtCore.QRect(9, 47, 30, 18))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.C4_M1 = QtGui.QComboBox(self.C4)
        self.C4_M1.setGeometry(QtCore.QRect(50, 0, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C4_M1.setFont(font)
        self.C4_M1.setObjectName(_fromUtf8("C4_M1"))
        self.C4_M1.addItem(_fromUtf8(""))
        self.C4_M1.addItem(_fromUtf8(""))
        self.C4_M1.addItem(_fromUtf8(""))
        self.C4_M1.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.C4)
        self.label_12.setGeometry(QtCore.QRect(9, 71, 30, 18))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.C4_M3 = QtGui.QComboBox(self.C4)
        self.C4_M3.setGeometry(QtCore.QRect(50, 47, 225, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C4_M3.setFont(font)
        self.C4_M3.setObjectName(_fromUtf8("C4_M3"))
        self.C4_M3.addItem(_fromUtf8(""))
        self.C4_M3.addItem(_fromUtf8(""))
        self.C4_M3.addItem(_fromUtf8(""))
        self.C4_M3.addItem(_fromUtf8(""))
        self.C4_M2 = QtGui.QComboBox(self.C4)
        self.C4_M2.setGeometry(QtCore.QRect(50, 24, 225, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.C4_M2.setFont(font)
        self.C4_M2.setObjectName(_fromUtf8("C4_M2"))
        self.C4_M2.addItem(_fromUtf8(""))
        self.C4_M2.addItem(_fromUtf8(""))
        self.C4_M2.addItem(_fromUtf8(""))
        self.C4_M2.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.C4)
        self.label_4.setGeometry(QtCore.QRect(9, 0, 30, 18))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_9 = QtGui.QLabel(self.C4)
        self.label_9.setGeometry(QtCore.QRect(9, 24, 30, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.FourChanTrig = QtGui.QCheckBox(self.C4)
        self.FourChanTrig.setGeometry(QtCore.QRect(10, 95, 256, 26))
        self.FourChanTrig.setChecked(True)
        self.FourChanTrig.setObjectName(_fromUtf8("FourChanTrig"))
        self.channelSelection.addItem(self.C4, _fromUtf8(""))
        self.line = QtGui.QFrame(self.frame_12)
        self.line.setGeometry(QtCore.QRect(12, 310, 276, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.splitter)
        self.frame_9 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 17))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 34))
        self.frame_9.setBaseSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.message_label = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_label.sizePolicy().hasHeightForWidth())
        self.message_label.setSizePolicy(sizePolicy)
        self.message_label.setMinimumSize(QtCore.QSize(0, 30))
        self.message_label.setBaseSize(QtCore.QSize(0, 17))
        self.message_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.message_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.message_label.setWordWrap(True)
        self.message_label.setObjectName(_fromUtf8("message_label"))
        self.horizontalLayout.addWidget(self.message_label)
        self.coord_label = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coord_label.sizePolicy().hasHeightForWidth())
        self.coord_label.setSizePolicy(sizePolicy)
        self.coord_label.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.coord_label.setFont(font)
        self.coord_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coord_label.setObjectName(_fromUtf8("coord_label"))
        self.horizontalLayout.addWidget(self.coord_label)
        self.freezeButton = QtGui.QCheckBox(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freezeButton.sizePolicy().hasHeightForWidth())
        self.freezeButton.setSizePolicy(sizePolicy)
        self.freezeButton.setMaximumSize(QtCore.QSize(100, 10))
        self.freezeButton.setObjectName(_fromUtf8("freezeButton"))
        self.horizontalLayout.addWidget(self.freezeButton)
        self.pushButton_4 = QtGui.QPushButton(self.frame_9)
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frame_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))

        self.retranslateUi(MainWindow)
        self.edge2edge.setCurrentIndex(1)
        self.edge1Count.setCurrentIndex(0)
        self.channelSelection.setCurrentIndex(0)
        self.C1_chanmode.setCurrentIndex(1)
        self.C1_trigmode.setCurrentIndex(0)
        self.C2_M1.setCurrentIndex(1)
        self.C2_M2.setCurrentIndex(1)
        self.C2_trigmode.setCurrentIndex(0)
        self.C3_M2.setCurrentIndex(1)
        self.C3_M3.setCurrentIndex(1)
        self.C3_M1.setCurrentIndex(1)
        self.C3_trigmode.setCurrentIndex(0)
        self.C4_M4.setCurrentIndex(1)
        self.C4_M1.setCurrentIndex(1)
        self.C4_M3.setCurrentIndex(1)
        self.C4_M2.setCurrentIndex(1)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.measure_interval)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.capture)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.showData)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.plotData)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.saveData)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Test and Measurement Suite", None))
        self.frame_12.setProperty("class", _translate("MainWindow", "PeripheralCollection", None))
        self.frame_7.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.timeoutBox.setSuffix(_translate("MainWindow", "mS", None))
        self.pushButton_6.setText(_translate("MainWindow", "Measure >", None))
        self.label.setText(_translate("MainWindow", "Timeout:", None))
        self.edge2edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.edge2edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.edge2edge.setItemText(2, _translate("MainWindow", "four rising edges", None))
        self.label_56.setText(_translate("MainWindow", "TIME INTERVAL MEASUREMENT", None))
        self.label_16.setText(_translate("MainWindow", "1", None))
        self.edge1edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.edge1edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.edge1edge.setItemText(2, _translate("MainWindow", "four rising edges", None))
        self.label_17.setText(_translate("MainWindow", "2", None))
        self.edge1Count.setItemText(0, _translate("MainWindow", "1", None))
        self.edge1Count.setItemText(1, _translate("MainWindow", "2", None))
        self.edge1Count.setItemText(2, _translate("MainWindow", "3", None))
        self.edge1Count.setItemText(3, _translate("MainWindow", "4", None))
        self.edge2Count.setItemText(0, _translate("MainWindow", "1", None))
        self.edge2Count.setItemText(1, _translate("MainWindow", "2", None))
        self.edge2Count.setItemText(2, _translate("MainWindow", "3", None))
        self.edge2Count.setItemText(3, _translate("MainWindow", "4", None))
        self.pushButton.setText(_translate("MainWindow", "Start", None))
        self.progressBar.setFormat(_translate("MainWindow", "%v", None))
        self.pushButton_2.setText(_translate("MainWindow", "Plot Data", None))
        self.pushButton_3.setText(_translate("MainWindow", "Raw Data", None))
        self.label_28.setText(_translate("MainWindow", "Input Channel", None))
        self.C1_chanmode.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C1_chanmode.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C1_chanmode.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C1_chanmode.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.C1_chanmode.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_29.setText(_translate("MainWindow", "Edges to Record :", None))
        self.label_31.setText(_translate("MainWindow", "trigger ", None))
        self.C1_trigmode.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C1_trigmode.setItemText(1, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C1_trigmode.setItemText(2, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.C1_trigmode.setItemText(3, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.channelSelection.setItemText(self.channelSelection.indexOf(self.C1), _translate("MainWindow", "Single Channel Mode", None))
        self.label_33.setText(_translate("MainWindow", "Channel 1", None))
        self.C2_M1.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C2_M1.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C2_M1.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C2_M1.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.C2_M1.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.label_34.setText(_translate("MainWindow", "Channel 2", None))
        self.C2_M2.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C2_M2.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C2_M2.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C2_M2.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.C2_M2.setItemText(4, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.C2_trigmode.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C2_trigmode.setItemText(1, _translate("MainWindow", "FALLING EDGE", None))
        self.C2_trigmode.setItemText(2, _translate("MainWindow", "RISING EDGE", None))
        self.label_35.setText(_translate("MainWindow", "trigger ", None))
        self.channelSelection.setItemText(self.channelSelection.indexOf(self.C2), _translate("MainWindow", "Two Channel Mode", None))
        self.C3_M2.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C3_M2.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C3_M2.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C3_M2.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.label_10.setText(_translate("MainWindow", "ID2 :", None))
        self.C3_M3.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C3_M3.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C3_M3.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C3_M3.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.label_5.setText(_translate("MainWindow", "ID1 :", None))
        self.C3_M1.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C3_M1.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C3_M1.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C3_M1.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.label_13.setText(_translate("MainWindow", "ID3 :", None))
        self.label_32.setText(_translate("MainWindow", "trigger ", None))
        self.C3_trigmode.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C3_trigmode.setItemText(1, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C3_trigmode.setItemText(2, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.C3_trigmode.setItemText(3, _translate("MainWindow", "EVERY FOUR RISING EDGES", None))
        self.channelSelection.setItemText(self.channelSelection.indexOf(self.C3), _translate("MainWindow", "Three Channel Mode", None))
        self.C4_M4.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C4_M4.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C4_M4.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C4_M4.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.label_11.setText(_translate("MainWindow", "ID3 :", None))
        self.C4_M1.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C4_M1.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C4_M1.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C4_M1.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.label_12.setText(_translate("MainWindow", "ID4 :", None))
        self.C4_M3.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C4_M3.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C4_M3.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C4_M3.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.C4_M2.setItemText(0, _translate("MainWindow", "DISABLED", None))
        self.C4_M2.setItemText(1, _translate("MainWindow", "EVERY EDGE", None))
        self.C4_M2.setItemText(2, _translate("MainWindow", "FALLING EDGES ONLY", None))
        self.C4_M2.setItemText(3, _translate("MainWindow", "RISING EDGES ONLY", None))
        self.label_4.setText(_translate("MainWindow", "ID1 :", None))
        self.label_9.setText(_translate("MainWindow", "ID2 :", None))
        self.FourChanTrig.setText(_translate("MainWindow", "Trigger on ID1", None))
        self.channelSelection.setItemText(self.channelSelection.indexOf(self.C4), _translate("MainWindow", "Four Channel Mode", None))
        self.message_label.setText(_translate("MainWindow", "Msg:", None))
        self.coord_label.setText(_translate("MainWindow", "TextLabel", None))
        self.freezeButton.setText(_translate("MainWindow", "FREEZE", None))
        self.pushButton_4.setText(_translate("MainWindow", "Save Data", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as", None))

