# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'psl_res/GUI/B_ELECTRONICS/C_COMMUNICATION/templates/ampMod.ui'
#
# Created: Mon Jul 18 22:55:10 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(932, 550)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pixmaps/cubeview48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.plot_area_frame = QtGui.QFrame(self.splitter)
        self.plot_area_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_area_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_area_frame.setObjectName(_fromUtf8("plot_area_frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.plot_area_frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.plot_area_frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 620, 487))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.plot_area = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.plot_area.setSpacing(0)
        self.plot_area.setMargin(0)
        self.plot_area.setObjectName(_fromUtf8("plot_area"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.frame_4 = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(2, 2, 3, 2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setMargin(5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.frame = QtGui.QFrame(self.frame_4)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.WidgetLayout = QtGui.QHBoxLayout(self.frame)
        self.WidgetLayout.setObjectName(_fromUtf8("WidgetLayout"))
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_11 = QtGui.QFrame(self.frame_4)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 115))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.CH1_LABEL = QtGui.QLabel(self.frame_11)
        self.CH1_LABEL.setGeometry(QtCore.QRect(20, 10, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CH1_LABEL.setFont(font)
        self.CH1_LABEL.setObjectName(_fromUtf8("CH1_LABEL"))
        self.CH2_LABEL = QtGui.QLabel(self.frame_11)
        self.CH2_LABEL.setGeometry(QtCore.QRect(20, 50, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CH2_LABEL.setFont(font)
        self.CH2_LABEL.setObjectName(_fromUtf8("CH2_LABEL"))
        self.CH1GainBox = QtGui.QComboBox(self.frame_11)
        self.CH1GainBox.setGeometry(QtCore.QRect(100, 10, 91, 21))
        self.CH1GainBox.setObjectName(_fromUtf8("CH1GainBox"))
        self.CH1GainBox.addItem(_fromUtf8(""))
        self.CH1GainBox.addItem(_fromUtf8(""))
        self.CH1GainBox.addItem(_fromUtf8(""))
        self.CH1GainBox.addItem(_fromUtf8(""))
        self.CH1GainBox.addItem(_fromUtf8(""))
        self.CH1GainBox.addItem(_fromUtf8(""))
        self.CH1GainBox.addItem(_fromUtf8(""))
        self.CH1GainBox.addItem(_fromUtf8(""))
        self.label_30 = QtGui.QLabel(self.frame_11)
        self.label_30.setGeometry(QtCore.QRect(55, 10, 51, 17))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.frame_11)
        self.label_31.setGeometry(QtCore.QRect(55, 50, 51, 17))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.CH1_ENABLE = QtGui.QCheckBox(self.frame_11)
        self.CH1_ENABLE.setGeometry(QtCore.QRect(0, 10, 21, 20))
        self.CH1_ENABLE.setText(_fromUtf8(""))
        self.CH1_ENABLE.setChecked(True)
        self.CH1_ENABLE.setObjectName(_fromUtf8("CH1_ENABLE"))
        self.CH2_ENABLE = QtGui.QCheckBox(self.frame_11)
        self.CH2_ENABLE.setGeometry(QtCore.QRect(0, 50, 21, 20))
        self.CH2_ENABLE.setText(_fromUtf8(""))
        self.CH2_ENABLE.setObjectName(_fromUtf8("CH2_ENABLE"))
        self.CH2GainBox = QtGui.QComboBox(self.frame_11)
        self.CH2GainBox.setGeometry(QtCore.QRect(100, 50, 91, 21))
        self.CH2GainBox.setObjectName(_fromUtf8("CH2GainBox"))
        self.CH2GainBox.addItem(_fromUtf8(""))
        self.CH2GainBox.addItem(_fromUtf8(""))
        self.CH2GainBox.addItem(_fromUtf8(""))
        self.CH2GainBox.addItem(_fromUtf8(""))
        self.CH2GainBox.addItem(_fromUtf8(""))
        self.CH2GainBox.addItem(_fromUtf8(""))
        self.CH2GainBox.addItem(_fromUtf8(""))
        self.CH2GainBox.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_5 = QtGui.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_2 = QtGui.QFrame(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(118, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_49 = QtGui.QLabel(self.frame_2)
        self.label_49.setGeometry(QtCore.QRect(5, 5, 66, 19))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.time_label = QtGui.QLabel(self.frame_2)
        self.time_label.setGeometry(QtCore.QRect(0, 86, 116, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.time_label.setFont(font)
        self.time_label.setText(_fromUtf8(""))
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName(_fromUtf8("time_label"))
        self.dial = QtGui.QDial(self.frame_2)
        self.dial.setGeometry(QtCore.QRect(20, 10, 81, 91))
        self.dial.setMaximum(9)
        self.dial.setPageStep(1)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.trigger_frame = QtGui.QFrame(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trigger_frame.sizePolicy().hasHeightForWidth())
        self.trigger_frame.setSizePolicy(sizePolicy)
        self.trigger_frame.setMinimumSize(QtCore.QSize(150, 110))
        self.trigger_frame.setMaximumSize(QtCore.QSize(16777215, 110))
        self.trigger_frame.setStyleSheet(_fromUtf8("QFrame{background-color: rgba(0, 175, 0, 50);}"))
        self.trigger_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.trigger_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.trigger_frame.setObjectName(_fromUtf8("trigger_frame"))
        self.trigger_level_label = QtGui.QLabel(self.trigger_frame)
        self.trigger_level_label.setGeometry(QtCore.QRect(0, 85, 171, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.trigger_level_label.setFont(font)
        self.trigger_level_label.setAlignment(QtCore.Qt.AlignCenter)
        self.trigger_level_label.setObjectName(_fromUtf8("trigger_level_label"))
        self.dial_11 = QtGui.QDial(self.trigger_frame)
        self.dial_11.setGeometry(QtCore.QRect(85, 10, 91, 81))
        self.dial_11.setMinimum(0)
        self.dial_11.setMaximum(1000)
        self.dial_11.setProperty("value", 500)
        self.dial_11.setNotchTarget(10.0)
        self.dial_11.setNotchesVisible(False)
        self.dial_11.setObjectName(_fromUtf8("dial_11"))
        self.label_4 = QtGui.QLabel(self.trigger_frame)
        self.label_4.setGeometry(QtCore.QRect(0, 25, 86, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.trigger_select_box = QtGui.QComboBox(self.trigger_frame)
        self.trigger_select_box.setGeometry(QtCore.QRect(0, 50, 86, 27))
        self.trigger_select_box.setStyleSheet(_fromUtf8(""))
        self.trigger_select_box.setIconSize(QtCore.QSize(0, 0))
        self.trigger_select_box.setFrame(True)
        self.trigger_select_box.setObjectName(_fromUtf8("trigger_select_box"))
        self.trigger_select_box.addItem(_fromUtf8(""))
        self.trigger_select_box.addItem(_fromUtf8(""))
        self.triggerBox = QtGui.QCheckBox(self.trigger_frame)
        self.triggerBox.setGeometry(QtCore.QRect(0, 0, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.triggerBox.setFont(font)
        self.triggerBox.setChecked(True)
        self.triggerBox.setObjectName(_fromUtf8("triggerBox"))
        self.horizontalLayout_2.addWidget(self.trigger_frame)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.label_2 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setMargin(5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame_6 = QtGui.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_6.setStyleSheet(_fromUtf8(""))
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.fit_select_box = QtGui.QComboBox(self.frame_6)
        self.fit_select_box.setGeometry(QtCore.QRect(85, 5, 66, 21))
        self.fit_select_box.setObjectName(_fromUtf8("fit_select_box"))
        self.fit_select_box.addItem(_fromUtf8(""))
        self.fit_select_box.addItem(_fromUtf8(""))
        self.fit_select_box.addItem(_fromUtf8(""))
        self.overlay_fit_button = QtGui.QCheckBox(self.frame_6)
        self.overlay_fit_button.setGeometry(QtCore.QRect(215, 5, 76, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.overlay_fit_button.setFont(font)
        self.overlay_fit_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overlay_fit_button.setAutoFillBackground(False)
        self.overlay_fit_button.setIconSize(QtCore.QSize(0, 0))
        self.overlay_fit_button.setObjectName(_fromUtf8("overlay_fit_button"))
        self.fit_select_box_2 = QtGui.QComboBox(self.frame_6)
        self.fit_select_box_2.setGeometry(QtCore.QRect(150, 5, 66, 21))
        self.fit_select_box_2.setObjectName(_fromUtf8("fit_select_box_2"))
        self.fit_select_box_2.addItem(_fromUtf8(""))
        self.fit_select_box_2.addItem(_fromUtf8(""))
        self.fit_select_box_2.addItem(_fromUtf8(""))
        self.fit_type_box = QtGui.QComboBox(self.frame_6)
        self.fit_type_box.setGeometry(QtCore.QRect(0, 5, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fit_type_box.setFont(font)
        self.fit_type_box.setFrame(False)
        self.fit_type_box.setObjectName(_fromUtf8("fit_type_box"))
        self.fit_type_box.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.frame_6)
        spacerItem = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 2)
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_9 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 17))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 34))
        self.frame_9.setBaseSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.message_label = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_label.sizePolicy().hasHeightForWidth())
        self.message_label.setSizePolicy(sizePolicy)
        self.message_label.setBaseSize(QtCore.QSize(0, 17))
        self.message_label.setStyleSheet(_fromUtf8(""))
        self.message_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.message_label.setWordWrap(False)
        self.message_label.setObjectName(_fromUtf8("message_label"))
        self.horizontalLayout.addWidget(self.message_label)
        self.freezeButton = QtGui.QCheckBox(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freezeButton.sizePolicy().hasHeightForWidth())
        self.freezeButton.setSizePolicy(sizePolicy)
        self.freezeButton.setMaximumSize(QtCore.QSize(100, 10))
        self.freezeButton.setObjectName(_fromUtf8("freezeButton"))
        self.horizontalLayout.addWidget(self.freezeButton)
        self.pushButton_2 = QtGui.QPushButton(self.frame_9)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.frame_9)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.frame_9)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 932, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuSaveProfile = QtGui.QMenu(self.menuBar)
        self.menuSaveProfile.setObjectName(_fromUtf8("menuSaveProfile"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSaveProfile = QtGui.QAction(MainWindow)
        self.actionSaveProfile.setObjectName(_fromUtf8("actionSaveProfile"))
        self.actionLoadProfile = QtGui.QAction(MainWindow)
        self.actionLoadProfile.setObjectName(_fromUtf8("actionLoadProfile"))
        self.menuSaveProfile.addAction(self.actionSaveProfile)
        self.menuSaveProfile.addAction(self.actionLoadProfile)
        self.menuBar.addAction(self.menuSaveProfile.menuAction())

        self.retranslateUi(MainWindow)
        self.fit_select_box.setCurrentIndex(2)
        self.fit_select_box_2.setCurrentIndex(2)
        self.fit_type_box.setCurrentIndex(0)
        QtCore.QObject.connect(self.CH1GainBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setGainCH1)
        QtCore.QObject.connect(self.CH2GainBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setGainCH2)
        QtCore.QObject.connect(self.dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setTimeBase)
        QtCore.QObject.connect(self.trigger_select_box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setTriggerChannel)
        QtCore.QObject.connect(self.dial_11, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setTriggerLevel)
        QtCore.QObject.connect(self.actionLoadProfile, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.loadPro)
        QtCore.QObject.connect(self.actionSaveProfile, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.savePro)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.saveFft)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.saveData)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Amplitude Modulation", None))
        self.centralwidget.setProperty("class", _translate("MainWindow", "PeripheralCollection", None))
        self.frame_4.setProperty("class", _translate("MainWindow", "PeripheralCollection", None))
        self.label_3.setText(_translate("MainWindow", "Channel Parameters", None))
        self.frame_11.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.CH1_LABEL.setText(_translate("MainWindow", "CH1", None))
        self.CH2_LABEL.setText(_translate("MainWindow", "CH2", None))
        self.CH1GainBox.setItemText(0, _translate("MainWindow", "+/-16V", None))
        self.CH1GainBox.setItemText(1, _translate("MainWindow", "+/-8V", None))
        self.CH1GainBox.setItemText(2, _translate("MainWindow", "+/-4V", None))
        self.CH1GainBox.setItemText(3, _translate("MainWindow", "+/-3V", None))
        self.CH1GainBox.setItemText(4, _translate("MainWindow", "+/-2V", None))
        self.CH1GainBox.setItemText(5, _translate("MainWindow", "+/-1.5V", None))
        self.CH1GainBox.setItemText(6, _translate("MainWindow", "+/-1V", None))
        self.CH1GainBox.setItemText(7, _translate("MainWindow", "+/-500mV", None))
        self.label_30.setText(_translate("MainWindow", "Range", None))
        self.label_31.setText(_translate("MainWindow", "Range", None))
        self.CH2GainBox.setItemText(0, _translate("MainWindow", "+/-16V", None))
        self.CH2GainBox.setItemText(1, _translate("MainWindow", "+/-8V", None))
        self.CH2GainBox.setItemText(2, _translate("MainWindow", "+/-4V", None))
        self.CH2GainBox.setItemText(3, _translate("MainWindow", "+/-3V", None))
        self.CH2GainBox.setItemText(4, _translate("MainWindow", "+/-2V", None))
        self.CH2GainBox.setItemText(5, _translate("MainWindow", "+/-1.5V", None))
        self.CH2GainBox.setItemText(6, _translate("MainWindow", "+/-1V", None))
        self.CH2GainBox.setItemText(7, _translate("MainWindow", "+/-500mV", None))
        self.frame_2.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.label_49.setText(_translate("MainWindow", "TIMEBASE", None))
        self.trigger_frame.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.trigger_level_label.setText(_translate("MainWindow", "Level : 0 mV", None))
        self.dial_11.setToolTip(_translate("MainWindow", "Scroll to change trigger level", None))
        self.label_4.setText(_translate("MainWindow", "Source", None))
        self.trigger_select_box.setItemText(0, _translate("MainWindow", "CH1", None))
        self.trigger_select_box.setItemText(1, _translate("MainWindow", "CH2", None))
        self.triggerBox.setText(_translate("MainWindow", "TRIGGER", None))
        self.label_2.setText(_translate("MainWindow", "Data Analysis", None))
        self.frame_6.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.fit_select_box.setItemText(0, _translate("MainWindow", "CH1", None))
        self.fit_select_box.setItemText(1, _translate("MainWindow", "CH2", None))
        self.fit_select_box.setItemText(2, _translate("MainWindow", "None", None))
        self.overlay_fit_button.setText(_translate("MainWindow", "Overlay", None))
        self.fit_select_box_2.setItemText(0, _translate("MainWindow", "CH1", None))
        self.fit_select_box_2.setItemText(1, _translate("MainWindow", "CH2", None))
        self.fit_select_box_2.setItemText(2, _translate("MainWindow", "None", None))
        self.fit_type_box.setItemText(0, _translate("MainWindow", "SINE FIT", None))
        self.message_label.setText(_translate("MainWindow", "Msg:", None))
        self.freezeButton.setText(_translate("MainWindow", "FREEZE", None))
        self.pushButton_2.setText(_translate("MainWindow", "Save Raw Plots", None))
        self.pushButton_3.setText(_translate("MainWindow", "Save FFt", None))
        self.menuSaveProfile.setTitle(_translate("MainWindow", "Profiles", None))
        self.actionSaveProfile.setText(_translate("MainWindow", "saveProfile", None))
        self.actionLoadProfile.setText(_translate("MainWindow", "LoadProfile", None))
        self.actionLoadProfile.setShortcut(_translate("MainWindow", "Ctrl+O", None))

