export const TOGGLE_READ = 'TOGGLE_READ';

export const TOGGLE_CHANNEL = 'TOGGLE_CHANNEL';
export const CHANGE_CHANNEL_RANGE = 'CHANGE_CHANNEL_RANGE';
export const CHANGE_CHANNEL_MAP = 'CHANGE_CHANNEL_MAP';

export const TOGGLE_TRIGGER = 'TOGGLE_TRIGGER';
export const CHANGE_TRIGGER_VOLTAGE = 'CHANGE_TRIGGER_VOLTAGE';
export const CHANGE_TRIGGER_CHANNEL = 'CHANGE_TRIGGER_CHANNEL';
export const CHANGE_TIME_BASE_INDEX = 'CHANGE_TIME_BASE_INDEX';

export const TOGGLE_FOURIER_TRANSFORM = 'TOGGLE_FOURIER_TRANSFORM';
export const CHANGE_FIT_TYPE = 'CHANGE_FIT_TYPE';
export const CHANGE_FIT_CHANNEL = 'CHANGE_FIT_CHANNEL';

export const TOGGLE_XY_PLOT = 'TOGGLE_XY_PLOT';
export const CHANGE_PLOT_CHANNEL = 'CHANGE_PLOT_CHANNEL';
