# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instrument_layouts/multimeter_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_multimeter_window(object):
    def setupUi(self, multimeter_window):
        multimeter_window.setObjectName("multimeter_window")
        multimeter_window.resize(460, 610)
        multimeter_window.setMinimumSize(QtCore.QSize(460, 610))
        multimeter_window.setMaximumSize(QtCore.QSize(460, 610))
        self.multimeter_layout = QtWidgets.QWidget(multimeter_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multimeter_layout.sizePolicy().hasHeightForWidth())
        self.multimeter_layout.setSizePolicy(sizePolicy)
        self.multimeter_layout.setMinimumSize(QtCore.QSize(460, 610))
        self.multimeter_layout.setMaximumSize(QtCore.QSize(460, 610))
        self.multimeter_layout.setObjectName("multimeter_layout")
        self.lcd_multimeter = QtWidgets.QLCDNumber(self.multimeter_layout)
        self.lcd_multimeter.setGeometry(QtCore.QRect(10, 10, 441, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_multimeter.sizePolicy().hasHeightForWidth())
        self.lcd_multimeter.setSizePolicy(sizePolicy)
        self.lcd_multimeter.setMinimumSize(QtCore.QSize(0, 10))
        self.lcd_multimeter.setMaximumSize(QtCore.QSize(460, 111))
        self.lcd_multimeter.setStyleSheet("QLCDNumber {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.lcd_multimeter.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_multimeter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcd_multimeter.setLineWidth(2)
        self.lcd_multimeter.setMidLineWidth(1)
        self.lcd_multimeter.setSmallDecimalPoint(False)
        self.lcd_multimeter.setDigitCount(10)
        self.lcd_multimeter.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_multimeter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_multimeter.setProperty("value", 0.0)
        self.lcd_multimeter.setProperty("intValue", 0)
        self.lcd_multimeter.setObjectName("lcd_multimeter")
        self.frame = QtWidgets.QFrame(self.multimeter_layout)
        self.frame.setGeometry(QtCore.QRect(10, 100, 441, 481))
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(460, 610))
        self.frame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(237, 212, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dial_multimeter = QtWidgets.QDial(self.frame)
        self.dial_multimeter.setGeometry(QtCore.QRect(90, 50, 271, 291))
        self.dial_multimeter.setMaximum(11)
        self.dial_multimeter.setPageStep(1)
        self.dial_multimeter.setSliderPosition(0)
        self.dial_multimeter.setInvertedAppearance(False)
        self.dial_multimeter.setWrapping(True)
        self.dial_multimeter.setNotchTarget(10.0)
        self.dial_multimeter.setNotchesVisible(True)
        self.dial_multimeter.setObjectName("dial_multimeter")
        self.label_unit_display = QtWidgets.QLabel(self.frame)
        self.label_unit_display.setGeometry(QtCore.QRect(10, 6, 421, 31))
        self.label_unit_display.setMaximumSize(QtCore.QSize(460, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_unit_display.setFont(font)
        self.label_unit_display.setText("")
        self.label_unit_display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_unit_display.setObjectName("label_unit_display")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 410, 421, 63))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(460, 195))
        self.groupBox.setObjectName("groupBox")
        self.slider_update_interval = QtWidgets.QSlider(self.groupBox)
        self.slider_update_interval.setGeometry(QtCore.QRect(10, 30, 331, 23))
        self.slider_update_interval.setMaximum(99)
        self.slider_update_interval.setOrientation(QtCore.Qt.Horizontal)
        self.slider_update_interval.setInvertedAppearance(False)
        self.slider_update_interval.setInvertedControls(False)
        self.slider_update_interval.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_update_interval.setTickInterval(1)
        self.slider_update_interval.setObjectName("slider_update_interval")
        self.label_update_interval = QtWidgets.QLabel(self.groupBox)
        self.label_update_interval.setGeometry(QtCore.QRect(343, 27, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_update_interval.setFont(font)
        self.label_update_interval.setAlignment(QtCore.Qt.AlignCenter)
        self.label_update_interval.setObjectName("label_update_interval")
        self.l_off = QtWidgets.QLabel(self.frame)
        self.l_off.setGeometry(QtCore.QRect(201, 335, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_off.setFont(font)
        self.l_off.setTextFormat(QtCore.Qt.AutoText)
        self.l_off.setAlignment(QtCore.Qt.AlignCenter)
        self.l_off.setObjectName("l_off")
        self.l_ch1 = QtWidgets.QLabel(self.frame)
        self.l_ch1.setGeometry(QtCore.QRect(118, 309, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_ch1.setFont(font)
        self.l_ch1.setTextFormat(QtCore.Qt.AutoText)
        self.l_ch1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ch1.setObjectName("l_ch1")
        self.l_ch2 = QtWidgets.QLabel(self.frame)
        self.l_ch2.setGeometry(QtCore.QRect(61, 248, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_ch2.setFont(font)
        self.l_ch2.setTextFormat(QtCore.Qt.AutoText)
        self.l_ch2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ch2.setObjectName("l_ch2")
        self.l_ch3 = QtWidgets.QLabel(self.frame)
        self.l_ch3.setGeometry(QtCore.QRect(53, 165, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_ch3.setFont(font)
        self.l_ch3.setTextFormat(QtCore.Qt.AutoText)
        self.l_ch3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ch3.setObjectName("l_ch3")
        self.l_vol = QtWidgets.QLabel(self.frame)
        self.l_vol.setGeometry(QtCore.QRect(81, 87, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_vol.setFont(font)
        self.l_vol.setTextFormat(QtCore.Qt.AutoText)
        self.l_vol.setAlignment(QtCore.Qt.AlignCenter)
        self.l_vol.setObjectName("l_vol")
        self.l_la4 = QtWidgets.QLabel(self.frame)
        self.l_la4.setGeometry(QtCore.QRect(283, 311, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_la4.setFont(font)
        self.l_la4.setTextFormat(QtCore.Qt.AutoText)
        self.l_la4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_la4.setObjectName("l_la4")
        self.l_la3 = QtWidgets.QLabel(self.frame)
        self.l_la3.setGeometry(QtCore.QRect(331, 245, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_la3.setFont(font)
        self.l_la3.setTextFormat(QtCore.Qt.AutoText)
        self.l_la3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_la3.setObjectName("l_la3")
        self.l_la2 = QtWidgets.QLabel(self.frame)
        self.l_la2.setGeometry(QtCore.QRect(344, 165, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_la2.setFont(font)
        self.l_la2.setTextFormat(QtCore.Qt.AutoText)
        self.l_la2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_la2.setObjectName("l_la2")
        self.l_la1 = QtWidgets.QLabel(self.frame)
        self.l_la1.setGeometry(QtCore.QRect(320, 90, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_la1.setFont(font)
        self.l_la1.setTextFormat(QtCore.Qt.AutoText)
        self.l_la1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_la1.setObjectName("l_la1")
        self.l_cap = QtWidgets.QLabel(self.frame)
        self.l_cap.setGeometry(QtCore.QRect(241, 47, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_cap.setFont(font)
        self.l_cap.setTextFormat(QtCore.Qt.AutoText)
        self.l_cap.setAlignment(QtCore.Qt.AlignCenter)
        self.l_cap.setObjectName("l_cap")
        self.l_ohm = QtWidgets.QLabel(self.frame)
        self.l_ohm.setGeometry(QtCore.QRect(159, 46, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l_ohm.setFont(font)
        self.l_ohm.setTextFormat(QtCore.Qt.AutoText)
        self.l_ohm.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ohm.setObjectName("l_ohm")
        multimeter_window.setCentralWidget(self.multimeter_layout)
        self.statusbar = QtWidgets.QStatusBar(multimeter_window)
        self.statusbar.setObjectName("statusbar")
        multimeter_window.setStatusBar(self.statusbar)

        self.retranslateUi(multimeter_window)
        self.slider_update_interval.valueChanged['int'].connect(multimeter_window.update_refrest_rate)
        self.dial_multimeter.valueChanged['int'].connect(multimeter_window.read_knob)
        QtCore.QMetaObject.connectSlotsByName(multimeter_window)

    def retranslateUi(self, multimeter_window):
        _translate = QtCore.QCoreApplication.translate
        multimeter_window.setWindowTitle(_translate("multimeter_window", "PSLab Multimeter"))
        self.groupBox.setToolTip(_translate("multimeter_window", "Rate at which multimeter reads values from device"))
        self.groupBox.setTitle(_translate("multimeter_window", "Update Speed for Readings"))
        self.label_update_interval.setText(_translate("multimeter_window", "Every 0.01\n"
"seconds"))
        self.l_off.setText(_translate("multimeter_window", "OFF"))
        self.l_ch1.setText(_translate("multimeter_window", "CH1"))
        self.l_ch2.setText(_translate("multimeter_window", "CH2"))
        self.l_ch3.setText(_translate("multimeter_window", "CH3"))
        self.l_vol.setText(_translate("multimeter_window", "VOL"))
        self.l_la4.setText(_translate("multimeter_window", "LA4"))
        self.l_la3.setText(_translate("multimeter_window", "LA3"))
        self.l_la2.setText(_translate("multimeter_window", "LA2"))
        self.l_la1.setText(_translate("multimeter_window", "LA1"))
        self.l_cap.setText(_translate("multimeter_window", "CAP"))
        self.l_ohm.setText(_translate("multimeter_window", "Ω"))


