# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powersource_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_powersource_window(object):
    def setupUi(self, powersource_window):
        powersource_window.setObjectName("powersource_window")
        powersource_window.setEnabled(True)
        powersource_window.resize(460, 610)
        powersource_window.setMinimumSize(QtCore.QSize(460, 610))
        powersource_window.setMaximumSize(QtCore.QSize(460, 610))
        self.centralwidget = QtWidgets.QWidget(powersource_window)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 201, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox.setGeometry(QtCore.QRect(10, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox.setPrefix("")
        self.doubleSpinBox.setMinimum(-5.0)
        self.doubleSpinBox.setMaximum(5.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalSlider = QtWidgets.QSlider(self.frame)
        self.verticalSlider.setGeometry(QtCore.QRect(170, 40, 20, 211))
        self.verticalSlider.setAcceptDrops(False)
        self.verticalSlider.setMaximum(1000)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider.setTickInterval(14)
        self.verticalSlider.setObjectName("verticalSlider")
        self.dial = QtWidgets.QDial(self.frame)
        self.dial.setGeometry(QtCore.QRect(10, 40, 151, 151))
        self.dial.setMaximum(1000)
        self.dial.setSingleStep(1)
        self.dial.setPageStep(1)
        self.dial.setProperty("value", 500)
        self.dial.setNotchTarget(10.0)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(240, 20, 201, 261))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(10, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox_2.setPrefix("")
        self.doubleSpinBox_2.setMinimum(-5.0)
        self.doubleSpinBox_2.setMaximum(5.0)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.verticalSlider_2 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_2.setGeometry(QtCore.QRect(170, 40, 20, 211))
        self.verticalSlider_2.setAcceptDrops(False)
        self.verticalSlider_2.setMaximum(1000)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_2.setTickInterval(14)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.dial_2 = QtWidgets.QDial(self.frame_2)
        self.dial_2.setGeometry(QtCore.QRect(10, 40, 151, 151))
        self.dial_2.setMaximum(1000)
        self.dial_2.setSingleStep(1)
        self.dial_2.setPageStep(1)
        self.dial_2.setProperty("value", 500)
        self.dial_2.setNotchTarget(10.0)
        self.dial_2.setNotchesVisible(True)
        self.dial_2.setObjectName("dial_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(240, 300, 201, 261))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(10, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox_3.setPrefix("")
        self.doubleSpinBox_3.setDecimals(0)
        self.doubleSpinBox_3.setMinimum(0.0)
        self.doubleSpinBox_3.setMaximum(30.0)
        self.doubleSpinBox_3.setSingleStep(1.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalSlider_3 = QtWidgets.QSlider(self.frame_3)
        self.verticalSlider_3.setGeometry(QtCore.QRect(170, 40, 20, 211))
        self.verticalSlider_3.setAcceptDrops(False)
        self.verticalSlider_3.setMaximum(30)
        self.verticalSlider_3.setPageStep(1)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_3.setTickInterval(1)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.dial_3 = QtWidgets.QDial(self.frame_3)
        self.dial_3.setGeometry(QtCore.QRect(10, 40, 151, 151))
        self.dial_3.setMaximum(30)
        self.dial_3.setSingleStep(1)
        self.dial_3.setPageStep(1)
        self.dial_3.setProperty("value", 0)
        self.dial_3.setNotchTarget(1.0)
        self.dial_3.setNotchesVisible(True)
        self.dial_3.setObjectName("dial_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 300, 201, 261))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(10, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.doubleSpinBox_4.setFont(font)
        self.doubleSpinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox_4.setPrefix("")
        self.doubleSpinBox_4.setMinimum(-5.0)
        self.doubleSpinBox_4.setMaximum(5.0)
        self.doubleSpinBox_4.setSingleStep(0.01)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.verticalSlider_4 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_4.setGeometry(QtCore.QRect(170, 40, 20, 211))
        self.verticalSlider_4.setAcceptDrops(False)
        self.verticalSlider_4.setMaximum(1000)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_4.setTickInterval(14)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.dial_4 = QtWidgets.QDial(self.frame_4)
        self.dial_4.setGeometry(QtCore.QRect(10, 40, 151, 151))
        self.dial_4.setMaximum(1000)
        self.dial_4.setSingleStep(1)
        self.dial_4.setPageStep(1)
        self.dial_4.setProperty("value", 500)
        self.dial_4.setNotchTarget(10.0)
        self.dial_4.setNotchesVisible(True)
        self.dial_4.setObjectName("dial_4")
        powersource_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(powersource_window)
        self.statusbar.setObjectName("statusbar")
        powersource_window.setStatusBar(self.statusbar)

        self.retranslateUi(powersource_window)
        QtCore.QMetaObject.connectSlotsByName(powersource_window)

    def retranslateUi(self, powersource_window):
        _translate = QtCore.QCoreApplication.translate
        powersource_window.setWindowTitle(_translate("powersource_window", "PSLab Power Source"))
        self.label.setText(_translate("powersource_window", "Voltage Source 1"))
        self.doubleSpinBox.setSuffix(_translate("powersource_window", " V"))
        self.label_2.setText(_translate("powersource_window", "Voltage Source 2"))
        self.doubleSpinBox_2.setSuffix(_translate("powersource_window", " V"))
        self.label_3.setText(_translate("powersource_window", "Current Source"))
        self.doubleSpinBox_3.setSuffix(_translate("powersource_window", " mA"))
        self.label_4.setText(_translate("powersource_window", "Voltage Source 3"))
        self.doubleSpinBox_4.setSuffix(_translate("powersource_window", " V"))


