# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powersource_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_powersource_window(object):
    def setupUi(self, powersource_window):
        powersource_window.setObjectName("powersource_window")
        powersource_window.setEnabled(True)
        powersource_window.resize(460, 610)
        powersource_window.setMinimumSize(QtCore.QSize(460, 610))
        powersource_window.setMaximumSize(QtCore.QSize(460, 610))
        self.centralwidget = QtWidgets.QWidget(powersource_window)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_pv1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_pv1.setGeometry(QtCore.QRect(20, 20, 201, 261))
        self.frame_pv1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pv1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pv1.setObjectName("frame_pv1")
        self.label_pv1 = QtWidgets.QLabel(self.frame_pv1)
        self.label_pv1.setEnabled(True)
        self.label_pv1.setGeometry(QtCore.QRect(0, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_pv1.setFont(font)
        self.label_pv1.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_pv1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_pv1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pv1.setObjectName("label_pv1")
        self.spinner_pv1 = QtWidgets.QDoubleSpinBox(self.frame_pv1)
        self.spinner_pv1.setGeometry(QtCore.QRect(10, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinner_pv1.setFont(font)
        self.spinner_pv1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinner_pv1.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinner_pv1.setPrefix("")
        self.spinner_pv1.setMinimum(-5.0)
        self.spinner_pv1.setMaximum(5.0)
        self.spinner_pv1.setSingleStep(0.01)
        self.spinner_pv1.setObjectName("spinner_pv1")
        self.slider_pv1 = QtWidgets.QSlider(self.frame_pv1)
        self.slider_pv1.setGeometry(QtCore.QRect(170, 40, 20, 211))
        self.slider_pv1.setAcceptDrops(False)
        self.slider_pv1.setMaximum(1000)
        self.slider_pv1.setSliderPosition(500)
        self.slider_pv1.setOrientation(QtCore.Qt.Vertical)
        self.slider_pv1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_pv1.setTickInterval(14)
        self.slider_pv1.setObjectName("slider_pv1")
        self.dial_pv1 = QtWidgets.QDial(self.frame_pv1)
        self.dial_pv1.setGeometry(QtCore.QRect(10, 40, 151, 151))
        self.dial_pv1.setMaximum(1000)
        self.dial_pv1.setSingleStep(1)
        self.dial_pv1.setPageStep(1)
        self.dial_pv1.setProperty("value", 500)
        self.dial_pv1.setNotchTarget(10.0)
        self.dial_pv1.setNotchesVisible(True)
        self.dial_pv1.setObjectName("dial_pv1")
        self.frame_pv2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_pv2.setGeometry(QtCore.QRect(240, 20, 201, 261))
        self.frame_pv2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pv2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pv2.setObjectName("frame_pv2")
        self.label_pv2 = QtWidgets.QLabel(self.frame_pv2)
        self.label_pv2.setEnabled(True)
        self.label_pv2.setGeometry(QtCore.QRect(0, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_pv2.setFont(font)
        self.label_pv2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_pv2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_pv2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pv2.setObjectName("label_pv2")
        self.spinner_pv2 = QtWidgets.QDoubleSpinBox(self.frame_pv2)
        self.spinner_pv2.setGeometry(QtCore.QRect(10, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinner_pv2.setFont(font)
        self.spinner_pv2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinner_pv2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinner_pv2.setPrefix("")
        self.spinner_pv2.setMinimum(-5.0)
        self.spinner_pv2.setMaximum(5.0)
        self.spinner_pv2.setSingleStep(0.01)
        self.spinner_pv2.setObjectName("spinner_pv2")
        self.slider_pv2 = QtWidgets.QSlider(self.frame_pv2)
        self.slider_pv2.setGeometry(QtCore.QRect(170, 40, 20, 211))
        self.slider_pv2.setAcceptDrops(False)
        self.slider_pv2.setMaximum(660)
        self.slider_pv2.setProperty("value", 330)
        self.slider_pv2.setOrientation(QtCore.Qt.Vertical)
        self.slider_pv2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_pv2.setTickInterval(14)
        self.slider_pv2.setObjectName("slider_pv2")
        self.dial_pv2 = QtWidgets.QDial(self.frame_pv2)
        self.dial_pv2.setGeometry(QtCore.QRect(10, 40, 151, 151))
        self.dial_pv2.setMaximum(660)
        self.dial_pv2.setSingleStep(1)
        self.dial_pv2.setPageStep(1)
        self.dial_pv2.setProperty("value", 330)
        self.dial_pv2.setNotchTarget(10.0)
        self.dial_pv2.setNotchesVisible(True)
        self.dial_pv2.setObjectName("dial_pv2")
        self.frame_pcs = QtWidgets.QFrame(self.centralwidget)
        self.frame_pcs.setGeometry(QtCore.QRect(240, 300, 201, 261))
        self.frame_pcs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pcs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pcs.setObjectName("frame_pcs")
        self.label_pcs = QtWidgets.QLabel(self.frame_pcs)
        self.label_pcs.setEnabled(True)
        self.label_pcs.setGeometry(QtCore.QRect(0, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_pcs.setFont(font)
        self.label_pcs.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_pcs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_pcs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pcs.setObjectName("label_pcs")
        self.spinner_pcs = QtWidgets.QDoubleSpinBox(self.frame_pcs)
        self.spinner_pcs.setGeometry(QtCore.QRect(10, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinner_pcs.setFont(font)
        self.spinner_pcs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinner_pcs.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinner_pcs.setPrefix("")
        self.spinner_pcs.setDecimals(0)
        self.spinner_pcs.setMinimum(0.0)
        self.spinner_pcs.setMaximum(30.0)
        self.spinner_pcs.setSingleStep(1.0)
        self.spinner_pcs.setObjectName("spinner_pcs")
        self.slider_pcs = QtWidgets.QSlider(self.frame_pcs)
        self.slider_pcs.setGeometry(QtCore.QRect(170, 40, 20, 211))
        self.slider_pcs.setAcceptDrops(False)
        self.slider_pcs.setMaximum(30)
        self.slider_pcs.setPageStep(1)
        self.slider_pcs.setOrientation(QtCore.Qt.Vertical)
        self.slider_pcs.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_pcs.setTickInterval(1)
        self.slider_pcs.setObjectName("slider_pcs")
        self.dial_pcs = QtWidgets.QDial(self.frame_pcs)
        self.dial_pcs.setGeometry(QtCore.QRect(10, 40, 151, 151))
        self.dial_pcs.setMaximum(30)
        self.dial_pcs.setSingleStep(1)
        self.dial_pcs.setPageStep(1)
        self.dial_pcs.setProperty("value", 0)
        self.dial_pcs.setNotchTarget(-0.5)
        self.dial_pcs.setNotchesVisible(True)
        self.dial_pcs.setObjectName("dial_pcs")
        self.frame_pv3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_pv3.setGeometry(QtCore.QRect(20, 300, 201, 261))
        self.frame_pv3.setStyleSheet("")
        self.frame_pv3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pv3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pv3.setObjectName("frame_pv3")
        self.label_pv3 = QtWidgets.QLabel(self.frame_pv3)
        self.label_pv3.setEnabled(True)
        self.label_pv3.setGeometry(QtCore.QRect(0, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_pv3.setFont(font)
        self.label_pv3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_pv3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_pv3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pv3.setObjectName("label_pv3")
        self.spinner_pv3 = QtWidgets.QDoubleSpinBox(self.frame_pv3)
        self.spinner_pv3.setGeometry(QtCore.QRect(10, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinner_pv3.setFont(font)
        self.spinner_pv3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinner_pv3.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinner_pv3.setPrefix("")
        self.spinner_pv3.setMinimum(-5.0)
        self.spinner_pv3.setMaximum(5.0)
        self.spinner_pv3.setSingleStep(0.01)
        self.spinner_pv3.setObjectName("spinner_pv3")
        self.slider_pv3 = QtWidgets.QSlider(self.frame_pv3)
        self.slider_pv3.setGeometry(QtCore.QRect(170, 40, 20, 211))
        self.slider_pv3.setAcceptDrops(False)
        self.slider_pv3.setMaximum(330)
        self.slider_pv3.setOrientation(QtCore.Qt.Vertical)
        self.slider_pv3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_pv3.setTickInterval(14)
        self.slider_pv3.setObjectName("slider_pv3")
        self.dial_pv3 = QtWidgets.QDial(self.frame_pv3)
        self.dial_pv3.setGeometry(QtCore.QRect(10, 40, 151, 151))
        self.dial_pv3.setMaximum(330)
        self.dial_pv3.setSingleStep(1)
        self.dial_pv3.setPageStep(1)
        self.dial_pv3.setProperty("value", 0)
        self.dial_pv3.setNotchTarget(4.0)
        self.dial_pv3.setNotchesVisible(True)
        self.dial_pv3.setObjectName("dial_pv3")
        powersource_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(powersource_window)
        self.statusbar.setObjectName("statusbar")
        powersource_window.setStatusBar(self.statusbar)

        self.retranslateUi(powersource_window)
        self.dial_pv1.valueChanged['int'].connect(powersource_window.power_dial_changed)
        self.dial_pv2.valueChanged['int'].connect(powersource_window.power_dial_changed)
        self.dial_pcs.valueChanged['int'].connect(powersource_window.power_dial_changed)
        self.dial_pv3.valueChanged['int'].connect(powersource_window.power_dial_changed)
        self.slider_pv1.valueChanged['int'].connect(powersource_window.power_slider_changed)
        self.slider_pv2.valueChanged['int'].connect(powersource_window.power_slider_changed)
        self.slider_pcs.valueChanged['int'].connect(powersource_window.power_slider_changed)
        self.slider_pv3.valueChanged['int'].connect(powersource_window.power_slider_changed)
        self.spinner_pv1.valueChanged['double'].connect(powersource_window.power_spinner_changed)
        self.spinner_pv2.valueChanged['double'].connect(powersource_window.power_spinner_changed)
        self.spinner_pcs.valueChanged['double'].connect(powersource_window.power_spinner_changed)
        self.spinner_pv3.valueChanged['double'].connect(powersource_window.power_spinner_changed)
        self.spinner_pv1.valueChanged['QString'].connect(powersource_window.power_spinner_changed)
        self.spinner_pv2.valueChanged['QString'].connect(powersource_window.power_spinner_changed)
        self.spinner_pcs.valueChanged['QString'].connect(powersource_window.power_spinner_changed)
        self.spinner_pv3.valueChanged['QString'].connect(powersource_window.power_spinner_changed)
        QtCore.QMetaObject.connectSlotsByName(powersource_window)

    def retranslateUi(self, powersource_window):
        _translate = QtCore.QCoreApplication.translate
        powersource_window.setWindowTitle(_translate("powersource_window", "PSLab Power Source"))
        self.label_pv1.setText(_translate("powersource_window", "Voltage Source 1"))
        self.spinner_pv1.setSuffix(_translate("powersource_window", " V"))
        self.label_pv2.setText(_translate("powersource_window", "Voltage Source 2"))
        self.spinner_pv2.setSuffix(_translate("powersource_window", " V"))
        self.label_pcs.setText(_translate("powersource_window", "Current Source"))
        self.spinner_pcs.setSuffix(_translate("powersource_window", " mA"))
        self.label_pv3.setText(_translate("powersource_window", "Voltage Source 3"))
        self.spinner_pv3.setSuffix(_translate("powersource_window", " V"))


