# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pslab_main_window(object):
    def setupUi(self, pslab_main_window):
        pslab_main_window.setObjectName("pslab_main_window")
        pslab_main_window.resize(460, 610)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pslab_main_window.sizePolicy().hasHeightForWidth())
        pslab_main_window.setSizePolicy(sizePolicy)
        pslab_main_window.setMinimumSize(QtCore.QSize(460, 610))
        pslab_main_window.setMaximumSize(QtCore.QSize(460, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/icons/app_logo/pslab_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pslab_main_window.setWindowIcon(icon)
        pslab_main_window.setWindowOpacity(50.0)
        self.app_window = QtWidgets.QWidget(pslab_main_window)
        self.app_window.setObjectName("app_window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.app_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.app_tabs = QtWidgets.QTabWidget(self.app_window)
        self.app_tabs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.app_tabs.setAutoFillBackground(False)
        self.app_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.app_tabs.setIconSize(QtCore.QSize(24, 24))
        self.app_tabs.setElideMode(QtCore.Qt.ElideNone)
        self.app_tabs.setMovable(False)
        self.app_tabs.setTabBarAutoHide(False)
        self.app_tabs.setObjectName("app_tabs")
        self.tab_instruments = QtWidgets.QWidget()
        self.tab_instruments.setObjectName("tab_instruments")
        self.frame_instruments = QtWidgets.QFrame(self.tab_instruments)
        self.frame_instruments.setGeometry(QtCore.QRect(-1, -1, 441, 541))
        self.frame_instruments.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_instruments.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_instruments.setLineWidth(1)
        self.frame_instruments.setObjectName("frame_instruments")
        self.scroll_instruments = QtWidgets.QScrollArea(self.frame_instruments)
        self.scroll_instruments.setGeometry(QtCore.QRect(0, -1, 441, 541))
        self.scroll_instruments.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_instruments.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scroll_instruments.setWidgetResizable(True)
        self.scroll_instruments.setObjectName("scroll_instruments")
        self.scroll_area_instruments = QtWidgets.QWidget()
        self.scroll_area_instruments.setGeometry(QtCore.QRect(0, 0, 441, 541))
        self.scroll_area_instruments.setObjectName("scroll_area_instruments")
        self.scroll_instruments.setWidget(self.scroll_area_instruments)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../resources/icons/tab_icons/instrument_tab_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.app_tabs.addTab(self.tab_instruments, icon1, "")
        self.tab_guide = QtWidgets.QWidget()
        self.tab_guide.setObjectName("tab_guide")
        self.frame_guide = QtWidgets.QFrame(self.tab_guide)
        self.frame_guide.setGeometry(QtCore.QRect(-1, -1, 441, 541))
        self.frame_guide.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_guide.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_guide.setObjectName("frame_guide")
        self.scroll_guide = QtWidgets.QScrollArea(self.frame_guide)
        self.scroll_guide.setGeometry(QtCore.QRect(-1, -1, 441, 541))
        self.scroll_guide.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_guide.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scroll_guide.setWidgetResizable(True)
        self.scroll_guide.setObjectName("scroll_guide")
        self.scroll_area_guide = QtWidgets.QWidget()
        self.scroll_area_guide.setGeometry(QtCore.QRect(0, 0, 441, 541))
        self.scroll_area_guide.setObjectName("scroll_area_guide")
        self.text_area_guide = QtWidgets.QTextBrowser(self.scroll_area_guide)
        self.text_area_guide.setGeometry(QtCore.QRect(0, 0, 441, 541))
        self.text_area_guide.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_area_guide.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_area_guide.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.text_area_guide.setDocumentTitle("")
        self.text_area_guide.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.text_area_guide.setCursorWidth(1)
        self.text_area_guide.setOpenExternalLinks(True)
        self.text_area_guide.setObjectName("text_area_guide")
        self.scroll_guide.setWidget(self.scroll_area_guide)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../resources/icons/tab_icons/guide_tab_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.app_tabs.addTab(self.tab_guide, icon2, "")
        self.tab_sensors = QtWidgets.QWidget()
        self.tab_sensors.setObjectName("tab_sensors")
        self.frame_sensors = QtWidgets.QFrame(self.tab_sensors)
        self.frame_sensors.setGeometry(QtCore.QRect(-1, -1, 441, 541))
        self.frame_sensors.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sensors.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_sensors.setObjectName("frame_sensors")
        self.scroll_sensors = QtWidgets.QScrollArea(self.frame_sensors)
        self.scroll_sensors.setGeometry(QtCore.QRect(-1, -1, 441, 541))
        self.scroll_sensors.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_sensors.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scroll_sensors.setWidgetResizable(True)
        self.scroll_sensors.setObjectName("scroll_sensors")
        self.scroll_area_sensors = QtWidgets.QWidget()
        self.scroll_area_sensors.setGeometry(QtCore.QRect(0, 0, 441, 541))
        self.scroll_area_sensors.setObjectName("scroll_area_sensors")
        self.scroll_sensors.setWidget(self.scroll_area_sensors)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../resources/icons/tab_icons/sensor_tab_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.app_tabs.addTab(self.tab_sensors, icon3, "")
        self.tab_console = QtWidgets.QWidget()
        self.tab_console.setObjectName("tab_console")
        self.frame_console = QtWidgets.QFrame(self.tab_console)
        self.frame_console.setGeometry(QtCore.QRect(-1, -1, 441, 541))
        self.frame_console.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_console.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_console.setObjectName("frame_console")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../resources/icons/tab_icons/ipython_tab_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.app_tabs.addTab(self.tab_console, icon4, "")
        self.verticalLayout.addWidget(self.app_tabs)
        pslab_main_window.setCentralWidget(self.app_window)
        self.pslab_main_menu = QtWidgets.QMenuBar(pslab_main_window)
        self.pslab_main_menu.setGeometry(QtCore.QRect(0, 0, 460, 25))
        self.pslab_main_menu.setObjectName("pslab_main_menu")
        self.menuDevice = QtWidgets.QMenu(self.pslab_main_menu)
        self.menuDevice.setObjectName("menuDevice")
        self.menuHelp = QtWidgets.QMenu(self.pslab_main_menu)
        self.menuHelp.setTearOffEnabled(False)
        self.menuHelp.setObjectName("menuHelp")
        pslab_main_window.setMenuBar(self.pslab_main_menu)
        self.pslab_status_bar = QtWidgets.QStatusBar(pslab_main_window)
        self.pslab_status_bar.setObjectName("pslab_status_bar")
        pslab_main_window.setStatusBar(self.pslab_status_bar)
        self.action_reconnect = QtWidgets.QAction(pslab_main_window)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../resources/icons/menu_icons/reconnect_menu_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_reconnect.setIcon(icon5)
        self.action_reconnect.setObjectName("action_reconnect")
        self.action_about_device = QtWidgets.QAction(pslab_main_window)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../resources/icons/menu_icons/about_device_menu_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about_device.setIcon(icon6)
        self.action_about_device.setObjectName("action_about_device")
        self.action_test_device = QtWidgets.QAction(pslab_main_window)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../resources/icons/menu_icons/test_device_menu_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_test_device.setIcon(icon7)
        self.action_test_device.setObjectName("action_test_device")
        self.action_pin_Layout = QtWidgets.QAction(pslab_main_window)
        self.action_pin_Layout.setObjectName("action_pin_Layout")
        self.action_datasheet = QtWidgets.QAction(pslab_main_window)
        self.action_datasheet.setObjectName("action_datasheet")
        self.menuDevice.addAction(self.action_reconnect)
        self.menuDevice.addAction(self.action_test_device)
        self.menuDevice.addSeparator()
        self.menuDevice.addAction(self.action_about_device)
        self.menuHelp.addAction(self.action_pin_Layout)
        self.menuHelp.addAction(self.action_datasheet)
        self.pslab_main_menu.addAction(self.menuDevice.menuAction())
        self.pslab_main_menu.addAction(self.menuHelp.menuAction())

        self.retranslateUi(pslab_main_window)
        self.app_tabs.setCurrentIndex(0)
        self.action_reconnect.triggered.connect(pslab_main_window.maction_reconnect_device)
        self.action_test_device.triggered.connect(pslab_main_window.maction_test_device)
        self.action_about_device.triggered.connect(pslab_main_window.maction_about_device)
        self.action_pin_Layout.triggered.connect(pslab_main_window.maction_pinlayout)
        self.action_datasheet.triggered.connect(pslab_main_window.maction_datasheet)
        QtCore.QMetaObject.connectSlotsByName(pslab_main_window)

    def retranslateUi(self, pslab_main_window):
        _translate = QtCore.QCoreApplication.translate
        pslab_main_window.setWindowTitle(_translate("pslab_main_window", "PSLab Desktop App V2.0"))
        self.app_tabs.setTabText(self.app_tabs.indexOf(self.tab_instruments), _translate("pslab_main_window", "Instruments"))
        self.app_tabs.setTabToolTip(self.app_tabs.indexOf(self.tab_instruments), _translate("pslab_main_window", "Instruments provided by PSLab"))
        self.text_area_guide.setHtml(_translate("pslab_main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.text_area_guide.setPlaceholderText(_translate("pslab_main_window", "Guide for the selected instrument will be displayed here..."))
        self.app_tabs.setTabText(self.app_tabs.indexOf(self.tab_guide), _translate("pslab_main_window", "Guide"))
        self.app_tabs.setTabText(self.app_tabs.indexOf(self.tab_sensors), _translate("pslab_main_window", "Sensors"))
        self.app_tabs.setTabText(self.app_tabs.indexOf(self.tab_console), _translate("pslab_main_window", "Console"))
        self.menuDevice.setTitle(_translate("pslab_main_window", "Device"))
        self.menuHelp.setTitle(_translate("pslab_main_window", "Help"))
        self.action_reconnect.setText(_translate("pslab_main_window", "Reconnect"))
        self.action_reconnect.setToolTip(_translate("pslab_main_window", "Reconnect to PSLab device"))
        self.action_reconnect.setShortcut(_translate("pslab_main_window", "Ctrl+Alt+R"))
        self.action_about_device.setText(_translate("pslab_main_window", "About..."))
        self.action_test_device.setText(_translate("pslab_main_window", "Test Device..."))
        self.action_pin_Layout.setText(_translate("pslab_main_window", "Pin Layout..."))
        self.action_datasheet.setText(_translate("pslab_main_window", "Datasheet..."))


